### ISSUE TITLE
Cannot change folder name on Android 7.0

### ISSUE THREAD

**Issue by magowiz** [OpenLauncherTeam/openlauncher#101]
I'm trying your launcher, but I didn't find the way to rename a folder : I drag a desktop icon over another then I get a folder containing the two icons with name "unnamed", I really don't know if it is a bug or if simply I don't know how to do it, I tried opening the folder and tapping on lower edge, i long pressed that edge, I long pressed folder icon (in this case I have the only possibility to remove it), but nothing. What should I do? Thanks in advance

**Comment by urbanomad64** [comment]
I have the same problem with v. 0.4.0

**Comment by dkanada** [comment]
Yes that is a bug right now, I am currently adding the option to rename any item on the desktop and dock by dragging it onto an edit button. Shortly after that I want to add the option to change the icon as well.
