### ISSUE TITLE
Empty home screen, no icons addable when updating

### ISSUE THREAD

**Issue by mueller-ma** [OpenLauncherTeam/openlauncher#104]
I updated from 0.3.1 to 0.4.0 and now my all my icons are missing, even the app drawer icon. The search button and the clock display are still working.

Android 5.1.1

**Comment by dkanada** [comment]
That was planned for the 0.4.0 update, we moved the desktop items into a database so everything was reset. The next update will reset the app settings since we are also moving those to a new format but there should be no more data loss after that.
