### ISSUE TITLE
App drawer icon is not used in custom icon packs.

### ISSUE THREAD

**Issue by dkanada** [OpenLauncherTeam/openlauncher#106]
I am not sure how nova implemented it but the app drawer icon should change when a custom icon pack is applied, see [this](https://github.com/dkanada/ICEcons/blob/34b56d0909350e7553037ecdd1936891369bc36e/app/src/main/res/xml/appfilter.xml#L738) line for the correct drawable.

**Comment by TomJansen** [comment]
I agree, a feature where you can edit edit the icon of an app  in the drawer would be very handy.
