### ISSUE TITLE
Unable to remove some widgets

### ISSUE THREAD

**Issue by mase76** [OpenLauncherTeam/openlauncher#111]
Hi!
Some widgets, for example the fairphone 2 clock
widget cannot be removed from desktop. The behaviour is as it isn't there when long tapping.
The data of OL has to be reset to get rid of it.

**Comment by BennyKok** [comment]
I have encountered this bug a long time ago, Ha ha.

**Comment by bas89** [comment]
Same here, unfortunately. Resetting the database doesn't solve it, there are widgets in the top left corner that I can't remove directly after placing them.

**Comment by ildar** [comment]
EDIT word is dragable. But if you resized the widget and EDIT is hid then,
yes, you're in trouble :)
