### ISSUE TITLE
Date format in search bar

### ISSUE THREAD

**Issue by mase76** [OpenLauncherTeam/openlauncher#112]
Hi!
Can you make the date format of the search bar configurable? Looks strange for Western Europe users.

**Comment by offa** [comment]
Maybe it's possible to use the system default?

**Comment by mase76** [comment]
That would be an acceptable solution.

**Comment by aabaker** [comment]
As far as I can tell there isn't a system locale format for the day and month without the year. The current code is in Home.java

```
private void updateDesktopClock() {
    if (clockText != null) {
        Calendar calendar = Calendar.getInstance(Locale.getDefault());
        String date = calendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.getDefault()) + " " + String.valueOf(calendar.get(Calendar.DAY_OF_MONTH));
        String date2 = calendar.getDisplayName(Calendar.DAY_OF_WEEK, Calendar.LONG, Locale.getDefault()) + ", " + String.valueOf(calendar.get(Calendar.YEAR));
        clockText.setText(Html.fromHtml(date + "<br><small><small><small><small><small>" + date2 + "</small></small></small></small></small>"));
        }
```

The best option available is probably a configuration option for month first or day number first and to use that to do

```
if (monthFirst) {
    date=calendar.getDisplayName(Calendar.MONTH) + calendar.get(Calendar.DAY_OF_MONTH);
} else {
    date=calendar.get(Calendar.DAY_OF_MONTH) + calendar.getDisplayName(Calendar.MONTH);
}
```

**Comment by antonv6** [comment]
I don't know Java, but it would surprise me if there wasn't a date/time formatting function that can take "%m %d"-style format strings. This format string can be put into settings or at least into translatable resources.

**Comment by gsantner** [comment]
See <https://developer.android.com/reference/java/text/SimpleDateFormat.html>

**Comment by aabaker** [comment]
Translatable resources doesn't work as countries with the same language (e.g. en-us and en-gb) have different norms and some countries the correct default may even depend upon what part of the country you are in. Putting the option in settings therefore seems like the best option but most users won't want to learn the date format syntax so it needs to offer at least a pre defined month first format and a pre defined date first format and possibly a user defined format as well.

**Comment by gsantner** [comment]
If it will get an option, there has to be an default value, yeah. Which could be e.g. the current value
