### ISSUE TITLE
Widget covers status bar

### ISSUE THREAD

**Issue by zelleb** [OpenLauncherTeam/openlauncher#117]
Some widgets cover the status bar. See screenshot
![screenshot_20170518-151832](https://cloud.githubusercontent.com/assets/19358704/26204207/6248a908-3bde-11e7-8dbd-3c442873ea41.png)

**Comment by dkanada** [comment]
Are you using LineageOS?

**Comment by zelleb** [comment]
NitrogenOS

**Comment by dkanada** [comment]
What version of stock android is it based on? I have the same issue but am not sure what the cause is yet, I thought it might be an issue with a specific version of android. Is your ROM based on stock android or is it a fork of LineageOS?

**Comment by zelleb** [comment]
Its based on AOSP
[manifest](https://github.com/nitrogen-project/android_manifest/tree/kenzo)

**Comment by aabaker** [comment]
I can recreate this using current git HEAD in the emulator using the standard calendar widget. As per the original screenshot it needs search bar turned off. My emulator hasn't been updated in ages so is running sdk_google_phone_x86-userdebug 5.1.1 LMY48X
