### ISSUE TITLE
Option to normalise icon size

### ISSUE THREAD

**Issue by Trevonn** [OpenLauncherTeam/openlauncher#122]
https://material.io/guidelines/style/icons.html#icons-product-icons

Some icons don't respect the material design guidelines and hence need to be scaled down so they don't look out of place among the other icons.

**Comment by ildar** [comment]
I see two questions here:
1. How it is supposed to be coded (hardcoded) ?
2. Isn't it the matter for Icon Pack (which is luckily already supported) ?
BTW may I suggest
https://f-droid.org/repository/browse/?fdid=org.xphnx.ameixa , it may solve
your issue in some way?

**Comment by Trevonn** [comment]
I assume you would check which icons are bigger than 48dp which is the suggestion in the guidelines and scale them down to that. 
Nova launcher has the option and it works regardless of the icon pack.

**Comment by gsantner** [comment]
This would mean OL has to analyze every single app icon, and the margins around. Which requires a lot of computing power
