### ISSUE TITLE
New version 0.5.0, missing columns

### ISSUE THREAD

**Issue by klauf** [OpenLauncherTeam/openlauncher#124]
Hi
Thanks for the new 0.5.0 version, lots of improvements. The size of the grid, among other things, works better now. But, i lack the possibility of choosing more rows, i had 14 with the previous version and now the maximum is 10. Can you fix that please? 
Cheers

**Comment by aabaker** [comment]
This is in preferences_desktop.xml

```xml
        <com.benny.openlauncher.widget.NumberPickerPreference
            android:defaultValue="4"
            android:key="@string/pref_key__desktop_columns"
            android:title="@string/columns"
            app:maxValue="10"
            app:minValue="2" />

        <com.benny.openlauncher.widget.NumberPickerPreference
            android:defaultValue="5"
            android:key="@string/pref_key__desktop_rows"
            android:title="@string/rows"
            app:maxValue="10"
            app:minValue="2" />
```

What limits would you like to see? https://developer.android.com/guide/practices/ui_guidelines/widget_design.html suggests a formula for converting a size in dip to the number of widget cells it should map to and as some screens reach 1000 dip that would suggests the maximum should be at least 14 and I would consider <3 unusable so I'm tempted to suggest min=3, max=20 would be sensible

**Comment by klauf** [comment]
Thanks aabaker. Does that mean I could change the value and compile it myself? Sorry for sounding like a noob here. 

I guess 20 would leave enough room, for me on a smartphone definately, maybe on a tablet one would perhaps need a higher value? 
I guess the 'dock' preferences file could also be adjusted accordingly. 

Thanks!

**Comment by aabaker** [comment]
Yes, if you can set up the compile tools then try it and see what works well on your device.
