### ISSUE TITLE
Implement Unit Tests

### ISSUE THREAD

**Issue by aabaker** [OpenLauncherTeam/openlauncher#128]
Some of the classes that involve less UI interaction such as CellContainer would benefit from having unit tests written for them that would simplify testing all of the potential edge conditions and ensure that once something is working the risk if it breaking again due to other changes is minimised.

**Comment by dkanada** [comment]
Yeah, I have been trying to change all of the addXToY methods in CellContainer to handle errors internally when possible, still a work in progress.
