### ISSUE TITLE
Uninstall not possible

### ISSUE THREAD

**Issue by michaelof** [OpenLauncherTeam/openlauncher#131]
Hi,

I wanted to test OpenLauncher, so I installed 0.5.0 from F-Droid. But as I'm getting permanent crashes (seems to be a known issue), I decided to uninstall. Maybe later again :)

Whyever (Android 4.4.2), uninstall is NOT possible:

- in Android's Settings / Apps all Buttons incl. Uninstall are greyed out
- trying from F-Droid leads to "Error uninstalling %s - ... Unknown error ..."
- trying from Google Play, which offers only a "deactivate", no uninstall: "this app has admin functions, which have to be deactivated first" - no idea how 

Please advice how to remove,
thanks,
Michael

**Comment by ildar** [comment]
OpenLauncher magically became the system app?
Please provide screenshot​s, I'm intrigued.
In the meanwhile you can deactivate the app.

**Comment by dkanada** [comment]
I think you might have enabled OpenLauncher as a device administrator, which is required to set the wallpaper. You can't uninstall an app until after you turn that off, it should be somewhere in your device settings.

We are currently working through as many bugs as we can right now, if you would be willing to post the content of your error message from the crash activity I could take a look and see if it's a new bug or if we are already working on fixing it.

**Comment by gsantner** [comment]
@dkanada 
>I think you might have enabled OpenLauncher as a device administrator, which is required to set the wallpaper. 
Are you sure this is needed? Shouldn't be `<uses-permission android:name="android.permission.SET_WALLPAPER"/>` enough?

**Comment by gsantner** [comment]
@ildar 
If somehow you cannot get to there, you can always open that via adb: `adb shell am start -S "'com.android.settings/.Settings\$DeviceAdminSettingsActivity'"`

**Comment by michaelof** [comment]
THANKS to all who answered. dkanada's hint for "device admin" was the solution, thank you !!!

So now that I know how to uninstall I'll let openLauncher installed :-) And try to help testing etc. for the crash-issue. I'll search for similar issues or open a new one, not to mix threads.
