### ISSUE TITLE
team discussion

### ISSUE THREAD

**Issue by gsantner** [OpenLauncherTeam/openlauncher#134]
-

**Comment by dkanada** [comment]
I was wondering why I hadn't heard from you in a while, are you still using gsanter@mailbox.org for the chat?

**Comment by gsantner** [comment]
Yeah, I sent pretty much every day some. Was just wondering because thes are marked as correctly sent on my side. very strange, hm.

**Comment by dkanada** [comment]
Try sending individual messages to @BennyKok or me unencrypted and see if those get through, we can work from that point to see what the issue is. I just tried messaging you and got a failed status.

**Comment by gsantner** [comment]
Thatd what I already tried some days ago. Tried every combination, MUC, normal chat, encrypted non encrypted. Both, desktop and android XMPP client report a successfull received on other side.
strange.
yep, thanks for help. Gonna do some more tests. You gonna see some messages(or tries).

**Comment by dkanada** [comment]
Alright I will let you know if I get a message so just assume the chat still isn't working if I haven't responded in half a day or so. I might be sleeping or something but I usually respond pretty fast.

**Comment by gsantner** [comment]
" dk**da@dk**da.com" is your ID, right? I get "remote-server not found"

**Comment by dkanada** [comment]
Yeah that should be it, can you contact benny at all?
