### ISSUE TITLE
0.5.0 doesn't work at all, after pressing home nothing appears.

### ISSUE THREAD

**Issue by sp-1234** [OpenLauncherTeam/openlauncher#137]
Nexus 5X, latest official firmware, rooted, stock launcher disabled along with Google App.

0.5.0 doesn't work at all, after pressing home nothing appears. No explicit crashes either so I can't be more specific.

Fortunately I could long-press home button to invoke search, that allowed to open Firefox and from there I could get to F-Droid and get out of this almost-stuck situation by installing 0.4.0.

I think for a project of this type it should focus more on stability+security rather than on bells and whistles.

Don't know if this specific problem is fixed in 0.5.1 or not.

**Comment by BennyKok** [comment]
have u tried clearing the data and restart it.

**Comment by sp-1234** [comment]
no, I didn't

**Comment by BennyKok** [comment]
I really need to take times to review the problem as I have been away form the internal part of the launcher for some times.

**Comment by ildar** [comment]
That should be in the FAQ: while in beta, every upgrade users should care
to wipe app data. I don't know, maybe it's worth doing from the app itself.

**Comment by BennyKok** [comment]
I will have some time in this weekend. Stay tuned.

**Comment by dkanada** [comment]
I did mention near the top of the readme and on the front page of the wiki that versions before 0.5.0 are not compatible with the lower versions but we do have a lot of bugs to work through. Is the launcher entirely missing or can you access the minibar? It could be that your desktop is just blank, maybe try long pressing the background to see if the desktop option view shows up. If it does, try clicking on action and adding a new app drawer button.

**Comment by sp-1234** [comment]
as far as I remember, long press on desktop also didn't have any effect whatsoever.
can't test now, because I reverted to previous version and don't have time currently to do it all again, sorry.

**Comment by gsantner** [comment]
@sp-1234 
We are working hard on the project to get to an stable and always upgradeable state, but we are not there yet. We are working on many parts of the app and cannot ensure a upgrade always works, because this would mean a lot of legacy code (which is quite bad if there is a lot).
