### ISSUE TITLE
Missing Icons for Groups

### ISSUE THREAD

**Issue by aabaker** [OpenLauncherTeam/openlauncher#141]
With the "individual icons for items part one " patch thte idValues don't appear to be assigned correctly for Items that are part of a group. As a consequence GroupIconDrawable::draw() is crashing with null pointer exceptions. The following change makes the code more robust - there are potentially other scenarios that could mean the icon file doesn't exist even when idValue is set properly so this change might be worth including even once the underlying issue is fixed. Provided as diff rather than pull request to avoid merge conflicts as you are working in that area.

```diff
--- a/app/src/main/java/com/benny/openlauncher/viewutil/GroupIconDrawable.java
+++ b/app/src/main/java/com/benny/openlauncher/viewutil/GroupIconDrawable.java
@@ -42,11 +42,11 @@ public class GroupIconDrawable extends Drawable {
         final float size = Tool.dp2px(AppSettings.get().getIconSize(), context);
         final Bitmap[] icons = new Bitmap[4];
         for (int i = 0; i < 4; i++) {
-            if (i < item.items.size() && item.items.get(i) != null) {
+            icons[i] = null;
+            if (i < item.items.size() && item.items.get(i) != null)
                 icons[i] = Tool.drawableToBitmap(Tool.getIcon(context, Integer.toString(item.items.get(i).idValue)));
-            } else {
+            if (icons[i] == null)
                 icons[i] = Tool.drawableToBitmap(new ColorDrawable(Color.TRANSPARENT));
-            }
         }
         init(icons, size);
     }

```

**Comment by dkanada** [comment]
Thanks, I still have quite a bit of work with the icons before they are working properly but I would consider it a very important feature for custom launchers, I use it all the time for odd app icons or long names.
