### ISSUE TITLE
Configurable colours of the minibar and desktop folders

### ISSUE THREAD

**Issue by mase76** [OpenLauncherTeam/openlauncher#145]
Hi!
Can you make the colours and transparency of the minibar and the (opened) desktop folders configurable?

**Comment by dkanada** [comment]
Desktop folders were working at one point but I forgot to add them back while I was working on the folder popup, thanks for reminding me. Also, I definitely agree with the minibar customization, been wanting that for a while.

**Comment by gsantner** [comment]
Minibar color editable

**Comment by dkanada** [comment]
folder color working again
