### ISSUE TITLE
Request to implement sound and vibration reaction. 

### ISSUE THREAD

**Issue by alekksander** [OpenLauncherTeam/openlauncher#148]
Please consider adding custom sound and vibration on __icon__ tap  and gesture.

**Comment by dkanada** [comment]
@BennyKok is the phone supposed to vibrate when an app is long pressed? That isn't happening for me right now.

**Comment by BennyKok** [comment]
no, the latest commit is only for gesture, so I haven't close this issue, later there will be another commit for icon tap vibration.

**Comment by BennyKok** [comment]
dkanada, can u receive the message in Conversation?

**Comment by BennyKok** [comment]
@dkanada do you use telegram ? please message me https://t.me/BennyKok
