### ISSUE TITLE
Hardcoded default widgets on first startup

### ISSUE THREAD

**Issue by syefulislam** [OpenLauncherTeam/openlauncher#152]
Can any one help me how can i add my widget as preload on home screen. When i build and run openlauncher, my widget shown by default at home screen.

Thanks in advance

**Comment by dkanada** [comment]
If you mean add it to the codebase, I have no clue how to do that. You can always add it to your desktop manually, why do you want to add it to the code?

**Comment by syefulislam** [comment]
Actually I am working on my custom launcher and wants custom look of home screen like- 
![image](https://cloud.githubusercontent.com/assets/3271954/26518651/5cd51a84-42d6-11e7-9ecd-110a3522801d.png)

**Comment by gsantner** [comment]
You mean, if someone installs OpenLauncher freshly, he should get some defaults, like Caller,SMS, Contacts, Browers, and a search widget?

**Comment by syefulislam** [comment]
@gsantner yes like that. I want clock widget with weather forecasting like picture i have uploaded my previous comment.

**Comment by aabaker** [comment]
Look in Home.java for the lines

```java
                    if (AppSettings.get().isAppFirstLaunch()) {
                        AppSettings.get().setAppFirstLaunch(false);
```
which are followed by the current code to add an appDrawerBtnItem to the database on first launch. You could add extra items at that point but unless you are doing this for inclusion in your own ROM it is impossible to predict what apps would be installed.

**Comment by gsantner** [comment]
@aabaker  I don't think this is about rom builders but a user wanting to have pre-defined apps when first starting. Thats where the game begins, because there are a lot of different apps/packageIds out there, where it needs some way of detecting those.

**Comment by aabaker** [comment]
That was essentially my point, you can do this if you are a ROM builder because you know what apps you are pre-installing but as a general purpose downloadable app it doesn't make sense as you can't know what apps exist on the device it is installed on as even the generic dialler, browser etc may be replaced with custom ones.

**Comment by syefulislam** [comment]
@aabaker I want to add widget as default on home screen, if someone installs OpenLauncher freshly, he should get this widget on home screen.  I am working for clock widget with weather forecasting like picture i have uploaded my previous comment. can you help me how can i add this on OpenLauncher  home screen.
Thanks

**Comment by gsantner** [comment]
@syefulislam As aabaker said, the point where you can hook into to do this is the `if (AppSettings.get().isAppFirstLaunch())` == true line, here you could add stuff.

**Comment by AviFix** [comment]
Can anyone please show an example for how to add an (Hard coded)  icon of an app to the bottom of the grig (desktop)?

Thanks
