### ISSUE TITLE
Icons overlap Android's "top bar"

### ISSUE THREAD

**Issue by pchampin** [OpenLauncherTeam/openlauncher#153]
When the 'Search bar' is disabled, the grid on which icons and widgets are laid out occupies all the space, overlapping Android's "top bar" (the one with the clock and notifications).

I should in fact write "underlapping" as icons and widgets appear to be "behind" the bar. They are mostly visible through transparency, but still, this is not very nice (especially for rectangular widgets, which occupy the space right to the top of the screen).

**Comment by dkanada** [comment]
Are you using a release from F-Droid? I think this has been fixed for the next version, we just have a few more things to do before we push another one.

**Comment by pchampin** [comment]
Yes, I'm using the F-Droid version. Sorry about the noise, then. Looking forward to then next version :)

**Comment by dkanada** [comment]
No worries, bug reports are always welcome :) Hopefully custom labels will be added before the next release, I am working on icons but that may be a bit further off. Also want to add status and navigation bar colors soon.
