### ISSUE TITLE
Search online without Google App

### ISSUE THREAD

**Issue by flocke** [OpenLauncherTeam/openlauncher#158]
Would it be possible to have the "Search online" feature of the search bar available without having the Google App installed?
My suggestion would be to launch the Google App if installed and fall back on just launching a Google search in the Browser if not.

**Comment by ildar** [comment]
Duckduckgo app must be the thing you're looking for.

**Comment by dkanada** [comment]
Just checked the code, it uses a [web search](https://github.com/OpenLauncherTeam/openlauncher/blob/ac9d2b829d5ae5b5c8bfcdf9b5f6bd984907be5f/app/src/main/java/com/benny/openlauncher/activity/Home.java#L504) intent which may not be supported by all browsers. Not sure of a different method we could use but I am sure one exists, definitely don't want to force people to search through the google app if we can avoid it.

**Comment by flocke** [comment]
If it's already a more general intent it's fine in my opinion. I will ask the dev of my browser (Lightning) to handle this intent.

**Comment by gsantner** [comment]
@flocke It's just the intent is intended really for search engines, it's not intended that this should handle >>Insert any webbrowser<<.
I think it's better in the case to send out a Intent.VIEW in case where the exception appears. This way no other app needs to be changed. Currently only the exception text is output.

**Comment by flocke** [comment]
I already submitted a feature request for Lightning. I will let the dev decide if he wants to implement it.
But a fallback is maybe a good idea, maybe even with a configurable search URL for the VIEW intent.

**Comment by flocke** [comment]
Just FYI I'm working on an implementation that checks if there is anything installed that can handle the ACTION_WEB_SEARCH intent and falls back on a ACTION_VIEW intent if not.
I also plan on adding a settings item to make the URL used by the VIEW intent configurable so you are not limited to a Google search.
