### ISSUE TITLE
Resizing widgets is a bit awkward

### ISSUE THREAD

**Issue by johnfocker** [OpenLauncherTeam/openlauncher#167]
Would you consider integrating Trebuchet's widget resizing feature in place of the one you have now?
It seems to me that it would be a good improvement on UX.

**Comment by contrapunctus-1** [comment]
I'm not sure what the resizing UI was like at the time of OP, but it's still the most awkward of all the launchers I've tried. The stock launcher (?) and Fairphone 2 Launcher both have a much nicer way to resize...it would be great if OpenLauncher used that instead, too.
