### ISSUE TITLE
0.5.1 (22)  app icons on folder gets folder name Android 7.0

### ISSUE THREAD

**Issue by magowiz** [OpenLauncherTeam/openlauncher#171]
When creating a folder, dragging an icon over another, all app icons in new folder are named "unnamed", like folder name. If I rename the folder (and restart launcher, otherwise the folder won't get new name), also the app icons inside get this new name

#### General information

* **Device:**   Lenovo Moto G5
* **Android Version:**  Android 7.0
* **App version:**  v0.5.1

#### Steps to reproduce

1. create a folder
2. see that folder name and icons in that folder are named "Unnamed"
3. change folder name
4. see that app icons are named with new name 

#### Expected result
**What is the expected output?** 
app icons should keep their names unless I choose to edit them
**What do you see instead?**
app icons name gets binded to folder name.

![screenshot_20170625-201251](https://user-images.githubusercontent.com/1067544/27518615-60173d4c-59e4-11e7-89bf-603181cac642.png)

Logcat:$ sudo adb logcat -s com.benny.openlauncher
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
--------- beginning of system
--------- beginning of main

**Comment by dkanada** [comment]
This is already fixed, I was waiting to push another update until I had the framework for the custom icons in place. I suppose I could just push an update with only the custom labels but then the icons will break when I add the functionality, what do you think @BennyKok? I could also add legacy code for the icons too but since the app is in beta I am against that option.

**Comment by dkanada** [comment]
nice wallpaper btw

**Comment by dkanada** [comment]
@magowiz are you still having this issue in 0.5.3 or has it been fixed?

**Comment by magowiz** [comment]
I'm using 0.5.3 and the issue has been fixed. Icons keeps their name and editing folder name doesn't change the inner icons . Thanks.
