### ISSUE TITLE
Master branch icon handling - no files in app's files directory

### ISSUE THREAD

**Issue by MFlisar** [OpenLauncherTeam/openlauncher#172]
I'm talknig about copying icons to the app's files directory.

Is this a beta feature that's not yet implemented completely? What's the goal of it?

The master branch will crash when trying to create a folder because no icons are saved in the files directory. The folder's content will use the `AppManager.App` item and uses it's `icon` field, why not just use this field for the folder's icon as well?

**Comment by dkanada** [comment]
Yeah I was working on implementing custom icons but have been busy lately, my solution was just to save the icons for each item on the desktop in that folder and allow users to select any icon from installed icon packs, it isn't very far along yet.

**Comment by MFlisar** [comment]
So the goal is to have access to icon pack items after those icon packs have been deinstalled? So apps without custom icons should just get the default icon? It does not make sense to copy the default icon to the folder, does it?

**Comment by dkanada** [comment]
Well the main goal is just to allow for custom icons, I didn't even consider that the icons would also be available after the packs were uninstalled. You are definitely right though.

**Comment by MFlisar** [comment]
Ok, then my change in my pull request is fine which does just load the apps default icon as you will have to change this anyways again and decide if a custom icon should be loaded or the default icon. Is there any way to discuss general things anywhere? Like gitter or so?

**Comment by dkanada** [comment]
We have a group on xmpp right now and are moving over to Telegram or some other service I think.

**Comment by gsantner** [comment]
@dkanada @BennyKok What about Matrix/Riot? It offers good integrations

**Comment by dkanada** [comment]
Oh I thought you already had a group over on Telegram with Benny? I haven't been able to look into it yet, I was going to look at Signal and Wire first since both of those look great as well.

**Comment by gsantner** [comment]
@dkanada Yeah, we got one, he just told me you don't want that? If not so, then just send a msg.

**Comment by dkanada** [comment]
Oh well I just don't have an account with Telegram so I was going to consider whether I wanted to make one or not, don't wanna switch services more than once if I can avoid it. Telegram has a lack of multi device support for encryption, Signal doesn't support encrypted file transfers, I don't think Wire has a native desktop client, I also tried Matrix and the chat service was not the best, so they all have downsides haha. I will just mull over it for a bit, you guys can do whatever, don't wait for me =p I am leaning towards Signal or Wire though.

**Comment by dkanada** [comment]
You are right though, xmpp had a ton of issues with encryption and group chats.

**Comment by gsantner** [comment]
Signal is somewhat bound to either Android or iOS. And may require gplay services. Ofc its up to you. I think there are a lot of discussions about all of the current available messengers and services out there

**Comment by MFlisar** [comment]
Never considered gitter.im? It can be used in the browser and supports all systems I could think of. And I've seen it in a few repositories already being used for questions and discussions.


And I first did not need a group and just wrote via mail with bennykok but  now I think I have a few questions and a few things to discuss

**Comment by gsantner** [comment]
@MFlisar Tried it in another project. Hard to convience people to use it^^. I think we gonna stay with XMPP, we will give you details when we made a decision.

**Comment by MFlisar** [comment]
Ok, no problem. Just let me know when you have something

**Comment by BennyKok** [comment]
So what will we be using now?

**Comment by MFlisar** [comment]
I close the issue, the main issue was explained and is so to say solved

**Comment by ildar** [comment]
Btw, gitter.im has the irc gate. People can be settled by it.
