### ISSUE TITLE
Extract refactoring - discussion

### ISSUE THREAD

**Issue by gsantner** [OpenLauncherTeam/openlauncher#179]
This issue is about the extract-refactoring branch and the work on the extraction, which was started by @MFlisar.

Todo:
* [ ] Allow setting dateformat in search bar (see enum) -> preferences
  * [ ] Custom format -> preferences

**Comment by MFlisar** [comment]
I've just added some id for this in my repo, I'd suggest using ids for enums because this way you can change the order of enums anytime without problems, I personally always do this whenever I save an enum value anywhere like in a database...

**Comment by gsantner** [comment]
What about a plain String which just holds the formatting string? Seems to be the easiest solution, and a String is needed anyway

**Comment by MFlisar** [comment]
You're right, in this case that's best. You can anyway remove the enum, it's just there for compatibility with the current app. Just the user interface should provide a list of predefined formats, the search bar does not need to know anything about this list...

**Comment by gsantner** [comment]
Are there other new enums (didnt notice yet)

**Comment by MFlisar** [comment]
I personally want to see the time as well, the tick event comes anyway already every minute... So I added the most common formats as predefined enums, but feel free to completely remove them again

**Comment by gsantner** [comment]
Closing as inactive (OR done)
