### ISSUE TITLE
Remove app icon is showing up in all apps mode in the launcher 

### ISSUE THREAD

**Issue by TeamBrainStorm** [OpenLauncherTeam/openlauncher#18]
I was testing the all apps mode in the launcher and found a bug. When you drag a app around the remove option comes up as well as the uninstall. but when an app is installed from the play store and you go to drag it around the only option that shows up is the remove option uninstall does not show up. is there any way to remove the remove option from all apps mode? 

Thanks in advance!

**Comment by BennyKok** [comment]
When you install an app the launcher will directly add the shortcut intent to the desktop so it is not an app object so only remove is shown,

I will fix this `remove the remove option from all apps mode?` and that too.
But currently I am busying with a app competition. Damn....

**Comment by gsantner** [comment]
All apps mode was removed for now
