### ISSUE TITLE
Gesture titles not changing inside settings

### ISSUE THREAD

**Issue by baa56f7e38625b65db06e39cd863bd2f8c71847** [OpenLauncherTeam/openlauncher#180]
#### General information

* **Device:** OnePlus
* **Android Version:** Android 7.1.2
* **App version:** v0.5.3

#### Steps to reproduce

1. Settings
2. Gestures
3. Click on any gesture other than "Double tap"

#### Expected result
**What is the expected output?** 
Titles should reflect the option.

**What do you see instead?**
All titles are "Double tap"

Pretty cosmetic issue. It doesn't cause any problem. Thought it might help pointing out, though. By the way, congratulations! The app is impressive.

**Comment by dkanada** [comment]
Thanks for the bug report, this one will be an easy fix :D we are always changing a lot of the code so sometimes things slip through, turns out launchers have a lot of moving parts.

**Comment by BennyKok** [comment]
what a bug...
