### ISSUE TITLE
Remove widgets/apps with desktop

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#182]
Ok. Now that the major irritating bugs are concurred, let's get to others. No 1:
#### Steps to reproduce

1. Remove a desktop
2. Create a desktop again with dropping an app
3. restart OL

#### result
**What do you see instead?**
Apps and widgets of _removed_ desktop appear on the newly created desktop

**Comment by dkanada** [comment]
This one makes sense at least, we probably aren't removing old items when a page is removed. The same thing happened when we added the ability to remove groups, the individual items were still showing up in the database.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - not happening anymore.

**Comment by ildar** [comment]
Excuse me, what kind of activity you expected here?
The issue is obvious and nobody cared to fix it. Did you, @gsantner, test
if it's fixed or not? Or even asked users/me?

**Comment by ildar** [comment]
I know there are "minor" issues like crashes after upgrade. But not all
issues are alike. You've got quite many real bugs still unfixed. Closing
them will not do any good to the project. Are you still sure?

**Comment by gsantner** [comment]
i tried to reproduce this and it did not happen. Why should this be rethought?

**Comment by ildar** [comment]
Oh, that's good news worth sharing.
Then closing this issue is a good move. Thanks.
And thank the team for working on issues.
