### ISSUE TITLE
Shortcut support

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#183]
Ok. Now that the major irritating bugs are concurred, let's get to others. No 2:
[Termux widget "Single shortcut 1x1"](https://fossdroid.com/a/termuxwidget.html) should be in the list of widgets

**Comment by ildar** [comment]
Also Contacts (std Android app) widgets are missing, like: Quick Call/SMS 1x1 etc.

**Comment by dkanada** [comment]
If the termux widget is 1x1 why are some screenshots in that link showing a larger widget maybe two or three spaces across? I am thinking that the missing widgets are actually shortcuts, most launchers dont have different locations for the two.

**Comment by ildar** [comment]
The termux widget "All shortcuts" is 2x2 and it's in the list. The problem
is 1x1 widget (possibly shortcut).

Do you mean that 1x1 shortcuts aren't supported by OL?

**Comment by dkanada** [comment]
Widgets, shortcuts, and apps are all separate items but most launchers combine the shortcuts and widgets in a single selection area. Widgets display data from and app on the home screen wheras shortcuts are usually just a link to a specific page or function in an app. I am guessing OpenLauncher isn't properly supporting shortcuts right now. @BennyKok I think that keeping the two on separate dialogs would be a good idea.

**Comment by ildar** [comment]
Guys, anybody please confirm or decline the lack of Application Shortcuts
in OL.

**Comment by sunng87** [comment]
I confirm ol doesn't support shortcut at the moment. I have a few shortcuts and there is no way to add for now.

**Comment by dkanada** [comment]
I think we have a few classes in the code for shortcuts but they aren't used at the moment, this should actually be a higher priority since lots of apps use shortcuts in addition to widgets. Some apps actually do have shortcuts that can be created manually inside the app (Lightning Browser has shortcuts for websites) but most don't.

**Comment by sunng87** [comment]
@dkanada by the way, could please create a 0.5.4 tag for the release? I'm using OL from F-Droid. It won't update until a tag is created.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening

**Comment by source124** [comment]
Bump for +1.

Many apps shortcuts cannot be added from within. They can be done through the launcher only. Thank you

**Comment by gsantner** [comment]
duplicate @dkanada

**Comment by dkanada** [comment]
Whoops.
