### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by testman42** [OpenLauncherTeam/openlauncher#186]
Why is there no IRC channel yet for this project?
#openlauncher on Freenode is not taken yet.
What about forums or any other platform for community to discuss things related to this project?

**Comment by dkanada** [comment]
We mainly use github to talk about things, I don't think any of us really use IRC so that's why we don't have a channel on freenode. If you have a feature you'd like to see or just want to start a discussion on some aspect of the project you can always use the issue tracker, that's where I am most active anyways.

**Comment by BennyKok** [comment]
maybe we should think about it. how about discord?

**Comment by testman42** [comment]
Depends on how much you like proprietary software.

**Comment by nailyk-fr** [comment]
+1 for IRC. 
If there is other further need, gateways are almost easy to setup ;)

**Comment by BennyKok** [comment]
I don't know how to set up the channel.... it's a bit complicated. I need a bit of googling.

**Comment by nailyk-fr** [comment]
Feels free to /query me on Freenode, I should be able to help you on this. 
Many thanks!

**Comment by nailyk-fr** [comment]
Any new on this? 
I should be able to handle it for you if you need. 

Not related: but wasn't able to find you on mastodon: https://mstdn.fr/@nailyk/99337361841549245

**Comment by BennyKok** [comment]
Sorry @nailyk-fr I don't have much free time these days, so if you can help me to set it up, I will appreciate that, anyway thanks for the post on mastodon, ha ha, I might set up an account on mastodon later.

**Comment by gsantner** [comment]
We have a community channel on Matrix now - join: [![Chat - Matrix](https://img.shields.io/badge/chat-on%20matrix-blue.svg)](https://matrix.to/#/#openlauncher:matrix.org) - it's `#openlauncher:matrix.org`
