### ISSUE TITLE
Can't scroll to the bottom of the search page

### ISSUE THREAD

**Issue by 12people** [OpenLauncherTeam/openlauncher#187]
When scrolling to the bottom of the search page, the keyboard covers a number of apps. Even with the keyboard hidden, the last app is stuck behind the system software keys.

Here are screenshots of the farthest I can scroll:

<img width="30%" height="30%" src="https://user-images.githubusercontent.com/7361228/28032246-15f95e30-65aa-11e7-892c-747793b13693.png">

<img width="30%" height="30%" src="https://user-images.githubusercontent.com/7361228/28032247-1603f5e8-65aa-11e7-9009-9d0e19ace91b.png">

#### General information

* **Device:** Nexus 5
* **Android Version:** Android 6.0.1
* **App version:** v0.5.1

#### Steps to reproduce

1. Click on search icon
2. Scroll to the bottom

**Comment by dkanada** [comment]
Quick update on this issue, the overlap with the notification bar should be fixed. We are still thinking about possible solutions for the keyboard overlap.

**Comment by BennyKok** [comment]
should be fixed
![image](https://user-images.githubusercontent.com/18395202/28753264-7ed6d346-7564-11e7-8245-fb88a72218df.png)
