### ISSUE TITLE
issue when you turn off device and your on a empty page in all apps mode 

### ISSUE THREAD

**Issue by TeamBrainStorm** [OpenLauncherTeam/openlauncher#19]
I found another bug this one is when your in all apps mode and there are no apps on a screen and you turn off the device with the page with no apps active and turn it back on all the apps are gone except the ones on the dock. I think that if we make it to where if there are no apps on a page that page goes away in all apps mode only! That's just my thoughts on the matter :)

**Comment by BennyKok** [comment]
ok

**Comment by BennyKok** [comment]
sorry I don't have time to check out the errors u reported as I really don't have time and there are some bugs that are even more annoying, so I need to set them a priority.

**Comment by gsantner** [comment]
All apps mode was removed for now
