### ISSUE TITLE
Better detection of/access to icon packs

### ISSUE THREAD

**Issue by conrad-heimbold** [OpenLauncherTeam/openlauncher#190]
My java skills are limited, so please correct me if I'm wrong
### State at the moment 
OpenLauncher only detects apps as icon pack apps, if they have got an xml file called "appfilter" inside their apk, if I understand the [IconPackHelper class](https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/util/IconPackHelper.java ) on line 236 correctly.  
=> **CheckForAppfilterXMLFile()**
The [MaterialOS icon pack / theming app](https://github.com/materialos/CM12-Theme) for example does not get recognized inside OpenLauncher. 

### Improvement possibilities: 
Detect icon pack apps by 
- checking if the scanned app uses the feature "org.cyanogenmod.theme" according to its AndroidManifest, just like the MaterialOS icon pack; see its [Android Manifest](https://github.com/materialos/CM12-Theme/blob/master/theme/src/main/AndroidManifest.xml) on line 21. The AndroidManifest.xml should contain the following string: 
```<uses-feature android:required="true" android:name="org.cyanogenmod.theme" />```
=> **CheckForUsedThemingFeature()**

- Checking if the app apk contains a file path beginning with "assets" and ending with ".png" or ".jpg" (just like Apps2Org , see its function isAssetImage() on line 164 inside the class [ChooseIconFromPackActivity]( https://github.com/willemw12/apps2org/blob/ui/app/src/main/java/com/google/code/appsorganizer/chooseicon/ChooseIconFromPackActivity.java ). 
This detection however is very broad and also detects many normal apps, so we could improve it by only treating apps  as icon packs if their apk contains more than 30 file paths (or any other reasonable number of it) beginning with "res" or "assets" and ending with ".png". Just look for the implementation in Apps2Org. Icon pack apps normally have icons for more than 30 divided by at least 3 (for all the *dpi sizes) = 10 apps. 
=> **CheckForManyRessourceOrAssetFiles()**

- checking if the 
``<application android:name="..." android:description="..."``  or ``android:label="...">`` or 
``<category android:name="..." >`` inside ``AndroidManifest.xml`` contains the strings "icon pack" or "theme" (see the Android Developer Guide for Android Manifest [application](https://developer.android.com/guide/topics/manifest/application-element.html) and [category](https://developer.android.com/guide/topics/manifest/category-element.html) elements)
=> **CheckForSuitableMetadataStrings()**

- Checking if the app offers some kind of [Content Provider functionality](https://developer.android.com/guide/topics/providers/content-provider-creating.html) for icons. This is **actually the prefered way of sharing data between apps** on Android, according to the doc's, but unfortunately; no icon pack app so far implements it. That's probably because of the much overhead generated if every icon pack app includes its own theming engine... ICEcons maybe will, see issue dkanada/ICEcons/issue/#59! 
=> **CheckForIconFileContentProvider()**

You could also combine multiple detection options to make the recognition even more precise.

**Comment by MFlisar** [comment]
Tried it with the theme debug apk from here: https://github.com/materialos/CM12-Theme/blob/master/theme-debug.apk

**Comment by MFlisar** [comment]
Icon packs work by providing an appfilter.xml. Without it you can not match apps with icons...

This icon pack has it's appfilter.xml here: https://github.com/materialos/CM12-Theme/tree/master/theme/src/main/assets/icons/res/xml

Normally it's either in the apps res directory or assets directory. Additionally checking for the above mentioned xml file and using it instead should do the trick already...

**Comment by conrad-heimbold** [comment]
I would like to create an icon pack that uses icons for **categories**. I am working on it. I like to sort my apps on the homescreen by **category (e.g. short-messaging apps, browsers, etc.)**. So an appfilter is not always the best choice for detecting icon packs, I would say.

**Comment by MFlisar** [comment]
Ok. If this is something common it's new to me, did not know that...

**Comment by conrad-heimbold** [comment]
@MFlisar **No**, it's **not common at all**. There is **no icon pack app existing for it yet**, that's why I would like to create it :)

**Comment by conrad-heimbold** [comment]
You are probably right, **ALL** icon pack apps **should have a kind of appfilter file** (maybe with a **different name**). If you think you shouldn't care about my icon pack app, please close this issue...

**Comment by conrad-heimbold** [comment]
@MFlisar: but what happens if the icon pack does not name the file, that fulfills the appfilter function, as "appfilter.xml"? Some kind of abstraction / broader detection would be very handy, I think.

**Comment by MFlisar** [comment]
Actually there must be some contract between icon packs and apps that use
icon packs. The xml defines which icon belongs to which app by defining a
mapping of icons <=> app package name and app activity name. Without that
an app can't know that the icon phone.png is the icon for the phone app
which is defined like com.samsung.phone/.MainActivity (guessed example but
that's the format an apps activity is defined). The same icon may be the
icon for a lot of other activities too like other manufactures phone app or
some other app that should use the same icon of this icon pack.

Grouping can easily be added by extending the contract or by defining an
additional xml file.

I think there are launchers that support grouping, ever checked some of the
big icon templates and if they have something for grouping?

conrad-heimbold <notifications@github.com> schrieb am Do., 13. Juli 2017,
12:09:

**Comment by MFlisar** [comment]
I just checked an icon pack template and saw that those sometimes have grouped items... Not sure if any launcher supports such groups yet or if those are defined in a common way between different icon pack templates...

This grouping was the grouping I was remembering. I think I've seen automatic grouping in launcher as well already but I don't remember in which app. But still I would guess it's based on the play store's category.

But thinking about it again I would say, that grouping should be a feature of a launcher not of an icon pack though...

**Comment by conrad-heimbold** [comment]
Well, I am even using a separate app for grouping - Apps2Org . Apps2Org already has quite sophisticated grouping / tagging functionality, the only missing feature of Apps2Org is automatically added icons for those categories.

**Comment by conrad-heimbold** [comment]
Do you know if any icon pack app is using the [**Content Provider functionality**](https://developer.android.com/guide/topics/providers/content-provider-creating.html) on Android as a way to permanently give other apps access to the icon files?

**Comment by MFlisar** [comment]
When I searched the internet the last time I only found the appfilter.xml way in combination with some definition in the manifest.

Technically a content provider solution is possible though... But making your own way for you icon pack will lead to that it is not usable for other apps like nova and similar...

**Comment by conrad-heimbold** [comment]
I can still provide multiple means of access in my app. APK-based access with appfilter.xml doesn't contradict access with Content Providers. 

Apart from that, it's the classical chicken-and-egg problem. I made an issue (#59) specifically for the Content Provider functionality in [ICEcons](https://github.com/dkanada/ICEcons), an icon pack app which I've been actively contributing to.

**Comment by MFlisar** [comment]
You're right, nothing speaks against multiple ways of accessing icons.. Maybe you're just the investor of a new way of icon loading

**Comment by gsantner** [comment]
Can this be closed?

**Comment by dkanada** [comment]
I think this is out of scope for this launcher, since it would require icon packs to support an entirely new detection method.
