### ISSUE TITLE
Show hidden apps in search results

### ISSUE THREAD

**Issue by 12people** [OpenLauncherTeam/openlauncher#193]
The apps that I hide from the app grid are generally apps that are installed by default and I don't want to clutter up the grid. However, once in a while, I need to revisit such apps (e.g. "Google settings"). It'd be really useful if these apps showed up in the offline search results. To not clutter the results, there could be a "Show hidden apps" button if you deem so necessary.

**Comment by gsantner** [comment]
Done and available in next release.
