### ISSUE TITLE
[improvement suggestion] Open App drawer when pressing HOME on main home screen/a second time

### ISSUE THREAD

**Issue by conrad-heimbold** [OpenLauncherTeam/openlauncher#196]
If you are already on the main homescreen, pressing the home button again doesn't do anything. 
However, we could **offer to open the app drawer** then. 
So: 
- if you are on the **main homescreen**
- and you press **HOME** again
OR
- if you press **HOME** twice (equivalent to the above)
=> then open the app drawer. 
This should be a customizable option, of course. 

Benefit: 
- The app drawer button can be left out from the dock / home screen, gaining more space. 
- you can open the app drawer from **any app** by pressing **HOME** twice 

Benefit 2 is only available as long as that double-tap does not get catched by the system and executes something different. On LineageOS 14 devices, you can specify on system level (in settings) what should happen if you press HOME twice. If you keep "No action" for this setting, OpenLauncher (or, more in general, the default HOME app) can detect the double-tap.

**Comment by MFlisar** [comment]
Little sidenote: double pressing home is often catched by the system and starts the camera...

**Comment by conrad-heimbold** [comment]
Didn't know that: on my phone, double-click on the **on-off-button** at the side does that.

**Comment by MFlisar** [comment]
It's like that on my samsung phone

**Comment by conrad-heimbold** [comment]
Well, opening app drawer will still work, if you are already on the homescreen and press HOME again. 
You just have to wait more between the two HOME presses.

**Comment by MFlisar** [comment]
Was just a hint to consider when implementing this. The single click idea sounds good, I would like this as well. And it's a simple improvement

**Comment by conrad-heimbold** [comment]
On LineageOS 14 devices, you can also specify on system-level (in settings) what should happen if you press home twice. If you keep "no action" for this system setting, OpenLauncher can detect the double tap.

**Comment by conrad-heimbold** [comment]
same as #102, therefore closing
