### ISSUE TITLE
Place widget (1 row items only) in dock

### ISSUE THREAD

**Issue by conrad-heimbold** [OpenLauncherTeam/openlauncher#199]
It would be cool if you could place widgets as well on the dock. So far, it doesn't work; see attached screen recording. 
 
<image src="https://user-images.githubusercontent.com/17474312/28619747-3cc04256-720a-11e7-8137-c0b77857b132.gif" />

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
