### ISSUE TITLE
Cannot change colors of desktop folders

### ISSUE THREAD

**Issue by mase76** [OpenLauncherTeam/openlauncher#202]
Hi!
Changing the desktop colors is the settings does not have an effect.
They remain grey.
Is it possible to adjust the background color of the opened folders?

**Comment by babyskill** [comment]
I saw this code in core:
`view = new AppItemView.Builder(context, iconSize)
                        .setAppItem(item, app)
                        .withOnTouchGetPosition(item, Setup.itemGestureCallback())
                        .vibrateWhenLongPress()
                        .withOnLongClick(item, DragAction.Action.APP, new AppItemView.LongPressCallBack() {
                            @Override
                            public boolean readyForDrag(View view) {
                                return true;
                            }

                            @Override
                            public void afterDrag(View view) {
                                callBack.setLastItem(item, view);
                            }
                        })
                        .setLabelVisibility((flags & NO_LABEL) != NO_LABEL)
                        .setTextColor(Color.WHITE)
                        .getView();`

**Comment by dkanada** [comment]
fixed in the next update
