### ISSUE TITLE
App items vanish from desktop sometimes

### ISSUE THREAD

**Issue by MFlisar** [OpenLauncherTeam/openlauncher#204]
I see that apps vanish from my desktop sometimes. I'm constantly pushing new versions to my phone while developing and this means, the desktop is created very often. Sometimes apps are updating right at this moment. Seems like OL thinks an app is deinstalled and therefore removes the item from the desktop.

I think this is the reason, but this is just a guess: 
https://github.com/OpenLauncherTeam/openlauncher/blob/master/core/src/main/java/com/benny/openlauncher/core/widget/GroupPopupView.java#L129

*Idea*

* app is updated (which means it's deinstalled and newly installed for OL, because the app won't be loaded in the apps list while it's updated)
* OL is launcher and desktop created
* desktop does not find the item's app and removes the item from the database

Only an idea, have not checked it though...

It's happening rarely, but I already saw it about 3-4 times...

**Comment by ShapeShifter499** [comment]
could this be related to or a cause of my issue?   https://github.com/OpenLauncherTeam/openlauncher/issues/60

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
