### ISSUE TITLE
Icon Package

### ISSUE THREAD

**Issue by beli3ver** [OpenLauncherTeam/openlauncher#205]
Hi,

I want to repack my Icon theme [Paper-FOSS-Theme](https://gitlab.com/beli3ver/Paper-FOSS-Theme) to be used in your launcher.
Is there a template or a special needing to be used in your launcher?

Thanks

**Comment by conrad-heimbold** [comment]
@beliv3r 

The appfilter.xml file has to be located under /res in  the apk. This is the only requirement so get the icon pack recognized so far. 
Having the apk under /assets doesn't work so far (at least not for the version on F-Droid).

**Comment by dkanada** [comment]
@beli3ver we use the same standard used in a lot of other launchers so if your app works in Nova it should work in this app as well.
