### ISSUE TITLE
[small bug] erratic homescreen sliding behaviour with big background picture

### ISSUE THREAD

**Issue by conrad-heimbold** [OpenLauncherTeam/openlauncher#211]
#### General information

* **App version:** 0.5.3
* **Android Version:** Android 7 (LineageOS 14.1)

#### Expected result
**What is expected?** 

Sliding through the homescreens should be as smooth as possible, even with large (in terms of file size) background pictures and phones that have only few RAM (like mine - Moto G, 1GB RAM). 

**What does happen instead?**

When sliding through home screens, I get erratic behaviour: in one millisecond, the icons move faster, then the background moves faster, etc. 

See video on: http://sendvid.com/la9ou3i3 

#### Steps to reproduce
- get a smartphone with few RAM
- Get a really big (in terms of file size), high-quality background picture
- Scroll through your homescreens (you need to have set multiple of them)

**Comment by BennyKok** [comment]
I really not sure how to fix this....  at this moment

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
