### ISSUE TITLE
Extended mini-bar

### ISSUE THREAD

**Issue by dimqua** [OpenLauncherTeam/openlauncher#212]
Please add more buttons to the mini-bar. It would be nice to have, for example, wi-fi, data and profile togglers, shutdown button and airplane mode button.

**Comment by iknownothingaboutcomputers** [comment]
@dimqua @dkanada Although I've enabled this minibar in Settings, I don't see it anywhere. My phone's running on Android 5.1. Please help.

**Comment by dkanada** [comment]
@iknownothingaboutcomputers on the home screen you can swipe from the left edge and the minibar should slide out.

**Comment by iknownothingaboutcomputers** [comment]
@dkanada Thank you. Got it. Sorry for the late reply.

**Comment by xxvixxy** [comment]
I'd also like to see the minibar have some extra features. Like apps perhaps.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening

Open specific issues for specific addins - and maybe send PRs for that ;)
