### ISSUE TITLE
Widget zombies

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#217]
If a user removes an app while this app's widget was on the OL desktop, then the widget becomes "zombie": doesn't draw but still occupying space, unable to be removed (or killed anyhow else)

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening

**Comment by ildar** [comment]
Xcuse me, you sure you tested this one?
The behavior changed a bit but got no better: now the place of the widget
is marked "cannot create widget" and that frame is unable to be dragged nor
deleted.

**Comment by gsantner** [comment]
as you can see yourself, your description is absolutely nothing in it that is in the issue description. So go ahead and create a issue.

Thats very exact the reason I close stuff.

**Comment by ildar** [comment]
Now the wrong behavior is like that: the place of the widget is marked
"cannot create widget" and that frame is unable to be dragged nor deleted.
Reopen please?

**Comment by gsantner** [comment]
just open a new issue
