### ISSUE TITLE
Widgets are hard to pick up

### ISSUE THREAD

**Issue by Neui** [OpenLauncherTeam/openlauncher#219]
#### General information

* **App version:** 0.5.3 (F-Droid)
* **Android Version:** 4.2.2
* **Phone:** GT-I8200N (Galaxy S3 Mini)

#### Expected result

**What is expected?** Longpressing/Holding on the widget should pick it up.

**What does happen instead?** Most of the time, the page zooms out to the thing where you can delete pages, add widgets et cetera. It works sometimes, but seems to be unreliable.

#### Steps to reproduce

* Place a widget (like the clock) on a page (only really used with widgets that take the full width (4 squares) at the top of the page)
* Longpress on the widget

**Comment by ildar** [comment]
https://github.com/OpenLauncherTeam/openlauncher/issues/111
https://github.com/OpenLauncherTeam/openlauncher/issues/182

**Comment by Neui** [comment]
Oh, I'm sorry, due to the titles, it looked like they weren't related to my problem. This probably can then be closed as a duplicate.
