### ISSUE TITLE
App name remain unchanged after the group was left empty

### ISSUE THREAD

**Issue by BennyKok** [OpenLauncherTeam/openlauncher#22]
To reproduce the error

1. Drag an app over another
2. Open the group
3. Drag a app out
4. The app name will remain "Unnamed"

The problematic code is around the [GroupPopupView](https://github.com/BennyKok/OpenLauncher/blob/master/launcher/src/main/java/com/benny/openlauncher/widget/GroupPopupView.java#L261) in the `removeItem `method
The code from 268 to 286 was able to set the `Drawable` of the app item back to an normal app item, but the name just wont change.

**Comment by dkanada** [comment]
I have been digging though the code looking for a fix. When one app is dragged into another app, where is the item changed to a group? I can see that the group enum is set at https://github.com/BennyKok/OpenLauncher/blob/6885717a47664e6c5eccdbb9aa116e5ca2e930ea/launcher/src/main/java/com/benny/openlauncher/widget/Desktop.java#L544 but that looks like it only triggers if the item is already a group.
