### ISSUE TITLE
Unable to pick up Apps from the drawer

### ISSUE THREAD

**Issue by flocke** [OpenLauncherTeam/openlauncher#222]
#### General information

* **App version:** 0.5.4 (from Google Play)
* **Android Version:** 7.1.2_r33 (SAOSP-N)

#### Expected result
**What is expected?** 
Long clicking on a app icon in the drawer should pick it up so I can place it on my desktop

**What does happen instead?**
The icon is not picked up when long-clicking it

#### Logcat
I only posted the (probably) relevant portion of the logcat, this error happens every time I long-click an icon in the drawer.

```
08-18 09:32:55.862 14679 14679 D Hey     : ACTION_DOWN
08-18 09:32:56.024 14679 14679 D Hey     : ACTION_UP
08-18 09:32:56.025 14679 14679 D Hey     : 570  -269  
08-18 09:32:56.802  5071  6567 D WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
08-18 09:32:56.806  5071  5131 E BatteryStatsService: no controller energy info supplied
08-18 09:32:57.511 14679 14679 W System.err: java.lang.IllegalStateException: Drag shadow dimensions must not be negative
08-18 09:32:57.512 14679 14679 W System.err: 	at android.view.View.startDragAndDrop(View.java:20696)
08-18 09:32:57.512 14679 14679 W System.err: 	at com.benny.openlauncher.core.util.DragDropHandler.startDrag(DragDropHandler.java:27)
08-18 09:32:57.512 14679 14679 W System.err: 	at com.benny.openlauncher.core.widget.AppItemView$Builder$6.onLongClick(AppItemView.java:360)
08-18 09:32:57.512 14679 14679 W System.err: 	at android.view.View.performLongClickInternal(View.java:5714)
08-18 09:32:57.512 14679 14679 W System.err: 	at android.view.View.performLongClick(View.java:5672)
08-18 09:32:57.512 14679 14679 W System.err: 	at android.view.View.performLongClick(View.java:5690)
08-18 09:32:57.512 14679 14679 W System.err: 	at android.view.View$CheckForLongPress.run(View.java:22398)
08-18 09:32:57.512 14679 14679 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
08-18 09:32:57.512 14679 14679 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-18 09:32:57.513 14679 14679 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-18 09:32:57.513 14679 14679 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6203)
08-18 09:32:57.513 14679 14679 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-18 09:32:57.513 14679 14679 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-18 09:32:57.513 14679 14679 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

#### Steps to reproduce
 * Clear database in OL settings and clean app data for OL
 * Start populating the desktop by dragging apps from the drawer
 * At some point I can not pick up apps from the drawer anymore (I long-click on them but nothing happens)
 * The point at which it stops to work seems random to me (I wasn't able to figure out any triggers, the amount of apps I managed to put on the desktop before it stopped working was different in my tests).

**Comment by EmmanuelMess** [comment]
Can replicate. 
Android 6.0.
Version: 42e2d98f3c0cc64e480fda708278719bd302617a
Motorola Moto E Gen 2 4G

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening

I don't see any problems in current master branch version

**Comment by EmmanuelMess** [comment]
It's unpredictable, trying to fix the bug in code, I stopped being able to replicate, no idea how.

**Comment by gsantner** [comment]
@EmmanuelMess If you find something feel free to send a PR 😄
