### ISSUE TITLE
Swipe indicator

### ISSUE THREAD

**Issue by dimqua** [OpenLauncherTeam/openlauncher#223]
Would be nice to have a swipe indicator at the bottom of homescreen, like this:

![](http://i.imgur.com/n3y0VyX.png)

**Comment by alekksander** [comment]
which launcher is it from?

**Comment by dimqua** [comment]
@alekksander [Lawnchair](https://github.com/Deletescape-Media/Lawnchair).

**Comment by alekksander** [comment]
@dimqua thank You
