### ISSUE TITLE
Set up Flattr

### ISSUE THREAD

**Issue by 12people** [OpenLauncherTeam/openlauncher#224]
Have you thought about setting up Flattr for a simple way to donate?

**Comment by BennyKok** [comment]
it's a good suggestion, leme check it out.
@dkanada 
@gsantner 
What do you guys think?

**Comment by gsantner** [comment]
I have to admit that I never used Flattr. In case of FOSS projects, maybe LiberaPay makes mlre sense <https://liberapay.com>

**Comment by BennyKok** [comment]
I finally understand how Flattr was working..

**Comment by 12people** [comment]
@gsantner F-droid has support for Flattr buttons, but not for Liberapay, so there are arguments in favor of Flattr too.

**Comment by gsantner** [comment]
@12people It's not like this OR that, a project can always accept from multiple sources

**Comment by BennyKok** [comment]
yea, I have just sat up both of them, as I want to get funding on buying a laptop. so I can work on this everyday.

**Comment by gsantner** [comment]
The cool thing at liberapay seems to be that it supports teams: (example <https://liberapay.com/wallabag/> ) I just registered there too, but it seems quite nice

**Comment by BennyKok** [comment]
yea , have you created a team?

**Comment by gsantner** [comment]
nope

**Comment by 12people** [comment]
@BennyKok Where can I fund the Flattr link?

**Comment by BennyKok** [comment]
@12people flattr.com/profile/BennyKok will my profile link work?

**Comment by BennyKok** [comment]
@12people  I haven't verify the account yet, and actually I am only 17 year-old and Flattr don't let me choose the correct birth year. I am afraid there will be a problem to verify the account with my ID card. :(
