### ISSUE TITLE
About Gestures

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [OpenLauncherTeam/openlauncher#228]
I'm using swipe up, down, and double tap to launch apps. Sometimes the apps open immediately after swiping/tapping, sometimes they don't. Wish it were consistent. 

Please look into this issue.

Thanks.

PS: Please add 'Swipe Left', 'Swipe Right' gestures.

**Comment by BennyKok** [comment]
About the Swipe Left and Swipe Right gestures, there will be conflicts if user use multiple pages. I am not sure about whether to implement this or not. I will also look into the issue.

**Comment by iknownothingaboutcomputers** [comment]
@BennyKok Well, you could try making sideways-swiping work ONLY if the user is using one page (which I do); automatically disabled on multiple pages.

Thanks for all yor work.

**Comment by BennyKok** [comment]
@iknownothingaboutcomputers alright...

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
