### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [OpenLauncherTeam/openlauncher#229]
1. After rebooting the phone, the cursor doesn't show up automatically in the search field. Have to tap in the field once to make it appear. After that the cursor shows up automatically whenever search bar is opened. Please make the cursor appear automatically all the time. 

2. Would like the Search Bar to always show me the list of apps from the top instead of continuing from where I left off the last time.

3. It would be nice if the search bar could be placed at the bottom.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
