### ISSUE TITLE
cant change wallpaper on 0.5.4

### ISSUE THREAD

**Issue by samansalamat** [OpenLauncherTeam/openlauncher#230]
this build doesn't have wallpaper changer

**Comment by BennyKok** [comment]
it hasnt been implement yet, except for a set wallpaper shortcut. Maybe you can be more specific.

**Comment by samansalamat** [comment]
it can just change from minibar, could u add it from long press main page?

**Comment by samansalamat** [comment]
another problem, after set blur for wallpaper, it frees a while then change it, i cant change amount of blurring, also is it possible to make blur feature just for app drawer?

tnx for your support ;)

**Comment by BennyKok** [comment]
alright
