### ISSUE TITLE
Crash on app drawer icon rename

### ISSUE THREAD

**Issue by testman42** [OpenLauncherTeam/openlauncher#231]
If I long-press on app drawer icon, and then drag it on "edit" that appears on top of the screen, after confirming new label text, launcher crashes.

Here is the log:

> Build version: 0.5.3
> Build date: 1980-01-01 00:00:00
> Current date: 2017-09-08 09:41:41
> Device: Samsung SM-G920F 
> Stack trace: java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to com.benny.openlauncher.widget.AppItemView at com.benny.openlauncher.widget.DragOptionView$1$1.itemLabel(DragOptionView.java:99) at com.benny.openlauncher.viewutil.DialogHelper$1.onInput(DialogHelper.java:42) at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:367) at android.view.View.performClick(View.java:6199) at android.widget.TextView.performClick(TextView.java:11090) at android.view.View$PerformClick.run(View.java:23647) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6682) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Using Samsung Galaxy S6

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
