### ISSUE TITLE
searchbar independent of gapps

### ISSUE THREAD

**Issue by benneti** [OpenLauncherTeam/openlauncher#24]
It would be nice to have a searchbar which searches contactacts and apps and messages at the same time , without gaps.
The code of one of the simple launchers (like kiss) could maybe be reused.

Thanks for the app anyway, a fully customizable launcher was definitely missing in fdroid 👍

**Comment by BennyKok** [comment]
ok ok, by the way implement a search bar that search so many things takes time.

**Comment by benneti** [comment]
Nice, did not expect to see it tomorrow and I appreciate the work you do.

**Comment by BennyKok** [comment]
ha ha always be online when I am available, thanks

**Comment by gsantner** [comment]
I cannot see any dependency on gapps anymore, so I'm closing this
