### ISSUE TITLE
Settings option to set custom date/time format for OL datebar

### ISSUE THREAD

**Issue by milouse** [OpenLauncherTeam/openlauncher#246]
## General information

* OpenLauncher v0.5.5 from f-droid
* Android v6.0.1 (open OS from Fairphone)

I found no way to modify it in the `strings.xml` file, that's why I open this bug report.

## What is expected?

When I look at my phone desktop, the date should be correctly displayed in french.

For exemple

```
samedi 30 septembre
2017
```

## What does happen instead?

![](https://nuage.duchesse.chat/apps/gallery/s/u3NTnZSRIEQ19KR)

```
septembre 30
samedi, 2017
```

In french, it's totally wrong to have the number *after* the month name. It's just non-sense. Having the weekday name on the second line is very strange too for french people, because it's read after the first line and again, the weekday cannot normally be put after the month name.

If there is a problem of space, bellow are some valid way to display a date in french:

```
sam. 30 sept.
2017

sam. 30 septembre
2017

samedi 30 septembre
2017

30 septembre
2017
```

I think

```
sam. 30 septembre
2017
```

Is the best date representation here (combine shorter weekday, equivalent to second line display for other languages, but avoid to totally remove it).

For you information, `dimanche 31 septembre` is the longest date string you'll have in french. Other weekday name or month are either shorter or of same length.

## Steps to reproduce

* Use a french version of Android
* Install OpenLauncher
* Look at the desktop

**Comment by BennyKok** [comment]
Oh i see

**Comment by edern-appere** [comment]
I have the same complaint about date display in French. It would be great if it could be patched. 
Having the possibility to display the time would be great also.

**Comment by gsantner** [comment]
I wouldn't go the way here to make specific exceptions for specific languages...just the default what android suggests to be for the given locale, or a custom one via settings.

PR welcome.

**Comment by gsantner** [comment]
Done and available in next release.
