### ISSUE TITLE
Customizable textcolor: Date widget, folders, shortcuts

### ISSUE THREAD

**Issue by sebaki** [OpenLauncherTeam/openlauncher#247]
#### General information

* OpenLauncher v0.5.5 (f-droid)
* Android Version v7.1.2 (LineageOS)

#### Expected result
In order to be able to use dark as well as light wallpapers and to read the displayed date on the desktop, there should be either a switch from light to dark depending on the brightness of the background image or there should be a setting, which allows to set the color of the date manually.

Thanks you.

Ps. Also it would be great to show the time just beneath the date.

**Comment by EmmanuelMess** [comment]
Labels are also difficult to read:
<img height="350px" src="https://user-images.githubusercontent.com/10991116/33966127-38553270-e03d-11e7-9b71-f1bfb1bfae58.png"/>

**Comment by gsantner** [comment]
Done and available in next release.
