### ISSUE TITLE
lockable homescreen(s)

### ISSUE THREAD

**Issue by mase76** [OpenLauncherTeam/openlauncher#25]
Hi!
How about making the homescreen(s) lockable to prevent moving 
or deleting the icons and widgets by error?

**Comment by BennyKok** [comment]
ok ok

**Comment by gsantner** [comment]
Just as a refereeence, heres how e.g. Nova handles/resolvws that

* Lock settings option
* Temp disable unlock by confirmation (Overkill for OpenLauncher maybe)

![tmp_29878-screenshot_20170329-040752571730509](https://cloud.githubusercontent.com/assets/6735650/24435443/9f94e6bc-1435-11e7-9bbb-59ddaa817d27.png)

**Comment by dkanada** [comment]
@BennyKok added this feature in [293aa0c](https://github.com/OpenLauncherTeam/openlauncher/commit/293aa0c5e07f01534f5b5aab5a4f7aaec0d5ed4a) with a toggle in the desktop edit view.
