### ISSUE TITLE
after enabling rotation, layout has adjustment bug

### ISSUE THREAD

**Issue by samansalamat** [OpenLauncherTeam/openlauncher#255]
by enabling rotate screen, after rotating layout doesn't fit properly...
like app drawer icon, menu for desktop and etc.

**Comment by BennyKok** [comment]
So, actually, this is the thing that I haven't come up with a solution for a long time, this is why I forced the launcher to be in portrait mode for that long, most of the UI is being recalculated in runtime. And most of them are custom view, so it is a bit troublesome to make them works in landscape mode, it will be a total rewrite of the interface as we need to keep two different layouts(one for portrait and one for landscape), also, the launcher is undergoing constant changing over the interface. Moreover, I am a full-time student, you can expect a limited time for me to work on this project every week. And there are a lot of other issues coming up, yea, so, I wish I were Naruto, so I can fix them all at once.

**Comment by samansalamat** [comment]
tnx for your commnet ;)
