### ISSUE TITLE
Shortcut gets out of the folder

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#258]
0.5.5 F-Droid

#### Steps to reproduce
* open folder
* drag one shortcut
* drop on the "Information" area on the top

As the result shortcut disappears. Actually it appears again on the desktop after OL restart

**Comment by yaomtc** [comment]
This also occurs with the Edit button, not just Info.

**Comment by gsantner** [comment]
there is no info top action anymore in latest version - closing.

**Comment by ildar** [comment]
👍
