### ISSUE TITLE
[Enhencement] Widget for contacts/sms/calls

### ISSUE THREAD

**Issue by nailyk-fr** [OpenLauncherTeam/openlauncher#261]
#### General information

* **App version: 0.5.5 **
* **Android Version: OmniRom 7.1.2 **

#### Expected result
**What is expected?** 
It should be possible to add widgets to contact (shortcut to contact vcard)
It should be possible to add widgets to phone call (touch on the icon call the person)
It should be possible to add widgets to sms (touch the icon open sms app for the right person)

**What does happen instead?**
Option is not avaible into widget menu. 
Using menu on the contact, 'Add icon to desktop' don't produce icon on OpenLauncher (on Launcher3 instead?)

**Comment by Scumpeter** [comment]
I think this is related: The widgets for Google Maps ([this one](https://support.google.com/maps/answer/6291823?co=GENIE.Platform%3DAndroid&hl=en)) are also missing in the widget menu.

**Comment by nailyk-fr** [comment]
Wanna look at this bug and find this: https://github.com/LawnchairLauncher/Lawnchair/issues/559
Maps, Contacts/calls, are system apps (LOCAL_PRIVILEGED_MODULE := true).
Guess it is related to the issue. But am not able to replace the built-in 'Launcher3' of my rom as there is no Android.mk file for OpenLauncher to test this theory.

**Comment by gsantner** [comment]
Further discussion in #280
