### ISSUE TITLE
Add shortcut intent is not handled

### ISSUE THREAD

**Issue by 9001** [OpenLauncherTeam/openlauncher#262]
#### General information

* 0.5.5 / F-droid
* 8.0.0 Oreo

#### Expected result
When adding a contact shortcut in Telegram using the stock launcher, an activity to decide the size is shown before the icon is added.

With OL nothing happens at all

#### Steps to reproduce
* In Telegram: Open a contact, press the menu button and "Add shortcut"

**Comment by dkanada** [comment]
Do you know any other apps that can add a shortcut from within the app? I will try to tackle this as soon as I find an app on F-Droid I can download to reproduce the shortcut creation. Right now shortcuts should be handled but it isn't working properly.

**Comment by ildar** [comment]
Amaze (Manage local files) - https://f-droid.org/app/com.amaze.filemanager
Long tap on a folder, then three dots

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by dkanada** [comment]
@BennyKok shortcut intent is handled now but for some reason the launcher adds two shortcuts instead of one.

**Comment by gsantner** [comment]
Merging to #280
