### ISSUE TITLE
Creation/Autocreation of Shortcuts to contents of other apps (System settings, firefox, other apps..)

### ISSUE THREAD

**Issue by 9001** [OpenLauncherTeam/openlauncher#264]
#### General information

* 0.5.5 / F-droid
* 8.0.0 Oreo

#### Expected result
Using the stock launcher, under the widgets section you will find "settings shortcut". From there you can add shortcuts to various items in Android Settings

This widget type is unavailable in OL

**Comment by gsantner** [comment]
Closing this in favor of #280 which is on the same topic.
