### ISSUE TITLE
Swiping from the left kills widget

### ISSUE THREAD

**Issue by 9001** [OpenLauncherTeam/openlauncher#266]
#### General information

* 0.5.5 / F-droid
* 8.0.0 Oreo

#### Steps to reproduce
* Create a widget covering the left side of the screen
* Swipe in from the left 
* Widget disappears until launcher is restarted

issue has been observed with the termux shortcuts list and the "vanilla music 2x2 A" widget

**Comment by BennyKok** [comment]
ah.. so this was the problem, thanks, man, I finally know how to retrigger this problem, I used to think this problem happens randomly.
