### ISSUE TITLE
Wallpaper not centered on home desktop screen

### ISSUE THREAD

**Issue by PlqnctoN** [OpenLauncherTeam/openlauncher#268]
#### General information

* **App version: 0.5.5 from F-Droid**
* **Android Version: Android 7.1.2 (LineageOS 14.1)**

I don't know if it's a bug, an oversight or a feature.

#### Expected result
**What is expected?** 
I have 5 destkop screens, the third one is my home screen that I've set in the settings. I would expect that when I set a wallpaper it would be centered around my home screen. I could then scroll to the second and first screen and I could see the left part of the wallpaper, I could also scroll on the right to see the right of part of the wallpaper.
**What does happen instead?**
The wallpaper is always centered on the first desktop screen. You can't ever see the left part of the wallpaper and when you are on your set home screen the wallpaper is not centered.

Here are some screenshots:
1. First desktop screen / 2. Third desktop screen / 3. That's also my home screen

<img width="30%" height="30%" src="https://user-images.githubusercontent.com/3833277/31566389-a28a0556-b06a-11e7-9c34-82900422b95e.png"><img width="30%" height="30%" src="https://user-images.githubusercontent.com/3833277/31566396-a677295a-b06a-11e7-8c49-0d549df650ae.png"><img width="30%" height="30%" src="https://user-images.githubusercontent.com/3833277/31566399-a7f281d0-b06a-11e7-8293-5a8e3b3bb50b.png">

Here's the wallpaper in question:
<img width="30%" height="30%" src="https://user-images.githubusercontent.com/3833277/31566472-11542020-b06b-11e7-91ee-38daf2f605fd.png">

#### Steps to reproduce
* Install Open Launcher
* Create an odd number of desktop screens
* Set the middle one as the home screen
* Set a wallpaper in Android's settings
* The wallpaper is centered on the first desktop screen and not the home screen

**Comment by gsantner** [comment]
I cannot confirm this bug, I draw this very artistic image below and set it as background

![img_20180114_190612](https://user-images.githubusercontent.com/6735650/34919064-40260dd2-f95e-11e7-881f-87e98a4b0550.jpg)

with 3 pages I get this as background in page 2

![screenshot_20180114-190644](https://user-images.githubusercontent.com/6735650/34919066-4a866e34-f95e-11e7-8efd-9d63c32b86f2.png)
