### ISSUE TITLE
When item is dragged out of a folder directly onto "Edit", the item then disappears from the folder

### ISSUE THREAD

**Issue by yaomtc** [OpenLauncherTeam/openlauncher#270]
#### General information

* **App version:** 0.5.5
* **Android Version:** 7.1.1

#### Expected result
**What is expected?** Item should go back into folder where it was.

**What does happen instead?** Item disappears.

#### Steps to reproduce
1. Put a few items into a folder
2. Drag one out of the folder onto "Edit"
3. Tap "OK" or "Cancel" 
4. Look for that icon in the folder (it's not there)

**Comment by teal77** [comment]
Related to #258

**Comment by yaomtc** [comment]
Oh, that seems like the exact same thing, except using Info instead. Same bug though, oops. I'll just comment there.
