### ISSUE TITLE
Creation/Autocreation of Shortcuts to contents of other apps (System settings, firefox, other apps..)

### ISSUE THREAD

**Issue by mbenitob** [OpenLauncherTeam/openlauncher#280]
- Onboarder version: 0.5.5
- Android version: 6.0.1
- What is expected?
When using Firefox, if you are in a web page and select  "three dots->page->add shortcut to start screen" a nice new icon is expected to appear on the first empty desktop screen available slot. On tapping on that icon, Firefox should be opened with that very web page the function was called from.
- What does happen instead?
After selecting as above, the Firefox browser is minimized but no new icon appears. :(

**Comment by ildar** [comment]
Shortcut not yet supported, search

**Comment by gsantner** [comment]
This is the new main issue regarding "Shortcuts" support - be it firefox weblink, system settings, play store (new app installed) or alike.

**Comment by Serkan-devel** [comment]
The same thing now happens on chrome

**Comment by ElmarKnipp** [comment]
Any news?

**Comment by AndreiMarcuBis** [comment]
I'm willing to improve shortcut support on this launcher. Making something that works across all android version is going to be tricky. That would be great if someone working on this project could contact me to share knowledge about this topic and give me more details about the project's roadmap.

**Comment by amipjs** [comment]
Hi folks,
Just installed OpenLauncher (Nov'19, OLv0.70, droidv9) and encountered 
this issue.  I was trying to add web links from Firefox or FF Focus.

If it's too much trouble to support the "add shortcuts" intent, would it be
easier to add a "Share" functionality which would then appear as an icon
on the desktop?    

Thanks, 

amipjs

**Comment by gsantner** [comment]
@AndreiMarcuBis 
Please go for it :smile: !
Theres the launcher & launchericon classes for visuals. For app DB @dkanada can give input.

**Comment by sudomain** [comment]
+1 for shortcut support. I'm mentioning Termux here for any users that are wondering why they can add the Termux widget (2x2) to the OL home screen, but not individual Termux shortcuts (1x1), both of which are provided by the app Termux:Widget

**Comment by gsantner** [comment]
theres just someone that must do it left

**Comment by gsantner** [comment]
#522 #637
