### ISSUE TITLE
Enhancement: add "notification drawer" in gesture actions

### ISSUE THREAD

**Issue by fajabird** [OpenLauncherTeam/openlauncher#283]
I miss "notification drawer" in the list of gesture actions. Most launchers even set this by default.

**Comment by gsantner** [comment]
A action which opens up the full notification drawer of the OS? Never used/heard about this one in any of used launchers ;D

**Comment by TomJansen** [comment]
Nova launcher has this.

**Comment by gsantner** [comment]
ok, then feel free to send an PR ;)

I think this will be 1-3 lines for `if + execution` + 1 line for strings.xml

**Comment by dkanada** [comment]
That fix looks great, I will merge it now! I didn't realize we had a help wanted label, I can tag a few more issues if you want to take a look at them. If you use Matrix I can also find you on there to talk about whatever changes you want to make to the project. My current project is merging the search bar and app drawer into one element, right now they are mostly the same thing except one has a search bar.

**Comment by justanidea** [comment]
Hey, about this feature, it doesnt seems to work on some android versions (at minimum 5.1.1)
I think the accessibility permission is missing, so when we launch the activity, nothing happens
I love this feature and would be really helpful for the users that run the launcher in full screen

Anyways great app 👍

**Comment by dkanada** [comment]
@justanidea since your comment is technically a bug I'll close this issue again and you can open a separate issue if your phone still can't use the notification action.
