### ISSUE TITLE
 F-Droid 0.5.8(alpha) build failed on git checkout

### ISSUE THREAD

**Issue by offa** [OpenLauncherTeam/openlauncher#288]
The build for _0.5.8(alpha)_ failed on F-Droid ([Build Log](https://f-droid.org/wiki/page/com.benny.openlauncher/lastbuild_30), [Wiki](https://f-droid.org/wiki/page/com.benny.openlauncher#0.5.8.28alpha.29)):

> ### Build Log
> 
> Git checkout of 'v0.5.8(alpha)' failed
> **detail begin**
> 
> error: pathspec 'v0.5.8(alpha)' did not match any file(s) known to git.
> **detail end**

According to the log it's caused by a failed git checkout. Has the tag changed or is `(…)` invalid on git?

**Comment by offa** [comment]
I have checked this locally. To checkout the version mentioned above, i have to escape the parentheses:

```
git checkout v0.5.8\(alpha\)
```

Leaving them without the `\` caused an error.

Pushing another Tag with a fixed naming (eg. `v0.5.8-alpha`) should fix this.

**Comment by BennyKok** [comment]
thanks man, i think i better get rid of the alpha tag to avoid further problem....

**Comment by offa** [comment]
You can use a `-` instead of the `(…)`.

**Comment by BennyKok** [comment]
alright, should be ok now.
