### ISSUE TITLE
App menu remains on the screen, is that normal behaviour?

### ISSUE THREAD

**Issue by randseed** [OpenLauncherTeam/openlauncher#289]
If you open app menu, then open some app from it and return on the home screen by pressing the middle key, the app menu is still there although you would expect it to close and show you nice and clean home screen. Is that OK? Anyone else has this issue?

**Comment by FraMecca** [comment]
I have the same issue

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening on latest version
