### ISSUE TITLE
Remove droprown stays on top

### ISSUE THREAD

**Issue by gsantner** [OpenLauncherTeam/openlauncher#29]
Sometimes the remove/delete top dropdown stay there/doesnt hide after deselecting. Even  when clicking on some options. I'm on latest HEAD.

![tmp_29878-screenshot_20170329-034129416148782](https://cloud.githubusercontent.com/assets/6735650/24434861/6a680a12-1432-11e7-92ea-cf3caa5778b3.png)

**Comment by BennyKok** [comment]
Thanks for testing anyway, it is related to the animation and some runnable not running. I will fix it later
