### ISSUE TITLE
Uninstall tile out of screen on russian localization

### ISSUE THREAD

**Issue by randseed** [OpenLauncherTeam/openlauncher#290]
This happens if you drag app icon on the desktop.
I guess that should be fixed somehow.
<img src="https://user-images.githubusercontent.com/10977869/33339923-a9233b54-d48b-11e7-8bcd-8df99c028192.png" width="250" />

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening on latest version
