### ISSUE TITLE
[Bug] Some icons disappeared after restart

### ISSUE THREAD

**Issue by Kristinita** [OpenLauncherTeam/openlauncher#292]
### 1. Summary

After reboot smartphone, some icons disappeared from my workspace.

### 2. Hardware and software

+ ARK Benefit S401;
+ Android 5.1.1;
+ [**Vertex**](https://4pda.ru/forum/index.php?s=&showtopic=788444&view=findpost&p=56079362) ROM;
+ OpenLauncher 0.5.5 — latest F-Droid version at the issue moment.

### 3. Steps to reproduce

I have icons in my workspace:

![DuckDuckGo](https://i.imgur.com/hg9vHBg.png)

I restart my device → now I can't see some icons.

![No DuckDuckGo](https://i.imgur.com/AejsB5g.png)

### 4. Expected behavior

All workspace icons saving after restart.

### 5. Debugging

I can't see stack trace before and after reboot.

```bash
C:\System Volume Information>adb logcat -s com.benny.openlauncher
--------- beginning of system
--------- beginning of main
```

**If** I can add any debugging information, please, tell me, what can I do.

Thanks.

**Comment by ildar** [comment]
If the apps are installed to sdcard (not sure if it works that way on
Lollypop) then the issue is duplicate

**Comment by Kristinita** [comment]
@ildar , I search in issues of this repository by words `SD Card` and `MicroSD`, but I don't find similar issues.

If issue is duplicate, how I can solve this problem?

Thanks.

**Comment by ildar** [comment]
Sorry, I seem have confused with Lawnchair issue:
https://github.com/Deletescape-Media/Lawnchair/issues/734#issuecomment-331370227

**Comment by EmmanuelMess** [comment]
Can replicate. 
Motorola E Gen 2 4G
Android 6.0

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening on latest version
