### ISSUE TITLE
Remove RAM cleaner feature

### ISSUE THREAD

**Issue by EmmanuelMess** [OpenLauncherTeam/openlauncher#299]
Extra features require time to develop and debug. Why is there a RAM cleaner in a launcher app? Maybe it could be in another app or some sort of plugin.

**Comment by TomJansen** [comment]
A RAM cleaner is also not the way how Android should behave. Free memory is wasted memory.

**Comment by BennyKok** [comment]
I actually believe that as Android is improving itself rapidly, this function doesn't have a significant advantage to most of the newest model, however it is still useful for some very low end device and old Android version. Maybe in future, when we dont support device below 5.0, these features will be archived.

**Comment by EmmanuelMess** [comment]
Then we would have the same argument made.

**Comment by EmmanuelMess** [comment]
Reduce the app's RAM footprint. If someone wants a ram cleaner they would download a app that specific for that purpose.

**Comment by gsantner** [comment]
Closing this for now, minSdk lolipop is some time away

**Comment by EmmanuelMess** [comment]
> minSdk lolipop is some time away

And?
As I said:

> Then we would have the same argument made.

There is always 'older devices' no matter how much time we wait.

**Comment by TomJansen** [comment]
@gsantner I do not get why this is closed. Are the devs against removing the RAM cleaner?

**Comment by gsantner** [comment]
As far I know benny wants to keep it for now, and I follow that.
And what we currently dont need are open issues with no real todo. Where to start fixing stuff on 100 vs 30 issues.. ;)

**Comment by EmmanuelMess** [comment]
You cannot arbitrarily mark issues as closed, there exist tags, milestones and projects for a reason.

**Comment by gsantner** [comment]
Sure I can, as you can see :)

**Comment by D0ve** [comment]
I vote for the future 'ram cleaner', but I was confused when tapped it several times(((.
This future obviously needs new icon. Because existant icon looks like 'settings'(((.

**Comment by D0ve** [comment]
And I would like to suggest modernize this future even more,- became it fully functional 'memory manager'!
Even if it will need root rights.
