### ISSUE TITLE
Bad widget scaling/sizing

### ISSUE THREAD

**Issue by gsantner** [OpenLauncherTeam/openlauncher#30]
I tried with 3 types of clock widgets now, I cannot accomplish to add clock widget to a desktop using openlauncher. Scaling/sizing doesnt work. I'm on latest HEAD. The first image is OpenLauncher, the second e.g. Nova. Tried it also with Trebuchet, it's not a problem of the widget(s) itself.

Thanks for this really nice project!

![tmp_29878-screenshot_20170329-0341091995214708](https://cloud.githubusercontent.com/assets/6735650/24435032/45792014-1433-11e7-9244-feae1d2bbb2a.png)

![tmp_29878-screenshot_20170329-0354121059640947](https://cloud.githubusercontent.com/assets/6735650/24435052/676055f8-1433-11e7-9a4b-4e5f7e3a5dc0.png)

**Comment by BennyKok** [comment]
did the four resize arrow button popup when u long press the widget?

**Comment by BennyKok** [comment]
and drop it back

**Comment by gsantner** [comment]
yes they do appear,  but making the rectangle smaller just cuts off the widgets contents. but not does shrink/resize them.
Thats exactly what can be seen in screenshots

**Comment by BennyKok** [comment]
I need time to look at the issue, what widget are u using?

**Comment by gsantner** [comment]
The default clock widget included on my system, so AOSP clock - so pretty much the most common widget out there. Second one is cLock, included in LineageOS.

**Comment by gsantner** [comment]
The default clock widget included on my system, so AOSP clock - so pretty much the most common widget out there (most roms at least include a fork of this widget). Second one is cLock, included in LineageOS.

**Comment by dkanada** [comment]
similar issue in #33

**Comment by aabaker** [comment]
I saw this behaviour with an older release but I haven't seen it go wrong for a while - is it still an issue?

**Comment by gsantner** [comment]
yep.

![tmp_14007-screenshot_20170506-010241930396206](https://cloud.githubusercontent.com/assets/6735650/25767258/fa9f1f52-31f7-11e7-85e0-ee30805bd952.png)
