### ISSUE TITLE
Apps should be centered in folders

### ISSUE THREAD

**Issue by EmmanuelMess** [OpenLauncherTeam/openlauncher#300]
Here the 2 items should be lower down so that they are centered:
<img height="150px" src="https://user-images.githubusercontent.com/10991116/33965851-2dc6adee-e03c-11e7-8839-3993f9038845.png" />
And here 3 items, the bottom one should be moved to the right to be centered:
<img height="150px" src="https://user-images.githubusercontent.com/10991116/33965932-76c32c48-e03c-11e7-87d9-4dce588ea770.png" />

**Comment by ildar** [comment]
3 icons could be placed even better: triangularly, as in Lawnchair.

**Comment by gsantner** [comment]
I think thats more personal taste :)

every launcher does/handles this different. Feel free to send PR if needed.
