### ISSUE TITLE
Typo in first install welcome message

### ISSUE THREAD

**Issue by remi13131** [OpenLauncherTeam/openlauncher#301]
#### General information

* **App version:** Latest from FDroid
* **Android Version:** 7.0

#### Expected result
**What is expected?** 
 
I think the welcome message should be : 

"The Launcher **from** the community for the community."

**What does happen instead?**

"The Launcher **form** the community for the community."

#### Steps to reproduce

* Install the Launcher from FDroid.

* Launch it for the first time

**Comment by conrad-heimbold** [comment]
Error is in: 
/app/src/main/java/com/benny/openlauncher/activity/InitActivity.kt:35: 
``.description("Just swipe form the left edge.")``
and
/app/src/main/res/layout/intro_csutom_layout.xml:98:                
``android:text="The Launcher form the community for the community"``
I will create a pull request.
