### ISSUE TITLE
Search filter in app drawer

### ISSUE THREAD

**Issue by jaimesBooth** [OpenLauncherTeam/openlauncher#302]
A search bar at the top of the app drawer is useful to quickly isolate an app. Apps filter out of the drawer when the app name does not match the text as it is entered in the search bar. This feature is implemented in Trebuchet.

**Comment by BennyKok** [comment]
hey man, there's are a search bar in the desktop that can search all the apps already.

**Comment by jaimesBooth** [comment]
Thanks for your reply. The desktop search bar is great. How about an option to add it to the app drawer?

**Comment by gsantner** [comment]
I think the searchbar already does very well, other appeance locations can be done by community via PR.
