### ISSUE TITLE
[CRASH] on tapping "Other" in settings menu

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#307]
#### General information

* **App version:** Latest F-Droid ( 0.5.8(alpha) )
* **Android Version:**  4.2.2

#### Steps to reproduce
* Clean install
[adb.logcat.log](https://github.com/OpenLauncherTeam/openlauncher/files/1564544/adb.logcat.log)

**Comment by gsantner** [comment]
Cannot reproduce on current master - reopen after next installed update if still happening

**Comment by ildar** [comment]
пн, 15 янв. 2018 г., 1:00 Gregor Santner <notifications@github.com>:

> Cannot reproduce on current master - reopen after next installed update if
> still happening
>
Hm, releases aren't frequent this year

**Comment by gsantner** [comment]
Then start working on the project, stuff doesnt get itself done

**Comment by ildar** [comment]
New version landed

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ildar** [comment]
But the problem persists on JB (Android 4.2)
logcat attached

**Comment by ildar** [comment]
please reopen

**Comment by ildar** [comment]
Similar crash is now observed choosing "Behavior" in Settings.

Please reopen.

**Comment by ildar** [comment]
looks duping https://github.com/OpenLauncherTeam/openlauncher/issues/503
