### ISSUE TITLE
Unable to launch apps with Gestures

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [OpenLauncherTeam/openlauncher#311]
When I select 'Launch Apps' in Gestures, list of apps doesn't appear. This is the only option under 'Gestures' that's no working for me.

**Comment by PiwwowPants** [comment]
`DialogHelper.selectActionDialog` is not actually used when opening the action selection dialog, instead prompting up a different dialog. This uncalled method is what is calling `DialogHelper.selectAppDialog` which is what lets you select the app to open.
The fix seems to just be swapping the dialog that is apparently generated in `SettingsActivity` with the one that already exists in `DialogHelper`

**Comment by gsantner** [comment]
Works on current version - this is executed in my case and show up the apps-menu <https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/util/LauncherAction.java#L88>

**Comment by tp0** [comment]
This is not fixed for me. No app list shows up, upon then swiping up/down OpenLauncher instantly crashes.

Android: 7.1.2, LineageOS 14.1
OpenLauncher: 0.5.10 (33) (F-Droid)
