### ISSUE TITLE
Support different types of animations for showing app grid

### ISSUE THREAD

**Issue by gsantner** [OpenLauncherTeam/openlauncher#316]
#### General information

* **App version:** 68c534a94776bf3a8c00b3f02f7ac421d38f5e2
* **Android Version:** 7.0.1

#### Expected result
**What does happen?**
Currently only the "circular reveal" animation is supported.

**What is expected?** 
To have support of more animations when showing the app grid.

For myself the most important would be e.g. the `Zoom Animation`, you can see the animation below of e.g. Nova Launcher:

<https://raw.githubusercontent.com/gsantner/gh_tmp/master/video_2018-01-02_22-17-45.mp4>

Just as a comparision, this is available on Nova:
* Zoom
* Circle
* Circle wipe (this is our current one)
* Slide up
* Fade

**Comment by BennyKok** [comment]
Good one man....
