### ISSUE TITLE
Unable to compile project

### ISSUE THREAD

**Issue by bdevay** [OpenLauncherTeam/openlauncher#317]
#### General information

* **App version: 022a51b1aa5c5e8f7e5e5330d1e770c9c50955dc. Modified by Gregor Santner 2017. 03. 29. 23:27:58 Refactor project to use default android gradle project layout**
* **Android Version: x**

#### Expected result
**What is expected?** 
Compile project

**What does happen instead?**
Gradle error

Screenshot about the error:
<img width="30%" height="30%" src="https://user-images.githubusercontent.com/5401818/34522435-e489f2c8-f092-11e7-9564-108c0287bd02.jpg">`

Settings are correct:

<img width="30%" height="30%" src="https://user-images.githubusercontent.com/5401818/34522503-3615be56-f093-11e7-8592-f75c075b9374.jpg">

<img width="30%" height="30%" src="https://user-images.githubusercontent.com/5401818/34522504-3630a766-f093-11e7-98a2-c9bccf3d1600.jpg">

#### Steps to reproduce
* Use Android Studio to checkout the project
* Follow Studio's instructions (to install necessary packages)
* Gradle will start compile the project automatically and error raises at the end

**Comment by bdevay** [comment]
**I tried to run gradlew from command line and I got this error message:**

Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

D:\Users\bdevay\Documents\GitHub\openlauncher>gradlew

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by BennyKok** [comment]
have you try rebuilding, invalid cache restart. etc...

**Comment by bdevay** [comment]
Yes, I tried everything I found on internet with this error message. Clean project, rebuild, invalidate cache, restart studio, restart computer...

**Comment by BennyKok** [comment]
I am not sure why that's happening, I will look into it tmr.

**Comment by BennyKok** [comment]
I am having something like this `Error:CreateProcess error=2, The system cannot find the file specified` oh no

**Comment by bdevay** [comment]
Yes, same for me if I try to compile it again. So the error message differs for the first and second time compilation.

**Comment by BennyKok** [comment]
please temporary comment out this line in the gradle 

>         //buildConfigField "String", "GITHASH", "\"${getGitHash()}\""

**Comment by bdevay** [comment]
I commented out it now in app/build.gradle and gradle build finished successfully. Thank you for your help!
I don't close this ticket now because it' a workaround. Is it OK with you?

**Comment by BennyKok** [comment]
Sure man, I need to find out why that's not working too.

**Comment by gsantner** [comment]
Ping me too on such issues, I didnt notice this.

This may be because you dont have git exectueable in PATH. Thanks for noticing

**Comment by BennyKok** [comment]
Cool, we may want to add this to readme for instruction for setting up openlauncher.

**Comment by gsantner** [comment]
there should be nothing to setup beyond installing andtoid studio and sdk, just normal setup

**Comment by BennyKok** [comment]
right, I was wondering some people may not have git installed, but then I realize, we are using github...

**Comment by gsantner** [comment]
this git commit hash is just a gimmick

**Comment by BennyKok** [comment]
yea thats cool

**Comment by gsantner** [comment]
@bdevay Git commit hash detection is now failsafe and will not block building, should work now.

@BennyKok I updated the buildscript as a whole, removed some deprecated stuff and updated libraries inlcuding latest kotlin

**Comment by BennyKok** [comment]
Thanks dude
