### ISSUE TITLE
Tweak the folder creation behavior for better usability.

### ISSUE THREAD

**Issue by grrrrr** [OpenLauncherTeam/openlauncher#32]
Allow Grouping of Applications on desktop

Currently you can only have individual app icons on the desktop, it would be great if multiple icons could be grouped into "folders"

**Comment by gsantner** [comment]
I don't know on which version of OpenLauncher you are at, as not supplied, but my version (current HEAD) has folder support. Just drop one launcher icon onto another.

**Comment by grrrrr** [comment]
@gsantner OpenLauncher alpha2_patch2 (f-droid).  I had tried that already and it just results in the icon you try to drop on top of another moving next to it

**Comment by gsantner** [comment]
![screenshot_20170329-221527](https://cloud.githubusercontent.com/assets/6735650/24475835/82ed265e-14d1-11e7-83ba-c0a290b6da46.png)
![screenshot_20170329-221532](https://cloud.githubusercontent.com/assets/6735650/24475836/82f0e21c-14d1-11e7-9174-2f8b216589e7.png)

**Comment by grrrrr** [comment]
Look at that it works.   Though not by dropping icon on top of icon.  I had to "flick" one icon into the other.  A bit unintuitive but it does the job

**Comment by dkanada** [comment]
I actually think we should keep this open, the folder creation is a bit finicky. This could be probably be improved by enlarging the area that triggers a folder creation.

**Comment by aabaker** [comment]
Part of the complexity here is in peekItemAndSwap(), if you hold the app you are moving over the app you want to make a folder with for >600 ms then the app that was there is moved. If you drop it after <600 ms then it creates a folder. For comparison other launchers seem to only move items out of the way if the item being moved is on the edge of the target, if it is central it creates a folder.

In either case as far as I can tell there is no way to rename the folder that is created.

**Comment by conrad-heimbold** [comment]
@grrrrr I prefer to use AppsOrganizer , that app offers much more flexibility and usability for creating groups/folders/categories of app icons on your home screen. 
- Original (really old) version: [F-Droid](https://f-droid.org/app/com.google.code.appsorganizer), [Source on Google Code](https://code.google.com/archive/p/appsorganizer/)
- Forked (newer) version, not yet on F-Droid or GPlay:  [Github](https://www.github.com/willemw12/Apps2Org/releases)

Having all such functionality in the home launcher is overkill, IMHO.
