### ISSUE TITLE
Launcher crashing when tapping menu 

### ISSUE THREAD

**Issue by p00rt** [OpenLauncherTeam/openlauncher#325]
#### General information

* **App version:** 0.5.8(Alpha)
* **Android Version:** LineageOS 14.1 (Android 7.1.2)
* **Device:** Moto E2 LTE 2015 (surnia)

#### Expected result
Installed apps should show up

**What does happen instead?**
launcher crashes

adb logcat -s com.benny.openlauncher says nothing, but:
adb logcat \*:D gives some info:
01-19 15:43:28.579   617   617 E Hey     : ACTION_DOWN  
01-19 15:43:28.713   617   617 E Hey     : ACTION_UP  
01-19 15:43:28.713   617   617 E Hey     : 289  36  
01-19 15:43:28.854   617   617 D AndroidRuntime: Shutting down VM
01-19 15:43:28.856   617   617 E AndroidRuntime: FATAL EXCEPTION: main
01-19 15:43:28.856   617   617 E AndroidRuntime: Process: com.benny.openlauncher, PID: 617
01-19 15:43:28.856   617   617 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=12; regionStart=0; regionLength=14
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at java.lang.String.substring(String.java:1931)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at com.benny.openlauncher.core.widget.AppItemView.onDraw(AppItemView.java:196)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:17189)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:16955)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4607)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:17192)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4013)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:16955)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:16955)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:17192)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:16955)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at io.codetail.widget.RevealFrameLayout.drawChild(RevealFrameLayout.java:32)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:17192)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16171)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16134)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16134)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.draw(View.java:16955)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1367)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16166)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16134)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16134)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16134)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16134)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-19 15:43:28.856   617   617 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-19 15:43:28.864 17962 25415 W ActivityManager:   Force finishing activity com.benny.openlauncher/.activity.Home
01-19 15:43:28.868 17962   645 W DropBoxManagerService: Dropping: data_app_crash (10 > 0 bytes)
01-19 15:43:28.879 17962 25415 I ActivityManager: Clearing package preferred activities from com.benny.openlauncher
01-19 15:43:28.888   617   617 I Process : Sending signal. PID: 617 SIG: 9
01-19 15:43:28.946 17962 18269 I WindowManager: WIN DEATH: Window{58dc10f u0 com.benny.openlauncher/com.benny.openlauncher.activity.Home}
01-19 15:43:28.946 17962 27500 D GraphicsStats: Buffer count: 4
01-19 15:43:28.947 17962 19554 I ActivityManager: Process com.benny.openlauncher (pid 617) has died
01-19 15:43:28.947 17962 19554 D ActivityManager: cleanUpApplicationRecord -- 617

#### Steps to reproduce
* launch openlauncher
* tap app drawer button

**Comment by gsantner** [comment]
> 01-19 15:43:28.856 617 617 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=12; regionStart=0; regionLength=14
> 01-19 15:43:28.856 617 617 E AndroidRuntime: 	at java.lang.String.substring(String.java:1931)
> 01-19 15:43:28.856 617 617 E AndroidRuntime: 	at com.benny.openlauncher.core.widget.AppItemView.onDraw(AppItemView.java:196)
> 01-19 15:43:28.856 617 617 E AndroidRuntime: 	at android.view.View.draw(View.java:17189)
> 01-19 15:43:28.856 617 617 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:16171)

**Comment by ildar** [comment]
If that helps I see the similar crash after new app installed but have a little different stack.
[adb.logcat.log](https://github.com/OpenLauncherTeam/openlauncher/files/1655155/adb.logcat.log)

**Comment by ligi** [comment]
also just got this: with com.benny.openlauncher_24.apk         

```
E/AndroidRuntime( 1495): java.lang.StringIndexOutOfBoundsException: length=20; regionStart=0; regionLength=22
E/AndroidRuntime( 1495): 	at java.lang.String.startEndAndLength(String.java:583)
E/AndroidRuntime( 1495): 	at java.lang.String.substring(String.java:1464)
E/AndroidRuntime( 1495): 	at com.benny.openlauncher.core.widget.AppItemView.onDraw(AppItemView.java:196)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13729)
E/AndroidRuntime( 1495): 	at android.view.View.buildDrawingCache(View.java:12983)
E/AndroidRuntime( 1495): 	at android.view.View.getDrawingCache(View.java:12765)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13419)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2931)
E/AndroidRuntime( 1495): 	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4607)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2800)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13732)
E/AndroidRuntime( 1495): 	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4013)
E/AndroidRuntime( 1495): 	at android.view.View.buildDrawingCache(View.java:12983)
E/AndroidRuntime( 1495): 	at android.view.View.getDrawingCache(View.java:12765)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13419)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2931)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2800)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13611)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2931)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2800)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13732)
E/AndroidRuntime( 1495): 	at android.widget.FrameLayout.draw(FrameLayout.java:467)
E/AndroidRuntime( 1495): 	at android.view.View.buildDrawingCache(View.java:12983)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12646)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13445)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2931)
E/AndroidRuntime( 1495): 	at io.codetail.widget.RevealFrameLayout.drawChild(RevealFrameLayout.java:32)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2800)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13732)
E/AndroidRuntime( 1495): 	at android.widget.FrameLayout.draw(FrameLayout.java:467)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12667)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13445)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2931)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2800)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12665)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12605)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.View.draw(View.java:13445)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2931)
E/AndroidRuntime( 1495): 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1367)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2800)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12665)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12605)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12605)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12605)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2913)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12605)
E/AndroidRuntime( 1495): 	at android.view.View.getDisplayList(View.java:12711)
E/AndroidRuntime( 1495): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1219)
E/AndroidRuntime( 1495): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2273)
E/AndroidRuntime( 1495): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2141)
E/AndroidRuntime( 1495): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1950)
E/AndroidRuntime( 1495): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1049)
E/AndroidRuntime( 1495): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4511)
E/AndroidRuntime( 1495): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/AndroidRuntime( 1495): 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/AndroidRuntime( 1495): 	at android.view.Choreograp
W/ActivityManager(  371):   Force finishing activity com.benny.openlauncher/.activity.Home

```

**Comment by just-Nob** [comment]
I run into the same issue: Starting the drawer crashes the launcher. It came up a few days ago, I guess after installing some apps (maybe incompatibility problems?), because it worked before. I have to check this.
Anyway, how to get those adb logs?

**Comment by just-Nob** [comment]
Apps can still be started without a crash via OpenLauncher's search feature.
That's the way I'm currently using it.

**Comment by dkanada** [comment]
@just-Nob thanks for the update on this one, I was worried this was still affecting users. By the way, adding a new comment is sometimes better than an edit, because an edit will not notify me of any new information in a conversation.
