### ISSUE TITLE
Search bar / date on the desktop

### ISSUE THREAD

**Issue by grrrrr** [OpenLauncherTeam/openlauncher#33]
Android 7.1.1 (LineageOS)
OpenLauncher alpha2_patch2 (f-droid)

What is happening:

On the desktop I have the date in the upper left corner of all desktops and does nothing and no discernible search bar.   If I go to settings and turn off `Search bar`,  The date disappears.    Also one widget, for SeriesGuide,  grows from taking 3 rows when `search bar` is enabled to 4 when it is disabled.  The widget also loses all the size adjustment options when you long press on it.

**Comment by BennyKok** [comment]
Now we have the new search bar.
