### ISSUE TITLE
Screen Management (Bug?): HomeScreen "shifts" when adding new screens to the left

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#334]
When adding a new screen on the left side by dragging one ore more app icons to the left, the homescreen "shifts" one position to the left as well.

An Example:
1. Imagine you're having three screens: One on the left (screen No.1), one in the middle (screen No.2), and one on the right (screen No.3). The centered screen (screen No.2) is set to be the homescreen, i.e. the screen to display when triggering the device's home button.
2. Now you're going to add a new screen at the left side by dragging any app icon (shortcut) or widget from screen No.1 to the left, i.e. a new screen to the left is added; let's name this screen as "screen No.0".
3. After the new screen is added to the left, the current homescreen isn't screen No.2 anymore, but screen No.1!

I guess that this misbehavior is based an a simple bug:
After adding a new screen to the left, in fact the new screen turns into screen No.1, (formerly) screen No.1 turns into screen No.2, screen No.2 turns in screen No.3, and so on, but the variable holding the homescreen isn't adapted, i.e. (referring to the example above) the homescreen still stays on screen No.2, but have to be corrected to screen No.3! ;)

Anyway, the user's expected result is that the homescreen stays at the screen with a special content, independent of adding some screens to the left or to the right.

#### General information

* **App version:** 0.58(alpha)
* **Android Version:** 7.1.1 Nougat

**Comment by tp0** [comment]
This has occurred for me too.

App version: Version 0.5.10 (33) from F-Droid
Android Version: 7.1.2 (LineageOS 14.1)

**Comment by Ptitg** [comment]
Fixed by #679
