### ISSUE TITLE
Problems when trying to set widgets' size (improvement / feature request?)

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#338]
I find it really hard to change a widget's size:
1. The handles are hard to strike - it needs many attempts before I "get them"! Anyway, my touch screens usually reacts precise, I tested it out with a test tool.
2. The duration before the handles disappear is somewhat short of time.

I wished to have bigger handles for resizing the widget. Optically, it's ok if they stay as they are, but the area to be recognized as a touch should be a little bigger.
Maybe it would also be nice to have a longer time before the handles disappear - maybe configurable in the settings?

#### General information

* **App version:** 0.58(alpha)
* **Android Version:** 7.11 Nougat
* **Device:** BQ Aquaris X Pro

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
