### ISSUE TITLE
Screen Management: Deleted  (removed) screens 'in the middle' re-appear after restart of OpenLauncher (bug)

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#342]
#### General information

* **App version:** 0.5.8(alpha)
* **Android Version:** 7.1.1 Nougat

#### Expected result
**What is expected?** 
A removed screen stays removed and don't re-appears after a restart of OpenLauncher.

**What does happen instead?**
If the deleted/removed screen is "in the middle" (i.e. between other screens), it re-appears after OpenLauncher was restarted. It doesn't matter if it's only one screen or multiple screens being removed. Anyway, its/their content is lost and don't re-apper, for sure!

#### Steps to reproduce
* Go to "Settings --> Debug --> Reset Database" and execute.
* Place minimum two widgets on the homescreen.
* Create two new screens to the right by dragging minimum one widget to the right, so far that you have three screens in total.
* Set the leftmost (original) screen as the home screen.
* Remove the second screen in the middle. It doesn't matter if the is any content like widgets or app shortcuts.
* Restart OpenLauncher ("Settings --> Debug --> Restart").
* The removed screen is like the T-800: He's back (but always empty, i.e. without any content like widgets or app shortcuts).

Only deleted screens between other screens re-appear!
If you remove a screen "at the end", it won't re-appear after a restart!

**Comment by Benjilein** [comment]
Got the same issu with the rightmost screen. If you look into the backfile, there ist still an empty screen, which gets inizialized, when reloading the app.
