### ISSUE TITLE
All Widget's Handles being displayed after OpenLauncher's (Re-)Start or after installing a new app (bug?)

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#343]
#### General information

* **App version:** 0.5.8(alpha)
* **Android Version:** 7.1.1 Nougat

#### Expected result
**What is expected?** 
No widget handles after OpenLauncher starts or after an installation of a new app.

**What does happen instead?**
All widgets get their resizing handles for one or two second after starting OpenLauncher or after installing a new app.

#### Steps to reproduce
* (Re-)Start OpenLauncher or install a new app.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
