### ISSUE TITLE
Issues with Progressive Web Apps on the homescreen 

### ISSUE THREAD

**Issue by Serkan-devel** [OpenLauncherTeam/openlauncher#346]
Firefox add to homescreen doesn't work

#### General information

* **App version:0.5.8 (alpha)**
* **Android Version:5.0.1 (also applies to 6.0.2)**

There is a recent feature on browsers, where one can add certain webpages, like pokedex.org  to the home screen and open it, the page then displays without a url bar and works offline.

https://developers.google.com/web/progressive-web-apps/

#### Expected result

**What is expected?** 
Just like on chrome, a PWA added to the home screen opens the PWA.
**What does happen instead?**
On Firefox or Fennec  (the F-Droid build of FF), the browser Icon gets added instead of the favicon of the page and when tapping on it, the Firefox/Fennec browser opens

![screenshot_2018-03-19-16-15-07](https://user-images.githubusercontent.com/16866642/37605009-976f91d8-2b92-11e8-8b57-7a00a30427c5.png)

When switching to the stock TouchWiz UI, I see the correct PWAs 
![screenshot_2018-03-19-16-16-57](https://user-images.githubusercontent.com/16866642/37605168-ee612ee8-2b92-11e8-8478-0a37f3b0ccd6.png)

and when opening them it opens like on chrome the PWA without URL bar but running on top of FF.

![screenshot_2018-03-19-16-17-39](https://user-images.githubusercontent.com/16866642/37605239-0fa9d438-2b93-11e8-80c0-71aaf2e6af77.png)

![screenshot_2018-03-19-16-17-53](https://user-images.githubusercontent.com/16866642/37605272-1df4bd5a-2b93-11e8-9d0f-71e9a8ed5f4e.png)

 
Logcat: `adb logcat -s com.benny.openlauncher`
--> /unable to do so/

#### Steps to reproduce
* Open pokedex.org
* tap in the add to homescreen option at the url-bar
* tap the new icon on the home screen

![screenshot_2018-03-19-16-16-21](https://user-images.githubusercontent.com/16866642/37605615-dd242184-2b93-11e8-8cf6-023e4b58e67c.png)

**Comment by Serkan-devel** [comment]
Oh and on 6.0.2 the same thing happens but it places the icon twice on the home screen. Logcat might follow

**Comment by Serkan-devel** [comment]
The problem still persist

**Comment by gsantner** [comment]
it has never said to be fixed. 

Closing as duplicate again.

**Comment by Serkan-devel** [comment]
Where has it been first mentioned?

**Comment by gsantner** [comment]
Progressive web apps are just shortcuts, which a big ticket is open for
