### ISSUE TITLE
App drawer glitches when gesture is set

### ISSUE THREAD

**Issue by Avizini** [OpenLauncherTeam/openlauncher#349]
#### General information

* **App version:** 0.5.10
* **Android Version:** 4.4

#### Expected result
**What is expected?** 
It should not glich.

**What does happen instead?**
It glitches.

[Screenshot - OpenLauncher](https://lut.im/C8qB0gts0I/nDktJ0F32Mrylh5F.png)

<img width="30%" height="30%" src="https://lut.im/C8qB0gts0I/nDktJ0F32Mrylh5F.png">

#### Steps to reproduce
*Install OpenLauncher (of course)
*Set gestures
*Set swipe up and swipe down gestures to open the App Drawer
*Swipe up... It works!

* Swipe Down :( doesn't work, instead that thing happens

(Other settings were not changed)

**Comment by dkanada** [comment]
This should be fixed in the next update you see on F-Droid, I just made a lot of changes to the gestures. If you still have issues with it after the update please reopen this issue!
