### ISSUE TITLE
Two App Shortcuts after installation on Homescreen(s) (Bug)

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#355]
#### General information

* **App version:** 0.5.10 (from F-Droid)
* **Android Version:** 7.1.1 Nougat

#### Expected result
**What is expected?** 
Maximum one shortcut / app link for a new installed app should be placed on the homescreen (s). If screens are locked, I'd even expect no single shortcut to be placed on any of the screens.

**What does happen instead?**
Two shortcuts / app links are placed on the screens, independent of OpenLauncher's "lock screen(s)" status.

#### Steps to reproduce
* Just install any app.

**Comment by tp0** [comment]
Every app based on my quick and random testing.

No icons show up if "Add icon to home screen" in Google Play app is disabled. Two icons if enabled.

Version: Version 0.5.10 (33)

**Comment by samansalamat** [comment]
is there anyway to fix it?
like refreshing the application list in app drawer after installing new app from playstore

**Comment by Serkan-devel** [comment]
I've extensibility documented in this issue in case of PWAs https://github.com/OpenLauncherTeam/openlauncher/issues/346 , but it has been closed as duplicate,  even though I've written it earlier.

**Comment by gsantner** [comment]
please add that here. It not makes anything easier or better if infos are distributed across 20 issues :). Thanks.

Hence this issue exists that this doesnt happen.

**Comment by Serkan-devel** [comment]
Oh, wrong thread, forget what I wrote, sorry

**Comment by gsantner** [comment]
Don't see any automatic homescreen launcher placement anymore, so closing.
