### ISSUE TITLE
Issue release only if CHANGELOG.md is updated

### ISSUE THREAD

**Issue by Drugoy** [OpenLauncherTeam/openlauncher#358]
I do not blindly update my programs, I prefer to read changelogs first to decide whether I'd like to update or not.
Current CHANGELOG.md contains very outdated info, please, update it.

**Comment by Drugoy** [comment]
Yeah, to hell this software then.

**Comment by Drugoy** [comment]
@dkanada @BennyKok, do you approve gsantner's action?

**Comment by gsantner** [comment]
send a merge request to update it.

**Comment by Drugoy** [comment]
@gsantner how would I know what changes do commits bring? you suggest me to decipher each commit figuring out what it does?
You are a joke.

**Comment by gsantner** [comment]
Stay polite. Topic locked.

**Comment by BennyKok** [comment]
..Take it easy dude @Drugoy , @gsantner is putting his own time into this, I appreciate it very much as I myself have been away for quite some times, and he and @dkanada have been maintaining this until now. Which the blame is on me cause I am not actively contributing anymore and left the launcher in this current state.
