### ISSUE TITLE
Bluetooth causes app to crash

### ISSUE THREAD

**Issue by Benjilein** [OpenLauncherTeam/openlauncher#360]
Everytime a bluetooth device connects or disconnects automatically (e.g. a bluetooth keyboard or a bluetooth headset), OpenLauchner crashes and needs to be reloaded. 

-----------------------------

#### General information

* **App version:** 0.5.5
* **Android Version:** 7.1.1

#### Expected result
**What is expected?** 
Bluetooth connections have no influence on the launcher

**What does happen instead?**
OpenLauchner crashes

#### Steps to reproduce
* Pair a device with the phone (e.g. a bluetooth keyboard)
* Switch off the keyboard
* App crashes (reload it)
* Switch on the keyboard
* As soon as Android detects the keyboard, the app crashes again
* Can also be reproduced with headsets etc. (All devices which can be switched on and off)

**Comment by dkanada** [comment]
I don't have any bluetooth devices, could you attach a crash log from your device when this happens again? I am trying to get to zero crashes in the F-Droid build.

**Comment by gsantner** [comment]
cannot reproduce
