### ISSUE TITLE
When editing desktop page clicking the page opens up the app drawer

### ISSUE THREAD

**Issue by kodeblacc** [OpenLauncherTeam/openlauncher#368]
#### Expected behavior
I expected that if I was editing the desktop page on open launcher, when I press the page I'm editing it'll go back to the desktop page.
#### Actual behavior
When I press anywhere on the edit page, it opens the app drawer.
PS: This is not a fixed response as sometimes the app behaves normally and sometimes the said bug is reproduced( clicking the page opens up the app drawer)

#### How to reproduce
- download open launcher from fdroid
- launch the app and allow all permissions
- press and hold the desktop screen for more options
- delete the page to make it empty(could delete all pages)
- Click and hold the page, press anywhere on the screen and the app drawer opens

<hr>

* Device: Infinix note 4
* Operating system: Android 8.0
* Software version: 0.5.10

#### Recording Of The Bug
https://vimeo.com/261903709
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/when-editing-desktop-page-clicking-the-page-opens-up-the-app-drawer">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dkanada** [comment]
Are you still having this issue? I am willing to bet that you currently use double tap to open the app drawer.
