### ISSUE TITLE
Request: Iphone like desktop & app drawer

### ISSUE THREAD

**Issue by Shuliande** [OpenLauncherTeam/openlauncher#369]
What about an option to disable app drawer/unified it with desktop?

**Comment by BennyKok** [comment]
Ha ha, thx for the suggestion, actually, we have done that before, however, it is removed from one of the previous versions because it just takes us more time to fix bugs related to that.

**Comment by dkanada** [comment]
Yeah, as stated above, we don't plan on adding that feature back in. It was a lot of work to maintain and this launcher is focusing on the app drawer setup.
