### ISSUE TITLE
Screens added to left of homescreen vanish after launcher restart

### ISSUE THREAD

**Issue by tp0** [OpenLauncherTeam/openlauncher#370]
#### Repro:

1. Have a setup where the current homescreen is the left-most screen (screen 1 = homescreen)
2. Drag one or more shortcuts/icons to the left to create a new screen (screen 1, screen 2 = homescreen)
3. Restart OpenLauncher
4. Result: The left-most screen (screen 1) is gone, and usually the icons that used to be there show up on the homescreen (screen 2). Depending on the arragement of the icons, they can overlap (graphical glitch) with existing icons.

Setting the newly created left-most screen as the new homescreen does not make a difference. Neither does locking the setup.

#### General information

* **App version:** Version 0.5.10 (33) from F-Droid
* **Android Version:** 7.1.2 (LineageOS 14.1)

**Comment by gsantner** [comment]
that may have todo with array index, but unsure about that part of logic. @BennyKok  knows better or?

**Comment by dkanada** [comment]
When a new page is created the desktop renumbers the pages immediately, so when an item is moved to a new page on the left it is saved to the wrong index. I couldn't think of a decent way to fix this without coding in a special case. One possible solution would be renumbering all existing items when a new page is created, but that is not ideal.

**Comment by BennyKok** [comment]
I don’t remember, wanna do a rewrite

**Comment by gsantner** [comment]
so i can stop working on OL an fixing things? 😅

**Comment by BennyKok** [comment]
I mean rewrite part of it😂😂

**Comment by gsantner** [comment]
xd. Maybe we should make sure our communication channels work and we are all in to know what todo. Dont care what but it should work to reach people in group chat^^

**Comment by BennyKok** [comment]
Btw, i dont have xmpp now, cuz i am using iphone as my daily driver 😪, as dkanada still dont have riot, will u guys be interested in using slack?

**Comment by BennyKok** [comment]
What dev? Just a suggestion.

**Comment by gsantner** [comment]
I mean why develop android launcher when you use mainly an iOS device 😀

**Comment by gsantner** [comment]
agreeing. what do you think about kotlin vs java? @dkanada  @BennyKok 

I think not much contributors know kotlin well yet, that may change but thats what I feel like and may be the reason that there are no code contribs from community

**Comment by dkanada** [comment]
I personally have no experience with Kotlin yet, although I do want to learn at some point. I am not sure we would get many code contributions regardless though, this is a pretty small project compared to some of the other launchers.

**Comment by gsantner** [comment]
If I'm having enough time to finish and get thumbs up from you two I would do merge-together-again now, with auto-format etc and basic fixes as reported by lint

**Comment by BennyKok** [comment]
I agree doing that tho :), so java :)

**Comment by gsantner** [comment]
@dkanada  @BennyKok 

As we see in the issue above, exactly as thought, yes Kotlin IS a problem for some potential contributors: https://github.com/OpenLauncherTeam/openlauncher/issues/376

**Comment by dkanada** [comment]
@gsantner were you working on merging the core back in or can I get that done today or tomorrow?

**Comment by gsantner** [comment]
Didn't get to it because had release day on Markor and Stringlate yesterday, with 12h+ work^^.

But yep, I'm gonna do it and will write here when I'm done, but please let me start because I noticed several stuff which needs to be fixed also and goes easy in this back-factor way

**Comment by BennyKok** [comment]
yea, kotlin did have some impact on the existing java code base

**Comment by gsantner** [comment]
Note though, I like kotlin and it's features. But the code is basically java converted, and as one would write java code. And the additional thing as above said is, more people know plain java including the one who just wanted to started contributing yesterday.

If we would really go kotlin, we should have decided to dump the old code and  re-implement, but we didn't.

**Comment by gsantner** [comment]
I finished most java-back-migration, core merging and removing+combining interfaces.

Can you guys do the rest? Please exclude SettingsActivity,AboutActivity and the Preference stuff. Gonna fully replace that anyway. Everything else please do.

**Comment by BennyKok** [comment]
@sure, i will do the testing tonight

**Comment by gsantner** [comment]
Should be all fine as tested on mine. But would be fine if you could do the left java-back conversation said above :D.

I just renamed to java file and reworked line by line.

**Comment by BennyKok** [comment]
Have not try reverting before, tho

**Comment by gsantner** [comment]
its not reverting git, its converting code by hand the other way :D

**Comment by gsantner** [comment]
@BennyKok  @dkanada 
I have completely reworked everything, including but not limited to
* Complete merge of core and app
* Complete removal of kotlin and all jetbrains stuff
* Complete rework of about
* Complete rework of settings
* Complete rework of pretty much everything else
* Resources, strings updates
* ...and much more
* see <https://github.com/OpenLauncherTeam/openlauncher/compare/v0.5.12...master> -  12,620 additions and 11,422 deletions, 65 Commits

I have done really much this week and pretty much did most stuff alone here for months. Now it's your turn again to make it better. Hope I didn't do this to keep working alone on it, as in both contributor and team level :smiley:.

![grafik](https://user-images.githubusercontent.com/6735650/39100805-ffe4838c-468f-11e8-95c0-a112bfc88078.png)

**Comment by gsantner** [comment]
<https://github.com/gsantner/opoc/blob/master/shell/android-check-preference-keys-dupplication.sh> can be used for pref checking
