### ISSUE TITLE
adding browser bookmarks broken

### ISSUE THREAD

**Issue by andyrtr** [OpenLauncherTeam/openlauncher#371]
I'm using the current OpenLauncher 0.5.10 from F-droid store together with Fennec browser. I can't add Fennec bookmarks and add them to the launcher as shortcuts like I can with other launchers. Usually after adding the bookmark to Fennec there's an option dialog to place them to the launcher as shortcuts. When hitting this the browser badly creates two shortcuts to the OpenLauncher desk but none of them allows to open that url. Also both don't show the webside icon but the Fennec one. I guess this is some bug in OpenLauncher or maybe a missing support feature I'd like to see.

**Comment by gsantner** [comment]
Duplicate, yep

**Comment by Serkan-devel** [comment]
Same here, but I can't find the issue that originally stated it
