### ISSUE TITLE
Ability to modify tapping the clock behavior

### ISSUE THREAD

**Issue by ybotspawn** [OpenLauncherTeam/openlauncher#376]
I love the launcher, I plan to start attempting to help with some of the issues mentioned below.  One of the things I noticed was that tapping on the clock pulls down a calendar.  It would be nice if the launcher allows for modification of this activity to open the calendar, clock, or any other type of user defined activity.

**Comment by gsantner** [comment]
good idea. we could e.g. use here the same list as available e.g. for "swipe down gesture"

**Comment by ybotspawn** [comment]
Sounds good, I'll give you a hand.  I'll grab a couple issues and start working them.  Thanks!

**Comment by ybotspawn** [comment]
Thanks again, figured out where the onclickListener for the clock was.  I'm working on implementing another gesture to manage the behavior that is expected when tapping on the clock.  Kotlins completely new to me, so it might take me a little bit.

**Comment by gsantner** [comment]
We will do some big changes today or tomorrow which will change many classes. I'm suggesting to wait 1-2 days before starting.

See discussion at <https://github.com/OpenLauncherTeam/openlauncher/issues/370#issuecomment-381072984>

**Comment by ybotspawn** [comment]
Sounds good
