### ISSUE TITLE
Minor Problem within Gestures.

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [OpenLauncherTeam/openlauncher#377]
If I have to change the app I had set to launch with a gesture, then I have to select a different action first because tapping on 'Launch App' doesn't do anything if the gesture was already set to do that before.

-----------------------------

* **App version:** 0.5.12
* **System:** 5.1

**Comment by dkanada** [comment]
Just fixed this issue, thanks for reporting! It will be in the next update on F-Droid.
