### ISSUE TITLE
app drawer icon disappears

### ISSUE THREAD

**Issue by samansalamat** [OpenLauncherTeam/openlauncher#378]
after clearing database to make a reset factory, app drawer icon will disappear.
ver 0.5.4

**Comment by dkanada** [comment]
Can be fixed by setting first run to **true** when the database is reset. This is a good suggestion, will be fixed for the next release.

**Comment by samansalamat** [comment]
could help me which part of code should be changed?

**Comment by dkanada** [comment]
I just fixed this issue in the latest update, you should see the changes on F-Droid in a few days or so.
