### ISSUE TITLE
Feature request: Choose first day of the week

### ISSUE THREAD

**Issue by source124** [OpenLauncherTeam/openlauncher#379]
#### General information

* **App version: 0.5.12** 
* **System: Android 8.0** 

#### Description

Hi,

Can we please be able to set the first day of the week (as any day), for use in the Desktop Calendar?

Thank you.

**Comment by ildar** [comment]
... or it may be determined automatically from system locale

**Comment by gsantner** [comment]
Will get System locale only if changed.

**Comment by source124** [comment]
> ... or it may be determined automatically from system locale

I keep my phone in English, but Monday is not the first day of the week where many people live.

> Will get System locale only if changed.

I'm not sure I understand.
