### ISSUE TITLE
Custom icon packs broken in latest master

### ISSUE THREAD

**Issue by dkanada** [OpenLauncherTeam/openlauncher#387]
@BennyKok at what point of the process are you switching out the default app icon for the custom icons?

At the moment custom icon packs are broken and I have no idea where the new icons are replacing the defaults, the IconProvider needs a bit of work.

I want to add support for custom icons per app, which will be saved in the database. All icon generation should be handled in a single provider, it should check for an icon with the process below.

1.) If a custom icon is set in the database, use that one.
2.) Check for drawable in selected icon pack. (apps plus open app drawer button)
3.) Use the default icon for apps and shortcuts. (launcher actions hard coded)

**Comment by gsantner** [comment]
1:

1.1 check local instance of this shortcut
1.2 global (as in app drawer too)

It worked at least before migration

**Comment by dkanada** [comment]
Yeah but basically every single class has seen changes since then =p so I can't really narrow it down that much. You are correct on step one, app drawer would need to be heavily modified first though so I forgot about it.

**Comment by dkanada** [comment]
Merged an old class back in and I am making a bit of progress but this is a very convoluted system for loading icons. It turns out OpenLauncher also supports the new adaptive icons somewhere in the code as well. We should add a setting for that so it itsn't enabled by default.

3.1 Check for adaptive icon and apply if enabled in settings

**Comment by gsantner** [comment]
You cant decide on Oreo, if an adaptive icon is available you must use it and cant load the legacy one, sadly. I tried it.

**Comment by dkanada** [comment]
I think it would work if we manually searched for the drawable instead of using Android's package manager.

**Comment by gsantner** [comment]
In general custom pack is working again now or?

**Comment by dkanada** [comment]
They are working again just as before, no new features added yet.

**Comment by gsantner** [comment]
basically setter didnt set, right?

**Comment by dkanada** [comment]
Yup haha

**Comment by dkanada** [comment]
Fixed this ages ago so I am closing it now.
