### ISSUE TITLE
Icon Projection and DragNDrop.

### ISSUE THREAD

**Issue by otakuhqz** [OpenLauncherTeam/openlauncher#395]
Icon projection not working on desktop. 
**step to reproduce:** 
Drag an item from the AppDrawer.
**reason**
code on the onMove method is wrong on class HpDragNDrop.
Also the dragNdrop location is not working propertly on desktop.

**Comment by gsantner** [comment]
we are still in migration, thanks for noticing. if you find more, please report at this issue here

**Comment by dkanada** [comment]
This has been fixed in the latest master, thanks for the report.
