### ISSUE TITLE
No badge on icon app on dock

### ISSUE THREAD

**Issue by AqwelF** [OpenLauncherTeam/openlauncher#396]
#### General information

* **App version:** 0.5.12
* **System:** Oreo 8.1 reserruction remix for honor 9

#### Description

No badge appears on the dock when i have a missed call or an unread message. Is that a bug ?

On the standard launcher with the os i have the dots (badges)

Thanks.

**Comment by dkanada** [comment]
This is not a bug, we currently don't have any plans to implement the badges, sorry.
