### ISSUE TITLE
Search results cut off by keyboard and dock visible in search

### ISSUE THREAD

**Issue by TT-392** [OpenLauncherTeam/openlauncher#400]
#### General information

* **App version:** 0.5.12 (from F-DROID)
* **System:**  8.1.0 (LineageOS 15.1-20180528-NIGHTLY-oneplus3)

#### Description
When opening the search bar, the dock is still visible and when you scroll down all the way, the keyboard is hiding the bottom 3 lines of apps in grid mode and 5 in list mode. these apps are visible when closing the keyboard. When the keyboard is closed the dock appears to be floating in mid air.

![screenshot_openlauncher_20180602-174549](https://user-images.githubusercontent.com/36132003/40878319-8ccc85aa-668f-11e8-89b4-571a2e9f55fc.png) ![screenshot_openlauncher_20180602-180013](https://user-images.githubusercontent.com/36132003/40878329-b06fba5e-668f-11e8-9fc9-769c5a45eff7.png)

**Comment by gsantner** [comment]
not happens at master. was fixed at some point.
