### ISSUE TITLE
SearchBar: filterPredicate logic mistake

### ISSUE THREAD

**Issue by pinkiesky** [OpenLauncherTeam/openlauncher#404]
#### General information

* **0.5.12** (master, commit c0d69da11308d57) 

#### Description
In commit `5c47776 (Migrate SearchBar back)` filter code 

```
if (s.isBlank())
   return@Predicate true
else
   return@Predicate item.label.toLowerCase().contains(s.toLowerCase())
```
convert to
```
if (s.isEmpty())
  return true;
else if (item._label.toLowerCase().contains(s.toLowerCase()))
   return false;

```

and it's look like mistake.

**Comment by gsantner** [comment]
@pinkiesky Thanks for the finding and much thanks for working on it!
Every help is welcome!
If you find more, or want to work on other issues feel free to :).

As said, pretty much android standard rules + formats, only `this.var`->`_var`
