### ISSUE TITLE
Question: can we use kotlin in future pull request?

### ISSUE THREAD

**Issue by pinkiesky** [OpenLauncherTeam/openlauncher#406]
#### Description
Can we use kotlin in future pull request?

I found base kotlin support in build script and it's work perfect for me. 

Of course, should not just rewrite everything on Kotlin, we can just gradually introduce it.

#### Example
For icon drag position fix (issue  #395), need create `DragOptionModel` data class, and kotlin allow me gently create this:

```
data class DragOptionModel(
        val startLocation: PointF = PointF(),
        val location: PointF = PointF(),
       ....
       some another fields and computed properties
       ....
)
```
Alternative code for java looks a little too much :)

And great news  - we can use this data class in both Java and Kotlin! 

PS. Is there any place for the questions asked? Discord? Gitter?

**Comment by gsantner** [comment]
No, we had Kotlin previously and migrated back to java. There was quite some talk about that, and we came to the point that Java only is best for this project :)
