### ISSUE TITLE
Mini-Bar new elements

### ISSUE THREAD

**Issue by D0ve** [OpenLauncherTeam/openlauncher#408]
Would like to suggest new hardly needed elements for mini-Bar :

Battery,  Energy Saving Mode  on/off ;
Wi-Fi, Wi-Fi  on/off ;
Sim Cards, Using Sim Card for Mobile Data  on/off ;
Bluetooth, Bluetooth  on/off ;
Memory, Unmount/Mount SD-card (SD-card off/on) ;
(UPD)
Location on/off ;
Security, Installation from Unknown Sources on/off .

Theese futures are hardly needed to qick access to be  on or off.

**Comment by dkanada** [comment]
I agree, since we have screen lock from the minibar already I think adding these items would not require any new permissions. Device administrators can modify system settings, which probably encompass all of the above items. It would also be really convenient.

**Comment by gsantner** [comment]
Energy Saving e.g. is nothing we can toggle, no single API. Everyone brews his own soup.

**Comment by dkanada** [comment]
Ah good point, energy saving wouldn't work. Bluetooth, WiFi, location, and mobile data might work though.

**Comment by D0ve** [comment]
At least woule be great to use all possible quick switchers:   Bluetooth, WiFi, location, mobile data and SD card   in mini-bar!
But, Energy saving mode, somehow is switchable frome the system integrated Settings.apk ?... may be thrue the root rights or undocumented(not public) API?

**Comment by gsantner** [comment]
we will at no point go for root permission or undocument API methods.
anyway not possible with android P+

**Comment by D0ve** [comment]
Ok. May be in future todo list, it's possible to implement 'root' futures that will work with root permissions, but be inactive without 'root'.
But anyway it's good to have 'quick acces' to switchers that takes 5-9 touches on usual settings app!
upd
I found another few ones that I missed in top..., Location and Security-Installation from Uknown Sources Switchers.

**Comment by gsantner** [comment]
No, even not inactive as default. We don't do anything with root in a launcher.

**Comment by D0ve** [comment]
And root rights won't bring any good stuff(?  I mean, for example, like futures 'freezing' selected working apps in background or so?

**Comment by gsantner** [comment]
You can take a cigarette with both, a lighter and a flamethrower.
Lighter is enough, flamethrower is crazy too much and dangerous.
Hope you understand now.
