### ISSUE TITLE
Widget content is based on wrong widget size

### ISSUE THREAD

**Issue by Lotus815** [OpenLauncherTeam/openlauncher#413]
#### General information

* **App version:** 
OpenLauncher 0.5.12 from F-Droid
WarnWetter https://play.google.com/store/apps/details?id=de.dwd.warnapp
* **System:** 
Android 7.0
Motorola Moto G5

#### Description
* Widget content from Deutscher Wetterdienst app dynamically adjusts displayed content based on widget size.
* After some time in standby, widget content for smaller size gets displayed without changing the actual widget size.
* After moving action of the widget, expected content is displayed properly.
* No problems with pre-installed Motorola launcher.

#### Log
Screen Recording:
[openlauncher_widget.mp4.zip](https://github.com/OpenLauncherTeam/openlauncher/files/2353792/openlauncher_widget.mp4.zip)

**Comment by gropius365** [comment]
same issue here - makes widgets unusable

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
