### ISSUE TITLE
Can't add Firefox page shortcut

### ISSUE THREAD

**Issue by vandys** [OpenLauncherTeam/openlauncher#414]
#### General information

* **App version:** 
0.5.12 (35)

* **System:** 
LineageOS 15.1-20180910-NIGHTLY-ether
(Android 8.1.0)

#### Description
While in Firefox, access page/add page shortcut.  The option is greyed out.
So you can't pin often visited web locations, reached directly from the home page.

**Comment by dkanada** [comment]
Pretty sure this is because we only partially implement the shortcut functionality. I am closing this as a duplicate of #355 but if you have any thoughts on the issue please bring them up over there.
