### ISSUE TITLE
Ask question，thanks

### ISSUE THREAD

**Issue by dtboy1995** [OpenLauncherTeam/openlauncher#415]
How does a launcher app update itself?
- can i use below?
```java
 Uri uri = Uri.fromFile(new File(Environment.getExternalStorageDirectory() + "/" + "update1.apk"));

        Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        intent.setDataAndType(uri,
                "application/vnd.android.package-archive");
        startActivity(intent);

```
- or other methods?

Any help is greatly appreciated!

**Comment by dkanada** [comment]
I have never looked into install intents on Android but that looks like it would work. On newer versions the launcher would need to have permission to install apps before this would work.

**Comment by dtboy1995** [comment]
@dkanada ,thanks. finally i use `pm install -r` to solve it
