### ISSUE TITLE
Bug. Launcher stucked on app drawer.

### ISSUE THREAD

**Issue by serebryakov-av** [OpenLauncherTeam/openlauncher#423]
1. I opened List of Applications (AppDrawer) and locked screen.
2. After night I unlocked screen.
3. List of Applications appeared. I couldn't find a way to get back to home screen.

**Comment by gsantner** [comment]
Please fill out issue template. it has a reason to be there.
note that we don't backsupport <0.6, update & check if happening still there and reopen if so.
