### ISSUE TITLE
Bug. Launcher spontaneously shows arrows on widget.

### ISSUE THREAD

**Issue by serebryakov-av** [OpenLauncherTeam/openlauncher#424]
1. Delete an app from List of Applications (AppDrawer).
2. After that Home screen and arrows will appear.

**Comment by just-Nob** [comment]
Seems to be related to post/issue #343.

**Comment by gsantner** [comment]
Please fill out issue template. it has a reason to be there.
note that we don't backsupport <0.6, update & check if happening still there and reopen if so.
