### ISSUE TITLE
redraw/refresh desktop

### ISSUE THREAD

**Issue by jenniestrongbow** [OpenLauncherTeam/openlauncher#425]
Hello,

I programmatically added some icons to the desktop. But the desktop only refreshes and shows the icons only after several OnResume events (after I open the app drawer several times and go back to the desktop). 

Do you know how to force a full rebuild/refresh of the desktop? 

Thanks

**Comment by dkanada** [comment]
Not sure about that but if you add the apps [here](https://github.com/OpenLauncherTeam/openlauncher/blob/65e4e1bc80380cdfaa6b857d36d2aaff28601e51/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java#L225) they should show up immediately.

**Comment by jenniestrongbow** [comment]
@dkanada , thanks for your answer. What worked for me was simply adding the app icons to the database before setContentView in the onCreate of the main homeActivity.
