### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by princekelly1** [OpenLauncherTeam/openlauncher#426]
Hello, I'm Kelly. 
 I think having a privacy policy statement will be a good thing for your project seeing it kind of have functionalities that may lead to data collection on your end or not. It's a good end users are made aware of the safety of their privacy. I could draft a privacy policy statement if you wish. It's my way of contributing to open source projects.
Also the project can benefit from a FAQ section. If I may

**Comment by dkanada** [comment]
We aren't looking to create either of those documents right now, thanks for the offer though!

**Comment by princekelly1** [comment]
Thanks, when you need one. You can contact me
