### ISSUE TITLE
Broken F-Droid build of v0.6.0

### ISSUE THREAD

**Issue by offa** [OpenLauncherTeam/openlauncher#436]
The [v0.6.0 F-Droid build is broken](https://f-droid.org/wiki/page/com.benny.openlauncher/lastbuild_36). From a first view of the log, it fails by Extra Translation errors and a lint error.

**Comment by offa** [comment]
Btw. congratulations to the ***200th Fork***! :tada:

**Comment by gsantner** [comment]
#435

**Comment by gsantner** [comment]
> Btw. congratulations to the 200th Fork! 🎉

;)
