### ISSUE TITLE
Homescreen-Settings: Problems when upgrading from v.0.5.12 to v.0.6.0 (Bug?)

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#442]
#### General information

* **App version:** 0.5.12 --> 0.6.0 (F-Droid version)
* **System:** Android Oreo 8.1.0

#### Description

After update from 0.5.12 to current 0.6.0, all widgets are replaced by black, semi-transparent "placeholder"-boxes, with a comment inside, informing that the widget wasn't able to be loaded.
New widgets can be placed, even if they are the same that was placed before (i.e. this one's that cannot be loaded after OpenLauncher's update).

Maybe some other settings aren't correctly imported, until now I hadn't the time to check this.

Downgrade via F-Droid failed.

I will describe that behavior more in detail when I find time to check it out.

**Comment by gsantner** [comment]
Hi! 
v0.6.0 was a major update, I myself had no such problem but it may happen due biggest changes ever in the project.
Closing this as we anyway can't restore something and won't backport hackish <0.6 stuff.

Thanks!

**Comment by dkanada** [comment]
Damn, I tried to check for any possible issues upgrading to the new version. Honestly we may want to set up a beta version if we continue work on this launcher. Regarding this but though, I have absolutely no idea why widgets would have changed at all, I don't think I touched that code.

**Comment by just-Nob** [comment]
Maybe your right.
I also have to update my phone to the latest Android Oreo 8.1 update, although I don't believe that this will fix that (but who knows).

I'm aware of the widget's calling information is stored instead of the widget itself.
But I'm confused that the "imported" widget calling vectors in the settings don't work, while the new ones will, although both are referred to the same widget. That's why I thought there's an error in importing the of settings (if they are imported and newly interpreted).

Maybe my problems are caused by an "uncallable" widget that I couldn't get rid of.
