### ISSUE TITLE
Widget cannot be deleted in state with text "widget cannot be added"

### ISSUE THREAD

**Issue by Catfriend1** [OpenLauncherTeam/openlauncher#445]
Device: Xiaomi Mi8
OS: Android 8.1.0 MIUI 10
App: OpenLauncher-fdroid-0.6.0

Reproducer
- add widget
- widget displays correctly
- reboot device
- widget stays black with text "widget cannot be added"
- widget cannot be deleted (delete popup doesn't show when clicking it)

**Comment by dkanada** [comment]
Which widget isn't working on your phone? I will download the app and test it out to see if I can reproduce the issue.

**Comment by Catfriend1** [comment]
So far I've already tested this happens to many apps. For example Tasker and domoticz had this problem. 1&1 weather widget works correctly. I also had the same problem with disappeared widgets on MIUI Launcher, so I'd suspect it's a special xiaomi phone issue. Are there any logs I can grab specifically on certain tags shortly after boot?

**Comment by Catfriend1** [comment]
I tried with the app https://f-droid.org/en/packages/net.etuldan.sparss.floss/ . It's surviving reboots and the widget stays there but if I use Xiaomi local backup , the text "widget cannot be added" just after the app was backed up. You can also reproduce this using ADB backup command from shell or adebar (backup tool for adb by izzysoft) if you don't own a Xiaomi device. I captured two logs for you. (1) is during backup until backup was taken and (2) is after backup when switching to openlauncher to the page that contains the widget.
![screenshot_2018-11-03-11-32-25-521_com benny openlauncher](https://user-images.githubusercontent.com/16361913/47951180-6ee11f00-df5d-11e8-80bd-d98b26ed47ee.png)
[Openlauncher_widget_lost_after_backup.zip](https://github.com/OpenLauncherTeam/openlauncher/files/2544882/Openlauncher_widget_lost_after_backup.zip)

**Comment by dkanada** [comment]
Wait is the issue from just restarts or from restoring from a backup? Those are two separate things, a restart means this could be a widespread issue but I don't think third party backups are even supported, although they should technically work.

**Comment by Catfriend1** [comment]
Hmm, playing around it seems to be two different issues:
- Domoticz App and Tasker sometimes lose the widget on restart (I have no proof but a bad feeling the autostart-restrictions from Xiaomi MIUI ROM may cause this!?)
- adb backup force stops (or freezes?) apps and that leads to the widget never being added again. (taking the previous suspect into account maybe that's Xiaomi specific too).
So I understand your point very well if you say "adb backup" is not supported or customizations Xiaomi made to their firmware are not supported - but - if there's a way to work around this (as it's also happening in the official MIUI launcher since 2016) would be great and very appreciated.

For a starting suggestion: Is it possible for example to build a debug version that retries adding the widget after it failed some minutes later? My intuition somehow tells me that this could maybe solve the issue as I'm always able to add the widget again.

Issue (3) would be: A failed widget with the text "widget cannot be added" like in the screenshot above cannot be removed > I would consider this a bug.

**Comment by seb1458** [comment]
> Wait is the issue from just restarts or from restoring a backup? Those are two separate things, a restart means this could be a widespread issue, I don't think third party backups are even supported although they should technically work.

I have the problem with two widgets: simple calendar and the stock clock widget. I run Lineage OS and the widgets disappear after the restart of my phone. BUT I tested this also on the Evie Launcher and the widgets crashed there as well.

**Comment by dkanada** [comment]
@Catfriend1 do you have any apps installed on an external card like @seb1458 was describing?

**Comment by Catfriend1** [comment]
Good point but, no I don't have an sdcard as the phone hardware only offers internal storage.

**Comment by dkanada** [comment]
I will have a possible fix for this issue on the next release, probably after the holidays are over. A lot of these disappearing item issues are all related so I am trying to fix them all in the next release.

**Comment by Catfriend1** [comment]
I'm happy to test a debug apk for you if you need the feedback before release.

**Comment by Catfriend1** [comment]
Ok, tested 0.7.0 like I said in https://github.com/OpenLauncherTeam/openlauncher/issues/490 I'm still unable to delete the stuck widgets. Will never add widgets again on miui because they are broken after running adb or miui backup on the apps. I didn't store anything on external as the Phone has internal storage only.

**Comment by ashokgaire** [comment]
this comment is for the developer who is working on this issues...

just change some lines in the code 
1.return new WidgetView(context.getApplicationContext()) from WidgetHost.java class
2. _appWidgetManager = AppWidgetManager.getInstance(getApplicationContext()); on HomeActivity.java init() method
..
error info :: W/AppWidgetHostView: updateAppWidget couldn't find any view, using error view android.widget.RemoteViews$ActionException: view: android.support.v7.widget.AppCompatImageView can't use method with RemoteViews: setImageResource()...

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
