### ISSUE TITLE
Consider using espresso as acceptance/UI test framework

### ISSUE THREAD

**Issue by calbrecht** [OpenLauncherTeam/openlauncher#449]
To stabilize and prevent regression bugs to occur, beside #128 consider testing of UI interaction with [espresso](https://developer.android.com/training/testing/espresso/), androids UI testing framework.

While i never did any android development, i'm willing to get started by including this framework into OpenLauncher, if this is a welcome contribution and if someone might be able to give me some hints here and there if i ask for it.

Thanks for the consideration, nevertheless i appreciate your work and the OpenLauncher as is. :)

**Comment by gsantner** [comment]
You are free to opem merge requests for this.
