### ISSUE TITLE
Integrated (App) Search [Bug]: Lack of search Results when choosing Gboard's alternative word suggestion

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#450]
#### General information

* **App version:** v0.6.0 (36) from F-Droid Repo
* **System:** Android 8.1.0 (Oreo)

#### Description

- _Precondition:_

I detected the error that is described below by entering the search string using Swype on Gboard, but this bug doesn't seem to be limited to Swype, but to Google's Gboard's.
I also tried to reproduce it with other soft keyboards ("Hacker's Keyboard", "Xperia Keyboard"), but wasn't able to reproduce it by using them.

Anyway, due to the fact that Gboard's is just Google's keyboard solution that it's installed on most "Vanilla-based" ROMs (a lot of stock ROMs as well, e.g. those offered by Motorola, BQ or Google itself), I think this is an important bug.

- _How to reproduce:_

When entering a search string via Gboard, the search results (i.e. the resulting apps) are shown for Gboard's automatically fulfilled suggestion. When this one isn't the one you had in mind and another suggestion is chosen by you, it seems that from now on the search is limited to the result of Gboard's first made suggestion.

- _An Example:_

1. Open OpenLauncher's integrated search; it doesn't matter if you're going to open it by using the search widget or the Minibar (of search is enabled there).

2. Enter "ing" into OpenLauncher's search string, either by swyping it, or by typing the characters separately one after the other. All apps with that string inside are shown, e.g. every "Settings" app, "Fing", "XING", "RingDroid" etc.

3. Tap on any other suggestion made by Gboard, for example on "Ong". The formerly shown results disappear; presumably you have an empty result list.

4. Even if you now clear the search's input field, the search result is still limited to that you had in step 2 (the "ing"-results), although all apps should be shown due to the empty input string.

5. Leave OpenLauncher's search and open it again. The search is still limited to the "ing"-results; anyway, although the search sticks to this 'biased preselection', a search is still possible (limited to that "Ing"-preselection).

(For sure, the mentioned apps are examples and have to be installed on the device.)

- _How to reset:_

For resetting the 'biased' search, just enter OpenLauncher's Settings and go to
"Desktop"
"Search Bar" section
and change any parameter in it (toggling any parameter twice without leaving the settings is sufficient).

**Comment by gsantner** [comment]
cannot reproduce on dev version
