### ISSUE TITLE
Widgets do not appear correctly on phone boot, launcher needs to be restarted

### ISSUE THREAD

**Issue by fredddii** [OpenLauncherTeam/openlauncher#455]
#### General Information

* **OpenLauncher Version:** 0.6
* **Android Version:** 8.1.0
* **Custom ROM:** LineageOS
* **Install Source:** F-Droid

#### Description

When the device boots I will have to manually restart the launcher for widgets to appear correctly. 

![screenshot_20181128-211149_openlauncher](https://user-images.githubusercontent.com/15217150/49179430-8a6bf980-f352-11e8-957f-ed80e8554bbb.png)

![screenshot_20181128-211211_openlauncher](https://user-images.githubusercontent.com/15217150/49179432-8a6bf980-f352-11e8-94c7-26ef978ff931.png)

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
