### ISSUE TITLE
More actions (feature request)

### ISSUE THREAD

**Issue by IAmNotImportant** [OpenLauncherTeam/openlauncher#466]
__General Information__  
OpenLauncher 0.6.1 (F-Droid), Android 7.0

__Description__  
While configuring the OpenLauncher, I found out that `Action` option (long press screen > bottom center icon) only offers one option: `Open App Drawer`. I'm suggesting to add more, specificaly `Open Switcher` (the overview of currently opened apps).

My phone (and plenty of others) does not have hardware buttons for it, and I find persistent software bottom bar annoying. Would it be possible? Now I have to use third-party, closed-source app to display it, which is annoying.

Thanks for this awesome piece of software.

**Comment by gsantner** [comment]
open seperate issue for each wanted action. if needed.
