### ISSUE TITLE
Builtin calendar and clock!

### ISSUE THREAD

**Issue by DI555** [OpenLauncherTeam/openlauncher#467]
#### General Information

* **OpenLauncher Version:** 6.1
* **Android Version:** 5.0
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Descriprion
Since integrated in OL qute calendar was removed in 6.* versions would like to request it back and with clock either, please!
Without it, I get nothing when clicking on date on the screen(((. I use no system calendar and many people uninstalled it too... .
Many thanks in advance!

**Comment by gsantner** [comment]
Won't return. Use a calendar app, or a app providing a widget.
