### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by bangkoksurprise** [OpenLauncherTeam/openlauncher#468]
#### General Information

  public static final int VERSION_CODE = 37;
  public static final String VERSION_NAME = "0.6.1";
  // Fields from default config.
  public static final String BUILD_DATE = "2019-01-26T23:22Z";* **Android Version:** 7?

* **Install Source:** Source Code

#### Description
OL forces vertical orientation. Where in the code, can this be defaulted for landscape?
Or if someone could update it to respect landscape orientation?

**Comment by perepujal** [comment]
You could set it to rotate the desktop, but if what you want to do is to force landscape, it seems not implemented yet.
A quick fix to force landscape is to apply the following patch and recompile 
HTH
Pere
diff --git a/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java b/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java
index 5a59bd75..23dd7a28 100644
--- a/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java
+++ b/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java
@@ -610,7 +610,7 @@ public final class HomeActivity extends Activity implements OnDesktopEditListene
         if (appSettings.getDesktopRotate()) {
             setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);
         } else {
-            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
+            setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
         }
 
         handleLauncherResume();

**Comment by perepujal** [comment]
Well, I've added a setting in order landscape mode be configurable so  openlauncher continues to display in portrait mode until you change it in the preferences.
It is in my fork in  [https://github.com/perepujal/openlauncher/commit/9f2d640e16bf20cbb3fa8d8f5cd5faf9586c700b](url) 
Could somebody review it before I submit a merge request?
Thanks
Pere

**Comment by dkanada** [comment]
@perepujal this looks useful, but I think it can be integrated into the current setting. The rotate mode should be changed into a list preference with three options, and rather than a nested if statement you can use an else-if statement.

**Comment by perepujal** [comment]
@dkanada  Thanks for the comments, it is now using a list preference and an else if statement.
Let me know if there is something else needed.
[https://github.com/perepujal/openlauncher/commit/9aa7dde505e7d18ce396e4ba5236a85520bd809e](url)
Thanks
Pere

**Comment by dkanada** [comment]
This looks great, when you open a PR I will merge it to master :)
