### ISSUE TITLE
Feature Request: Text shadow

### ISSUE THREAD

**Issue by alfalfascout** [OpenLauncherTeam/openlauncher#470]
#### General Information

* **OpenLauncher Version:** 0.6.1 (37)
* **Android Version:** 6.0
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description

The background I'm using has multiple colors. It would greatly improve readability if I could turn on a text/icon shadow for the home screen and the home screen editor. In the menu, it should probably only need one color selector.

**Comment by gsantner** [comment]
I think we already have a lots of configureable options for text and colors and every bit makes things more complicated. This is not planned currently, but can be added via PR.
