### ISSUE TITLE
Missing activity

### ISSUE THREAD

**Issue by perepujal** [OpenLauncherTeam/openlauncher#471]
#### General Information

* **OpenLauncher Version:** latest git
* **Android Version:** 7.1.2
* **Custom ROM:** lineageos 14.1
* **Install Source:** own build

#### Description
Tux Paint has two different activities both with their own icon that are meant to be launched independently, OpenLauncher only displays the main one, the tuxpaint config one is discarded.

I've found that just removing the check for already existing activity in app/src/main/java/com/benny/openlauncher/util/AppManager.java makes OpenLauncher to add the tuxpaint config activity too, not sure about what side effects this change may produce but I've not found anything obvious up to now.
HTH
Pere

```
diff --git a/app/src/main/java/com/benny/openlauncher/util/AppManager.java b/app/src/main/java/com/benny/openlauncher/util/AppManager.java
index 4de9c4d4..0dc085ad 100644
--- a/app/src/main/java/com/benny/openlauncher/util/AppManager.java
+++ b/app/src/main/java/com/benny/openlauncher/util/AppManager.java
@@ -173,7 +173,8 @@ public class AppManager {
             List<ResolveInfo> activitiesInfo = _packageManager.queryIntentActivities(intent, 0);
             for (ResolveInfo info : activitiesInfo) {
                 App app = new App(_packageManager, info);
-                if (!_nonFilteredApps.contains(app)) {
+                //if (!_nonFilteredApps.contains(app))
+               {
                     _nonFilteredApps.add(app);
                 }
             }
```

**Comment by dkanada** [comment]
Hmmmm I was actually making some changes to the AppManager class for work profile support. This is a separate issue but it is somewhat related, because I was also getting missing apps with those modifications as well.
