### ISSUE TITLE
5 seconds delay

### ISSUE THREAD

**Issue by lucassuzuk** [OpenLauncherTeam/openlauncher#473]
Hey, how hard would it be to implement this [fix](https://help.kustom.rocks/i194-launchers-touch-features-support-aka-remove-5-secs-delay) so there was no need to actually wait 5 seconds when launching an app through another app? I would be willing to try but I had never developed for android before and maybe someone more experienced could do it better.

**Comment by BennyKok** [comment]
ha ha actually, I have tried to do this loooong time ago, but think I have left undone it somehow, it is not very hard, but need testing to see if that support kustom live wallpaper.

**Comment by gsantner** [comment]
Let's not get in trouble with hacks if not needed
