### ISSUE TITLE
Phone app is missing from App Drawar

### ISSUE THREAD

**Issue by AliHamdar95** [OpenLauncherTeam/openlauncher#474]
#### General Information

* **OpenLauncher Version:** 1.0?
* **Android Version:** 1.0?
* **Custom ROM:** None?
* **Install Source:** F-Droid?

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by gsantner** [comment]
Than go to drawer and drop it.
