### ISSUE TITLE
After Reboot - Got an empty start page

### ISSUE THREAD

**Issue by Catfriend1** [OpenLauncherTeam/openlauncher#476]
Recent Version from F-Droid;

- had three pages
- page two is start page
- removed already empty page one
- rebooted phone
- page one came back empty as it was before the removal
- page one was the start page after reboot (but it is expected that if three pages are there it is page two!)

Phone: xiaomi mi8, Android 8.1

**Comment by Catfriend1** [comment]
Note: this can also be reproduced by deleting page one, going to openlauncher's settings and hitting the action restart launcher. Page one reappears and has to be deleted again.

**Comment by gsantner** [comment]
We got multiple such reports and we are aware of this. Closing this as duplicate.
