### ISSUE TITLE
Can't hide search/date bar at all

### ISSUE THREAD

**Issue by xstasi** [OpenLauncherTeam/openlauncher#477]
#### General Information

* **OpenLauncher Version:** 0.6.1
* **Android Version:** 9
* **Custom ROM:** LineageOS 16
* **Install Source:** F-Droid

#### Description

In the app settings i can only see sections for desktop, dock, drawer and appearance, as well as gestures and miscellaneous.

Settings for the search bar and/or date bar seem to be completely missing, despite people having reported to have disabled one or both of them in other issues which makes me think that the setting should be there.

Is there some way to hide it?

**Comment by xstasi** [comment]
Once I entered the settings from the minibar rather than the long press on the desktop, the settings for the search/date bar showed up. It may also have to do with me having performed a reboot in the meantime. Writing this down for posterity, feel free to close if it's not worth researching.

**Comment by gsantner** [comment]
It's in the desktop settings, right. Works in dev version fine
