### ISSUE TITLE
Bug: stucked on app drawer

### ISSUE THREAD

**Issue by coldsmile** [OpenLauncherTeam/openlauncher#478]
#### General Information

* **OpenLauncher Version:** 0.6.1 (37)
* **Android Version:** 8.1.0
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description

Steps to reproduce (1):
- open app drawer
- wait for screen lock

Steps to reproduce (2):
- open app drawer
- open task manager (square button)
- turn off the screen

#423

**Comment by gsantner** [comment]
cannot reproduce on current release
