### ISSUE TITLE
White background and no text in app drawer

### ISSUE THREAD

**Issue by contrapunctus-1** [OpenLauncherTeam/openlauncher#481]
Nokia 6.1
Android v9
OpenLauncher v0.6.1 from F-Droid

Opening the app drawer results in a grid of icons on a white background, with no app names. Seems like a bug.

**Comment by clc-github** [comment]
Try changing the label color.  Settings, App Drawer, Label.

The default label color matches the default background color in my experience.

**Comment by contrapunctus-1** [comment]
Oh, thanks a lot!

Can this please have a saner default?
