### ISSUE TITLE
Open drawer icon removed at launcher reload

### ISSUE THREAD

**Issue by marcocastignoli** [OpenLauncherTeam/openlauncher#484]
General Information
• OpenLauncher Version: 0.6.1 (37)
• Android Version: 9.0
• Custom ROM: None
• Install Source: F-Droid

Every time the launcher reloads the icon is removed. It started to happen when I backupped and restored my configuration changing phones.

**Comment by gsantner** [comment]
It's a known issue that somtimes the last added/item is not saved to db. Closing as duplicate.

For now, try to add something else and wait some seconds before rebooting/restarting.
