### ISSUE TITLE
hide/unhide apps breaks user customization

### ISSUE THREAD

**Issue by TheLoveCaptain** [OpenLauncherTeam/openlauncher#485]
#### General Information
hide/unhide apps breaks user customization
* **OpenLauncher Version:** 0.5.12
* **Android Version:** 8, 7
* **Custom ROM:** None
* **Install Source:** debug

#### Description
after restoring apps from hiding status they dont return to the home screen, only to the app drawer

**Comment by gsantner** [comment]
apps are deleted from desktop upon hiding, so place is free for other app(s).
