### ISSUE TITLE
[bug] name disappear

### ISSUE THREAD

**Issue by zaoqi** [OpenLauncherTeam/openlauncher#488]
#### General Information

* **OpenLauncher Version:** 0.6.1
* **Android Version:** 6.0
* **Custom ROM:** https://github.com/zaoqi/Le_X62X_AOSP6.0/releases
* **Install Source:** NanoDroid

#### Description

https://gitlab.com/Nanolx/NanoDroid/issues/77

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by Tobias-B-Besemer** [comment]
Same issue on Samsung Galaxy S9 with latest Stock (Android 9) and OpenLauncher 0.6.1 directly installed from F-Droid.

**Comment by Tobias-B-Besemer** [comment]
![Screenshot_20190721-115544_OpenLauncher](https://user-images.githubusercontent.com/11881073/61589721-8bd28680-abae-11e9-8d54-b403491d4996.jpg)

**Comment by zaoqi** [comment]
That is because colors of Card View and Label is same.

**Comment by zaoqi** [comment]
I adjusted them in `Settings`

**Comment by Tobias-B-Besemer** [comment]
But thats the default settings...
...so at least the default settings should change...
