### ISSUE TITLE
Option to change the background color of the status bar

### ISSUE THREAD

**Issue by jimigwell** [OpenLauncherTeam/openlauncher#49]
Hi,
I have a bright background on my phone and all of the status bar icons are white so i cannot see them. Is it possible to make the background of the status bar black or to change the color of those icon ?

Thank you very much for the work anyway !

Keep it up

Regards

**Comment by gsantner** [comment]
My suggestion: By default enable "Automatic mode". This means, OL analyzes the top
pixels and generates some kind of mid value, which either is more dark or more light.
Automatic mode takes the oposite of  it. In the dropdown there can be also "dark" and "light" which will set manually. As for statusbar-color (not statusbar-text-color): I would say leave it transparent.

Some hints:  
<http://stackoverflow.com/a/22192691> ; <http://stackoverflow.com/q/33316668>

**Comment by gsantner** [comment]
Note: 
```
View rootView = findViewById(android.R.id.content);
int rootViewVisibility = rootView.getSystemUiVisibility();

// Dark statusbar text 
rootView.setSystemUiVisibility(shouldBeDark() 
  ? rootViewVisibility | View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
  :  rootViewVisibility & !View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
);
```

**Comment by gsantner** [comment]
#151
Note: 
```
View rootView = findViewById(android.R.id.content);
int rootViewVisibility = rootView.getSystemUiVisibility();

rootView.setSystemUiVisibility(shouldBeDark() 
  ? rootViewVisibility | View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
  :  rootViewVisibility & !View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
);
```
