### ISSUE TITLE
Cannot interact with widget after placing it

### ISSUE THREAD

**Issue by RenatoLopes771** [OpenLauncherTeam/openlauncher#490]
General Information
• OpenLauncher Version: Lastest
• Android Version: 8.1.0
• Stock Rom (LG Q series)
• Install Source: F-Droid

Description

After putting a widget on the homescreen I cannot intercat with it, change position or remove it

**Comment by Catfriend1** [comment]
I was stuck with a non working widget for over a year now and could not remove it in 0.7.0 (widget cannot load error) so I created a new page without widgets and dropped the old page . Now the blank page added on startup bug is gone. I will never use widgets again aa they are broken on openlaucher (and on xiaomi miui) for long already.
