### ISSUE TITLE
Let me manually change an app icon

### ISSUE THREAD

**Issue by underlineGalaxy** [OpenLauncherTeam/openlauncher#491]
General Information
• OpenLauncher version: lastest
• Android Version: 8.1.0
• Stock ROM (LG Q series)
• Install Source: F-Droid

Description

Nova Launcher has a feature that lets you manually edit an app icon and name. OpenLauncher only lets you edit the name... it doesn't seem like it's too hard to implement has it's already halfway done. The simplicity argument is that it's already a pretty hidden feature so it's unlikely that most users would stumble by it anyway.

**Comment by gsantner** [comment]
#498
