### ISSUE TITLE
Add shortcut for Camera/Photo

### ISSUE THREAD

**Issue by saechimdaeki** [OpenLauncherTeam/openlauncher#497]
As a frequent user of photo function, I want to have photo function in short cut. If you don't mind, can I do it in November?

**Comment by dkanada** [comment]
Sure! If you add it as a custom action the main changes will be made to [this](https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/util/LauncherAction.java) class. Let me know if you have any questions about the codebase.

**Comment by saechimdaeki** [comment]
Thank you. I'm a student, so I'll try as soon as the exam is over.

**Comment by saechimdaeki** [comment]
Can I create additional classes?The function is performed, but it is not saved as storage, so I want to pass it over to the context to receive it.

**Comment by saechimdaeki** [comment]
Can you tell me what id means?   ex) new ActionDisplayItem(Action.SearchBar, HomeActivity._launcher.getResources().getString(R.string.minibar_title__search_bar), HomeActivity._launcher.getResources().getString(R.string.minibar_summary__search_bar), R.drawable.ic_search, 89)   

whait is 89 mean???

**Comment by dkanada** [comment]
That number is a random value chosen to represent the item. When it gets selected that number can be used to identify the value. It should probably be a constant variable but that's not something we need to do now.

I'm actually not sure if the value is used, but if you search the code base for `89` you might find a switch statement somewhere that uses it to select the right action.

**Comment by saechimdaeki** [comment]
My code needs at least minsdk level of this project, so I processed it through conditional statement. If I send a pull request, can you give me a code review? I'll try to correct it as much as possible (I'm sorry for the grammar error because I've written it through the translator because I'm not good at English)

**Comment by saechimdaeki** [comment]
Where do I add more parts to make the camera appear after pressing action in the gesture section?

**Comment by saechimdaeki** [comment]
Is the Preview camera a little bad? If I connect to an existing camera app and take a picture, I can't see the picture taken in the gallery, so I tried this.
