### ISSUE TITLE
Covers (Action Launcher 3 feature)

### ISSUE THREAD

**Issue by LeapingDragon** [OpenLauncherTeam/openlauncher#50]
An alternative to regular app folders whereby you can choose to have an indicator (or none) on an app icon (see app folders at top, covers at bottom):

![covers](https://www.androidcentral.com/sites/androidcentral.com/files/article_images/2015/07/actionlauncher-cover.gif)

Then swiping on the app in a certain direction will open the cover to reveal an app folder that looks like this:

![covers](http://i.imgur.com/A1Ffezw.png)

This could be extended in the future to require a sequence of taps, multiple directional swipes in a sequence, multi-finger swipe etc.

**Comment by dkanada** [comment]
This is really cool, what launcher are you using that has the feature?

**Comment by LeapingDragon** [comment]
[Action Launcher 3](https://play.google.com/store/apps/details?id=com.actionlauncher.playstore)
