### ISSUE TITLE
Screens added randomly, widgets rearranged with blocked screen

### ISSUE THREAD

**Issue by fmmaresca** [OpenLauncherTeam/openlauncher#508]
#### General Information

* **OpenLauncher Version:** 0.0.7(38)
* **Android Version:** 9.0
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description
With three screens, locked, randomly new screens appears between 2 and 3; sometimes icons/widgets are moved from screen to screen.

**Comment by ni-kw** [comment]
Same here.
Android 10 (on Pixel 4)
0.0.7 (38)

Icons and widgets are moving to other screens (but on same position). New, sometimes empty screens are appearing. And also some widgets are displayd over icons (see screenshot). Like a mixed or overlayed screen.

![Screenshot_20191102-074931](https://user-images.githubusercontent.com/16056721/68086499-1af96680-fe4d-11e9-96b8-85c5ed5f25b1.png)

**Comment by gsantner** [comment]
I'm not aware of this on current release.

Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
