### ISSUE TITLE
Change some of the launcher items for planned features.

### ISSUE THREAD

**Issue by dkanada** [OpenLauncherTeam/openlauncher#51]
I have been digging though home activity trying to fix issue #22 and have a few ideas for launcher items. It looks like shortcuts are used on the desktop while apps are only for the app drawer, correct? There is also a LAUNCHER_APP_DRAWER type that is used to open the app drawer. It would be a good idea to genericise the LAUNCHER_APP_DRAWER type to ACTION so that we more easily add features for this type in the future. It might also reduce bugs if the GROUP type behavior was changed to a container item that holds items rather than an app item that has an array of intents.

We could implement this with the creation of two new items, a group item and an action item, or by modifying the current item to hold different attributes. Action items will only hold the number of the [launcher action](https://github.com/BennyKok/OpenLauncher/blob/e794561a0d9fefb34f1cb391eaa7fc50d87565a5/app/src/main/java/com/benny/openlauncher/util/LauncherAction.java) that they correspond to, and group items will contain an array of items. With this change, app and shortcut items will no longer need to hold an [array](https://github.com/BennyKok/OpenLauncher/blob/e794561a0d9fefb34f1cb391eaa7fc50d87565a5/app/src/main/java/com/benny/openlauncher/widget/Desktop.java#L618) of intents, only the single intent that they need to open. This should reduce the amount of bugs relating to folders on the desktop and will make issues with items a lot easier to debug.

**Comment by BennyKok** [comment]
I used the array to hold all the inner item as to avoid nested action item as this will require Gson parser to do more job, but I agree that this is quite unreadable and very messy when a group instance is create, right a group item.

**Comment by dkanada** [comment]
The best solution I found for implementing groups gives every item a unique number or value. When a group item is created from the configuration, each item in the array is found and added to the group.

1.) Add all apps and shortcuts to the desktop, and hide the apps that are currently inside a group. Add the groups last and create the contents by searching the homepage for each item using its unique number. This solution prevents having to search the json file for each app individually.

2.) Do not add group contents to the desktop. When a group is created, search the json file for each app.

3.) Implement a database for the desktop and dock. Do not add group contents to the desktop. When a group is created, search the database for each app. At this point the settings could also be moved away from json if we wanted to use the tools provided by Android.

**Comment by BennyKok** [comment]
Right this is called a total rewite

**Comment by dkanada** [comment]
Yeah, I can definitely see why you used an array of intents the first time.
