### ISSUE TITLE
Unmotivated appearence of the widget rezize buttons

### ISSUE THREAD

**Issue by mase76** [OpenLauncherTeam/openlauncher#511]
#### General Information

OpenLauncher Version: 0.7.0
Android Version: 9.0
Custom ROM: Omnirom
Install Source: F-Droid

#### Description
Since the update to 0.7.0 I often see an unmotivated appearence of the widget resize buttons. Most times after closing an app.

**Comment by FranzMari** [comment]
Same here, with
OpenLauncher Version: 0.7.0
Android Version: 9.0
Custom ROM: /e/
Install Source: F-Droid

**Comment by mase76** [comment]
This issue is fixed in release 0.7.1.
