### ISSUE TITLE
Duplicate app when load

### ISSUE THREAD

**Issue by Stupidman22** [OpenLauncherTeam/openlauncher#518]
When i try to run and install other app by android studio. The app drawer show duplicate app. 
Please check it . This is always issue so you can try it by yourself. Hope you can fix it soon. Thank you

**Comment by gsantner** [comment]
please add version information and installation source.

**Comment by dkanada** [comment]
Also add the application IDs for both apps so we can compare them, I think you might be installing an app with a debug version or something.
