### ISSUE TITLE
Add internet page and other 1x1 shortcuts to home screen (PWA applications)

### ISSUE THREAD

**Issue by rewkha** [OpenLauncherTeam/openlauncher#522]
#### Description

There is no possibilities to add a a page from Firefox/Chrome or [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) to a home screen. This is very important for the users, who uses PWA instead of regular apps.

This looks like launcher issue, because it's possible on other launchers

![image](https://user-images.githubusercontent.com/3531135/69525769-1a924e00-0f69-11ea-95c8-0f81b557c904.png)
![image](https://user-images.githubusercontent.com/3531135/69525804-2d0c8780-0f69-11ea-9687-b9239502d28f.png)

**Comment by finn0** [comment]
Same thing happens in [Firefox Preview](https://github.com/mozilla-mobile/fenix) neither I can **add a private browsing shortcut** nor **create a shortcut for PWA**.

**Comment by dkanada** [comment]
It was never implemented in the launcher which is why nothing happens.

**Comment by summersab** [comment]
This is the only thing that keeps me from using OpenLauncher instead of Zim. Perhaps you could borrow code from them?
https://github.com/otakuhqz/zimlx

Zim has a few bugs (swipe down gesture doesn't work, rotate causes crashes, etc), but this one feature is why I keep using it.

I'm not an Android dev, but I'll be keeping an eye on this project and will give feedback when it is helpful.

**Comment by natrius** [comment]
Same here, i have an budget app that decided to just develop as PWA and with fennec from f-droid its not possible to add an PWA at all.
As far as i know, it should be an "Install" button in the menu.
Using  https://airhorner.com/ there is no such button.
![IMG_20211111_172150](https://user-images.githubusercontent.com/7243447/141332486-29880ffa-5f90-4190-b300-7a7898c6279b.jpg)

Using a xiaomi mi 9 with miui 12, android 10 and openlauncher 0.7.4

For some reason i got the "add to homescreen" popup actually (button still missing), but it does nothing.

Are there plans to do something with PWA or is nothin planned and i should switch launcher?
