### ISSUE TITLE
Feature request cyclic screens rotations

### ISSUE THREAD

**Issue by Ygarr** [OpenLauncherTeam/openlauncher#528]
#### General Information

* **OpenLauncher Version:** 1.0? Last
* **Android Version:** 1.0? Lineagos 16
* **Custom ROM:** None?
* **Install Source:** F-Droid? yes

#### Description
Please add Cyclic Screens rotation(aka infinite scroll in EMUI).
Also ability to rotate screens from last to first while moving icons(dragging to next screen -> adding to new screen +, dragging to second screen -> to the first existing screen)

**Comment by dkanada** [comment]
Duplicate of #181 so please track the issue there.
