### ISSUE TITLE
alpha4 crashes when clickin on "all apps"

### ISSUE THREAD

**Issue by spaetz** [OpenLauncherTeam/openlauncher#54]
Using the current alpha 4 on my Fairphone2 with Andoid6 (M) I experience a crash of openlauncher when I press the "dots" button to show all apps. The same crash occurs when I use the button via the sidebar. Is there any way to get helpful logs for you? This phone is not rooted so alogcat will probably not help?!

**Comment by BennyKok** [comment]
Are u using the compiled version from the latest source? Cause I added a crash catcher to the app in previous commit l, it should be displayed when the app crashed.

**Comment by spaetz** [comment]
a) Sorry, the version is called alpha3 not alpha4 and is the last compiled version from fdroid.org which was released on April 4.
b) No crash catcher pops up, I just get an dialog saying "OpenLauncher was ended" (in German).

**Comment by BennyKok** [comment]
Does the problem always occur?

**Comment by BennyKok** [comment]
Anyway thanks for reporting the bug, there should be a crash catcher as I add on Apr 2, 2017 ,However I may solved this bug when cleaning, refactoring the code.

**Comment by spaetz** [comment]
Yes. the problem occurs every single time. One more observation: I had added a calender widget before and every time I start OpenLauncher now, it starts with the calendar widget selected and the resizing arrows active. Even if I delete the widget and the select "all apps" leading to the crash, the calendar widget will still appear the same way when I restart OpenLauncher. Weird, isn't it? :-)

**Comment by BennyKok** [comment]
The resizing arrows is active whenever a widget view is instantiated, this is indented.

**Comment by gsantner** [comment]
I think this can be closed?

**Comment by spaetz** [comment]
Actually yes, it does not crash anymore :--).
