### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cpu2910** [OpenLauncherTeam/openlauncher#545]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** 9
* **Custom ROM:** LineageOS 16
* **Install Source:** F-Droid

#### Description
I installed OpenLauncher mainly for icon pack support.
If there are missing icons in the icon pack for some apps, the default icon is displayed.
**I found no option to change the icon to something from the icon pack.**
Editing will only let me change the name.

**Comment by TobiasDev** [comment]
There is a request for this where the maintainer behind this has asked for help. :) 

https://github.com/OpenLauncherTeam/openlauncher/issues/305

I'm also waiting for this! :)

**Comment by gsantner** [comment]
closing as duplicate
