### ISSUE TITLE
Launcher only finds first launcher intent

### ISSUE THREAD

**Issue by frknkrc44** [OpenLauncherTeam/openlauncher#546]
#### General Information

* **OpenLauncher Version:** 0.7.2 (40)
* **Android Version:** 8.1
* **Custom ROM:** LG UX 6.0
* **Install Source:** F-Droid

#### Description
I can't see "Phone" shortcut, because included in "Contacts" app and assigned as second launcher intent. Please fix it, because some apps using launcher intents more than one, like this example.

**Comment by Catfriend1** [comment]
Is this fixed by 0.7.3?

**Comment by frknkrc44** [comment]
I tried and seems to be fixed @Catfriend1, I'm closing this issue.

**Comment by Catfriend1** [comment]
Thanks for fixing it. Updated and works for me, too on Xiaomi Miui 11.
