### ISSUE TITLE
Minibar sound button opens "Do not disturb access" settings

### ISSUE THREAD

**Issue by frknkrc44** [OpenLauncherTeam/openlauncher#547]
#### General Information

* **OpenLauncher Version:** 0.7.2 (40)
* **Android Version:** 8.1
* **Custom ROM:** LG UX 6.0
* **Install Source:** F-Droid

#### Description
When I click to sound button from minibar, opens "do not disturb access" settings.

**Comment by gsantner** [comment]
it triggers what your system defines for sound, we don't know what this is for every systems. On normal android aosp it opens Sound (volume levels) and dnt.

**Comment by frknkrc44** [comment]
You can try `android.provider.Settings.ACTION_SOUND_SETTINGS` Intent, this one works on my phone.
