### ISSUE TITLE
widgets don't open the app in android10 MIUI11

### ISSUE THREAD

**Issue by bobeeeze** [OpenLauncherTeam/openlauncher#549]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** 10
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description
I've got 2 widgets on the desktop. The information in the widgets is updated, it's working. But i can't open the app clicking on it.

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
