### ISSUE TITLE
Long pressing on the home screen then tapping 'Widgets' results opening of the device settings

### ISSUE THREAD

**Issue by sudomain** [OpenLauncherTeam/openlauncher#560]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** FireOS 5.3.6.4 (based on android 5.1)
* **Custom ROM:** no
* **Install Source:** F-Droid

#### Description
Long pressing on the home screen shows the home screen editor with these buttons:
1. Remove
2. Home
3. Lock
4. Widget
5. Action
6. Settings

If the Widget button is pressed, normally a list of widgets is shown, but on this particular device the stock settings app is opened.

If possible, I would like to be able to use widgets on this device since the stock ROM doesn't allow it. If that isn't possible, perhaps it would be useful to notify users that certain devices don't support widgets

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
