### ISSUE TITLE
Widgets move and widget menu (remove, resize)

### ISSUE THREAD

**Issue by mmm4m5m** [OpenLauncherTeam/openlauncher#567]
#### General Information

* **OpenLauncher Version:** v0.7.2 (40)
* **Android Version:** 9 Pie
* **Custom ROM:** No. Stock OxygenOS 9.0.6. Rooted
* **Install Source:** F-Droid

#### Description

When I long press termux widget, then both happen at the same time:
- the menu popup (remove, resize)
- and the widget moving begin
I am not able to use the menu. I can not resize and I can not remove the widget.
I had to move widget to separate page and then delete the whole page.

Acidently I dropped the widget outside the page area (down/left) and Open Launcher crashed. It happens every time. It is easy to reproduce.

Thanks.

**Comment by DonQuiche** [comment]
### General Information

- OpenLauncher Version: v0.7.3 (41)
- Android Version: 9 Pie
- Custom ROM: No. (FP3)
- Install Source: F-Droid

Same problem with resizing full screen widgets : extremely difficult!
It appears as soon as I long press the widget : the vibration occurs and **the widget moves** (while my finger does **not**).
This means I have to systematicaly replace it properly at the top left corner of screen, and cannot resize it!  Sometimes requires more than a dozen trials before being able to resize.
**Feature request**: please make sure the widget stays where it was when long pressed (until my finger moves.)

Also : resize buttons disappear too quickly.  
**Feature request**: Please leave them on longer, or untill I tap somewhere else.

**Comment by agilob** [comment]
It is even possible to reside a widget? Eg. calendar widget by default is 2x4  but I would like it to be full page

**Comment by dkanada** [comment]
It should technically be possible, but widgets are a bit finnicky in this app so sometimes it doesn't work.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
