### ISSUE TITLE
System wide shortcuts and shortcuts created by 1x1 widget (like Settings or Termux)

### ISSUE THREAD

**Issue by mmm4m5m** [OpenLauncherTeam/openlauncher#568]
#### General Information

* **OpenLauncher Version:** v0.7.2 (40)
* **Android Version:** 9 Pie
* **Custom ROM:** No. Stock OxygenOS 9.0.6. Rooted
* **Install Source:** F-Droid

#### Description

I would like very much if OpenLauncher support shortcuts.
System wide shortcuts or own defined shortcuts
Shortcuts created by Activity Launcher (FDroid)
Shortcuts created by 1x1 widgets that create - like settings app or termux app.

For this I installed Lawnchair and Kiss launcher.
Kiss is able to show the shortcuts created by "Activity Launcher".
Lawnchair works good with 1x1 widgets but these shortcuts are not visible inside Kiss. (I also tried to set Kiss as default launcher and press "reload shortcuts" from Kiss settings).

Thanks.

**Comment by TheoRet** [comment]
Shortcut support would be highly appreciated.

I'm using Lineage OS 16 and latest F-Droid version.

I have many apps installed via the Shelter app (inside work profile). Shelter depends on creating shortcuts on the desktop to start these apps with only one tap.

Shortcut work with standard Trebuchet, but OpenLauncher looks better and has more useful features. Shortcut support ist the only thing that keeps me from using it.

**Comment by mickenordin** [comment]
I would also really want this feature.

**Comment by gsantner** [comment]
#522 #637

**Comment by Kenoubi** [comment]
I don't agree that this is a duplicate, as the issue it was marked a dupe of is marked fixed but I still see no way to add ordinary Android shortcuts using OpenLauncher. (Am I missing something? v0.7.4 (42) installed from F-Droid.)
