### ISSUE TITLE
Moving Widgets Requires 1 Unnecessary Space to the Right of Destination Under Condition

### ISSUE THREAD

**Issue by Yowlen** [OpenLauncherTeam/openlauncher#57]
To trigger this bug, first, place 2 widgets. (It may also trigger w/ a widget & a shortcut, but I didn't test.) Resize them as necessary in order to allow them to fit side-by-side. Put one widget on the far right-hand part of the screen, then try to place the other immediately to the left of it. The user will get an "Insufficient space" error.

Using Alpha 3 on F-Droid.

**Comment by aabaker** [comment]
There have been quite a few fixes in this area and I can't reproduce this on the latest git HEAD or on the 0.5.0 release. Is this still an issue?

**Comment by Yowlen** [comment]
It's easier now, yeah. I'm getting crashes everywhere I go as of the latest F-Droid build so I haven't been able to successfully move anything or do a lot of things for that matter, but they're unrelated to this, so this issue can be closed, I think.

**Comment by Yowlen** [comment]
Whoops. That's what I get for not reading. There's no way for me to test this one because the latest F-Droid build crashes when I try to move anything. It crashes in other places, too.

**Comment by Yowlen** [comment]
Sorry. Been a long day. Yes, this issue is fixed.
