### ISSUE TITLE
Samsung phone app is hidden

### ISSUE THREAD

**Issue by Erwane** [OpenLauncherTeam/openlauncher#570]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** 8.0.0
* **Custom ROM:** Stock
* **Install Source:** F-Droid

#### Description
The Samsung phone app is hidden, even if i reset all OpenLauncher settings and cache.
Others launcher see it well and i can launch it via "contact -> call"

Thanks.

**Comment by frknkrc44** [comment]
@Erwane please try new version, it seems to be fixed.

**Comment by Erwane** [comment]
Working fine. Thanks.
