### ISSUE TITLE
Getting lots of pop-up with "Create a widget and allow access?"

### ISSUE THREAD

**Issue by finn0** [OpenLauncherTeam/openlauncher#573]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** 7.1.1
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description

From few days, after installing and uninstalling of apps, I'm getting a series of pop-up with "Create a widget and allow access?" message,

<img alt="openlauncher-pop-up" src="https://user-images.githubusercontent.com/28824347/75400295-bf208500-58f6-11ea-9d48-a18a854918c0.png" width=400>

even after checking `Always allow OpenLauncher to create widgets and access their data` box and then `Create`, I'm still getting these pop-up (and lots of, at least 3 or 4 times).

### Steps to reproduce
- Install an app from F-Droid app.
- After installation, probably you'll get a series of pop-up with `Create a widget and allow access?` message; check "Always allow OpenLauncher to create widgets and access their data" and then click `create`.
- Create a shortcut icon of newly installed apps on home screen.
- Now, uninstall the app.

Probably this time also you'll get series of pop-up.

### Expected behavior
Remember answer provided by user.

### Actual behavior
After (un)installation, every time getting series of pop-up.

~PS: **Can anybody else reproduce this behavior**?~

**Comment by phi2lIP** [comment]
I am experiencing exactly the same behavior.
With each new installation or update (no matter if via Fdroid or Aurora Store) receiving multiple very annoying pop-ups.
For some Apps (e.g. Geocaching) Pop-ups even occur very often during normal execution (always jumping back to home screen and putting app into background)

Problem started around March 10th without any (aware/active) change of involved components.

My System:
device: nash (Moto Z2 Force XT1789-06)
microG LineageOS 16 (Android 9)  build from 2020-01-09
OpenLauncher v0.7.2(40)

**Comment by Stupidman22** [comment]
Can any one find and fix this issue ?

**Comment by darkrilin** [comment]
I'm also getting this issue on my device whenever apps are installed/uninstalled/updated. 

It takes focus away from whatever is currently being viewed, and the only way to reliably clear the multiple notifications is via pressing the android home button.

Device: Moto G6 Play XT1922-1 (Jeter)
/e/ v0.7 (Android 9) build from 2019-08-27
OpenLauncher v0.7.2

**Comment by JonnyTech** [comment]
Still happening with new version:

Package: com.benny.openlauncher
Version: v0.7.3 (41)
Flavor: Default (release)
Build date: 2020-04-30T01:56Z
ISource: com.google.android.packageinstaller
VCS Hash: 73968b61ee99b74b4b8a7205c34d3bc8a58422d8

**Comment by Stupidman22** [comment]
Finally found this problem cause. Hope any one fix this. 
[https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/viewutil/ItemViewFactory.java](url)

This line:
`LOG.error("Unable to bind app widget id: {} ", cn);
                    Intent intent = new Intent(AppWidgetManager.ACTION_APPWIDGET_BIND);
                    intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, appWidgetId);
                    intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_PROVIDER, cn);
                    HomeActivity._launcher.startActivityForResult(intent, HomeActivity.REQUEST_PICK_APPWIDGET);
                    return null;`
Remove other condition to reproduce this issue. I guess some user go to this condition.

**Comment by DonQuiche** [comment]
Same problem, except it happens daily, dozens of times, after instaling new apps or not:
   
- Open Launcher Version: 0.7.3
- Android Version: 9
- Custom ROM: None (standard FP3)
- Install Source: F-Droid

Steps to reproduce systematicaly:
1. Open the apps list and press home button: the popup appears
2. Long press home screen -> page layout view, then press home button: the popup appears
3. actualy, just pressing the home button does it.

Rebooting the phone clearled most of the problem (only 1 popup while pressing home button and testing steps above 12 times), though the home button now **no longer returns to the main screen from other screens**.

Please note : most of the time, popup appears on top of all icons.  A few times though, it appears **behind** desktop icons, though the screen capture always shows it on top.
![Screenshot_20200616-172423](https://user-images.githubusercontent.com/59511690/84810781-1a909300-b00c-11ea-9931-ee77aec8b811.png)

**Comment by DrizztFR** [comment]
I've got the same issue and it came right after I uninstalled some apps. One of them had a widget and I wonder if uninstalling it without the prior removal of the widget could be the culprit

**Comment by gsantner** [comment]
Please send pull request with fix.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
