### ISSUE TITLE
WebApps widgets not available

### ISSUE THREAD

**Issue by JonnyTech** [OpenLauncherTeam/openlauncher#574]
#### General Information

* **OpenLauncher Version:** v0.7.2 (40)
* **Android Version:** 8.1 Oreo
* **Custom ROM:** None, stock (rooted)
* **Install Source:** F-Droid

#### Description

Widgets list does not show those for WebApps https://github.com/tobykurien/webapps / https://f-droid.org/en/packages/com.tobykurien.webapps/

#### Log

n/a

**Comment by gsantner** [comment]
use.search. #522 #637
