### ISSUE TITLE
Multiple widgets per app are indistinguishable

### ISSUE THREAD

**Issue by smurfix** [OpenLauncherTeam/openlauncher#575]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** 9
* **Custom ROM:** None, Fairphone 3
* **Install Source:** F-Droid

#### Description

The widget list needs to distinguish multiple widgets per app, ideally by showing their preview image and by listing their size.

e.g. the "local weather" app has eight. widgets. No way to distinguish between them.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
