### ISSUE TITLE
Near-impossible to place items on the top row with persistent search bar removed

### ISSUE THREAD

**Issue by Yowlen** [OpenLauncherTeam/openlauncher#58]
Title pretty much says it. The Remove thing takes up the whole row in a 5x4 desktop with that persistent bar at the top disabled, leaving maybe a millimeter of space that I can use to place icons or widgets without them getting removed. I have a cheap phone w/ a 4.5 inch screen (LG Leon LTE), if it makes any difference.

The remove thing needs to be shrunken down on the left & right sides so that it covers about half of a single icon's space.

Using Alpha 3 on F-Droid.

**Comment by BennyKok** [comment]
Ok

**Comment by r0bbie** [comment]
Having the same issue - it's really difficult to drop widgets in the top row without accidentally removing them!

**Comment by BennyKok** [comment]
Did u guys disable the clock/(named search bar in settings)

**Comment by r0bbie** [comment]
@BennyKok Yes I have that disabled in my settings.

**Comment by leo-graf** [comment]
I think the preferable (long-term) solution would be to shrink the the draggable screen area on drag events like it's done when using the stock launcher. 

![dragevent](https://cloud.githubusercontent.com/assets/7384959/25070090/5be155e6-2294-11e7-9c90-dde771bb2234.png)

**Comment by BennyKok** [comment]
or do you guys like a pop menu like nova launcher did?

**Comment by BennyKok** [comment]
I think I will have both in the settings.

**Comment by leo-graf** [comment]
I never used Nova Launcher and i can't install it on my Phone as I dont use Google Play Services. I'll check it on an emulator but this can take some days. 
I would stick to one solution then because it doesn't seem important to me to have multiple options. It's not an everyday use case for most of the users and there are a lot more things to do.

**Comment by BennyKok** [comment]
@leo-graf  well thanks for you reply.

**Comment by leo-graf** [comment]
Your Welcome :) Great Project already, i will add some more issues in the next days

**Comment by Yowlen** [comment]
I actually do use Nova Launcher, but I'd have to agree with @leo-graf in that implementing both isn't necessary and wastes time better spent polishing other areas that I know exist. I'm not picky, as long as it's functional. If someone specifically requests the other option later, then we can think about expanding the options, but function is more important than looks to me.

But I disagree on the zoom out method. It will have issues if there's plans to implement the Pixel launcher icon capabilities that let app developers create custom actions assigned to their icons when long-pressed. The reason being that upon zooming out, the icon/widget often moves over the background to stay with the finger, so releasing would sometimes place it in a new spot, and therefore not reliably trigger the dropdown menu.

And just to clarify for @leo-graf, the popup is the current method where the remove option pops up on top of the area without zooming out. Nova uses a smaller area similar to my original suggestion up top. Nova also has the custom icon actions like Pixel, btw.

**Comment by gsantner** [comment]
I also would also go for leo-graf's posted method

**Comment by BennyKok** [comment]
Very detailed review, let me think.

**Comment by dkanada** [comment]
I am going to vote for the popup method as long as the actual popup is implemented to look more like a drop down menu than what the menu in nova currently looks like. I am not a fan of the separated options with rounded edges, it would look nicer as a rectangle in my opinion.

**Comment by BennyKok** [comment]
For now, here is an temporary solution, the bar size is now sat to wrap_content in both direction.

**Comment by neolovich** [comment]
Can you explain the solution? For me it is impossible to put a widget at the top of the homescreen because they getting removed.

**Comment by BennyKok** [comment]
Now the slide down option bar's size was reduced. Should have more space to place app on the top
