### ISSUE TITLE
Feature Request: Remove drawer button when using gestures

### ISSUE THREAD

**Issue by chris42** [OpenLauncherTeam/openlauncher#581]
First of all thanks for the work on this great launcher! I just started using it and love it. Simple and fast!

I think the drawer button could be deactivated and replaced with another app button when using gestures to open the drawer, as to swipe up is so similar to pressing the button. Combined with #542 it would be really awesome.

**Comment by dkanada** [comment]
You can already do this by removing the drawer button and then enabling swipe up to open the app drawer in the settings.

**Comment by chris42** [comment]
Sorry, was looking in the settings... DUH
