### ISSUE TITLE
Direct access to website does not work

### ISSUE THREAD

**Issue by wuniversales** [OpenLauncherTeam/openlauncher#582]
General Information

OpenLauncher Version:0.72
Android Version: 4.4.2
Custom ROM: None
Install Source: F-Droid

When trying to add a shortcut to any web page using firefox, it does not work, the shortcut is not created.#### Description

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by gsantner** [comment]
use.search. #522 #637
