### ISSUE TITLE
Changelog shortcut

### ISSUE THREAD

**Issue by JonnyTech** [OpenLauncherTeam/openlauncher#587]
#### General Information

* **OpenLauncher Version:** 0.7.3 (41)
* **Android Version:** 9.0
* **Custom ROM:** AOSP GSI
* **Install Source:** F-Droid

Package: com.benny.openlauncher
Version: v0.7.3 (41)
Flavor: Default (release)
Build date: 2020-04-30T01:56Z
ISource: com.google.android.packageinstaller
VCS Hash: 73968b61ee99b74b4b8a7205c34d3bc8a58422d8

#### Description

In the app's `About` page, the last item is `Copy build information`. Clicking on it does copy the details to the clipboard but it also shows a popup with the changelog.

Can you please add a seperate button for the changelog?

Also maybe show an information toast to state that the text has been copied because there is currently no feedback.

Lastly, the changelog only goes up to v0.5.1 so can that be updated?

**Comment by gsantner** [comment]
Nobody is maintaining the changelog atm best is to checkout commit history.
