### ISSUE TITLE
Moving widgets to a full page

### ISSUE THREAD

**Issue by Yowlen** [OpenLauncherTeam/openlauncher#59]
Moving a widget to a full page will give an "Insufficient Space" error, but the widget actually stays on that screen, overlapping any icons or other widgets that are already there. It should instead be sent back to the page it was picked up from.

Using Alpha 3 on F-Droid.

**Comment by BennyKok** [comment]
Oh, ok

**Comment by dkanada** [comment]
Are there any space calculations for widgets right now? I think all we need to do is modify the ACTION_DROP state to handle widgets as well.
