### ISSUE TITLE
Widgets keeps relocating to most left screen, overlaying each other

### ISSUE THREAD

**Issue by Pratched** [OpenLauncherTeam/openlauncher#591]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 9
* **Custom ROM:** /e/ FP3
* **Install Source:** F-Droid

#### Description

Whenever I adjust multiple widgets on different screens, after a while the widgets relocate to the most left screen. In case they have been at the same coordinates, they overlay.
Also happened earlier on the original FP3 OS.

**Comment by vdbhb59** [comment]
I agree. This happens on Android 10 as well. Moreover, upon random sysui reboots some widgets come twice and overlap.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
