### ISSUE TITLE
adding widget makes openlauncher crash

### ISSUE THREAD

**Issue by robintalma** [OpenLauncherTeam/openlauncher#595]
#### General Information

* **OpenLauncher Version:** 0.7.3(41)
* **Android Version:** 9.x on Blackbird bv9800
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description
When I tried to add Widget n'y holding a ronger on the wallpaper, then clicking "widget" an android message told me that "settings" app stop working (and launcher freeze 2-3 seconds). 

I think it's about the way "settings" ils calmes.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
