### ISSUE TITLE
Gesture on top of widgets

### ISSUE THREAD

**Issue by remi-dupre** [OpenLauncherTeam/openlauncher#596]
#### General Information

* **OpenLauncher Version:** v0.7.3 (41)
* **Android Version:** 9
* **Custom ROM:** /e/OS
* **Install Source:** /e/OS custom store (which probably uses F-Droid repos here)

#### Description

Doing gestures on top of widgets doesn't appear to work on my device. I think this could also be the cause of https://github.com/OpenLauncherTeam/openlauncher/issues/312?

Anyway this could be a nice thing to implement for heavy use of widgets, in my case I use a full-screen KWGT widget which makes gestures basically not usable.

Maybe there should be a feature switch (eg. in advanced settings), since gestures should be forwarded to widgets in some cases (but I don't think it currently works? https://github.com/OpenLauncherTeam/openlauncher/issues/531)

**Comment by karthikiyengar** [comment]
This is also true when swiping over icons.

**Comment by kofaysi** [comment]
> This is also true when swiping over icons.

Yeah, I had to create an blank column (no icon, no widget) over half of the screen to be able to use any gestures.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
