### ISSUE TITLE
Deleted page keep re-appearing

### ISSUE THREAD

**Issue by ghost** [OpenLauncherTeam/openlauncher#597]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 6.0.1
* **Custom ROM:** Valence ROM for SG J2
* **Install Source:** F-Droid

#### Description
A deleted page keep re-appearing on desktop.

**Steps to reproduce:**
1. Use fresh install/data-cleared Open Launcher.
2. Add icon on new right/second page and delete the left/first page.
3. Restart Launcher.

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by DonQuiche** [comment]
- OpenLauncher Version : 0.7.3(41)
- Android version 9
- Standard Rom: Fairphone 3
- Install source : F-Droid

**Same problem** occured to me:
1. I moved all icons (only 4) from the rightmost screen to a new screen, creating a blank new screen which was NOT the last one,
2. I used that new empty screen to test various widgets, which did not work ->
3. In desktop update view, deleted that empty page,
4. restart the launcher: the empty page is back.

**Temporary solution**: 
1. move back, one by one, all icons on the last page to the empty page,
2. Delete the LAST (now empy) page on the right,
3. restart the launcher: OK.
