### ISSUE TITLE
Keep app icons layout on launcher when using Adopted Storage feature

### ISSUE THREAD

**Issue by ShapeShifter499** [OpenLauncherTeam/openlauncher#60]
I have an issue where apps that have been installed to Adopted storage get removed on reboot because the system loads quicker then the SD card can be mounted.   I'd like to see an feature where you can "save" app layouts so everything doesn't get cleared on a reboot. 

Moto X Pure
LineageOS 14.1

**Comment by BennyKok** [comment]
Ok, let me see what i can do about this.

Maybe i can explain what happen when an app is not found and the launcher has started, the app item will set to invalidate and it will not be read when the layout is creating.

**Comment by dkanada** [comment]
We could add a function to remove the app when an APP_UNINSTALLED message is returned from an uninstallation instead of checking when the launcher has started. This wouldn't work when an app is removed in another location though like in the device settings.

**Comment by BennyKok** [comment]
Actually it will check every time the view is about to create because the appinfo are stored in the appmanager, so if there don't have the appinfo for specific app that means the app is not in the device now, so that is what going to be happen as I said above.

**Comment by BennyKok** [comment]
but that is also good idea

**Comment by gsantner** [comment]
Just some input:
Nova saves the whole layout, no remove/update at restart. When user clicks on some app icon, OR swipes to another page, the cleanup code starts running, and app icons get removed. Click on some app icon, which is already removed will say "this app is not installed", after that also here all non-installed will get removed.

**Comment by BennyKok** [comment]
ok we'll use this approach.

**Comment by BennyKok** [comment]
maybe we add this to the settings

**Comment by gsantner** [comment]
I don't think theres a need for a setting, or a way to turn it off, this should work always

**Comment by BennyKok** [comment]
#16 someone would like to auto clean up, and we'll see.

**Comment by dkanada** [comment]
@ShapeShifter499 is this still an issue?

**Comment by ShapeShifter499** [comment]
@dkanada It is

**Comment by ShapeShifter499** [comment]
@dkanada @BennyKok    I currently have 0.5.3 (24) of OpenLauncher installed and it's still an issue here.   I'll go to set up my home screen with all my favorite and most used apps but see it cleared when I reboot. It only affects the apps that are installed to the "adopted storage".  I'll have to drag all the apps back to the home screen until the next reboot.

**Comment by projectextremum** [comment]
Catapult & trebuchet does the thing properly as far as I have used.
