### ISSUE TITLE
Getting to move or remove a widget can be incredibly difficult with some of them

### ISSUE THREAD

**Issue by Porkepix** [OpenLauncherTeam/openlauncher#601]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 10
* **Custom ROM:** Stock
* **Install Source:** F-Droid

#### Description

With some widgets (here, the issue was reproduced with Blokada's widget), it can be very difficult if not impossible to get the widget in the mode where user can move it or get the menu to remove it.
I couldn't reproduce it with other widgets I tried, but it's specific to OpenLauncher: couldn't reproduce it either with the same widget with Pixel's native Launcher.

Instead of getting to move the widget, or getting its menu, OpenLauncher enter in its global edit mode, as visible in this screenshot:

![Screenshot_20200605-153519](https://user-images.githubusercontent.com/709500/83882421-60af4200-a742-11ea-8281-6e1a2954f7e4.png)

**Comment by eliotb** [comment]
Problem also occurs with Weather widgets (/e/ os). But not music player widget.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
