### ISSUE TITLE
Widgets are not displayed properly

### ISSUE THREAD

**Issue by faxefix** [OpenLauncherTeam/openlauncher#605]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 6.0.1 (Blackberry Priv)
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description
Some of the Widgets I use doesn't work properly with OpenLauncher: when initially configured, everything works fine, but quite soon - I believe after going to standby - one widget is invisible (Kontact Widget), two others (Google notices and DWD Weather App) seem to be resized in some kind of way - the widget is as big as before, but with limited amount of content.
When resized, the widgets return to normal (until next standby).

**Comment by JonnyTech** [comment]
I can also confirm this on Android 8, 9 and 10. To fix temporarily have to go to: OpenLauncher Settings >> Advanced >> Restart

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
