### ISSUE TITLE
Reset for the widgets

### ISSUE THREAD

**Issue by tochemoca** [OpenLauncherTeam/openlauncher#611]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 8.1.0
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description
Hi! I've had a problem for a few weeks now: the launcher keeps restarting, asking me to give permission to run widgets, and some days it's too annoying.

I have installed version 0.7.3 on an Android 8.1.0, running on a BQ Aquaris C phone.

Greetings and thank you very much for everything!

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by DC7IA** [comment]
I'm also affected by this issue.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
