### ISSUE TITLE
Not all widgets available

### ISSUE THREAD

**Issue by shanemd** [OpenLauncherTeam/openlauncher#614]
#### General Information
It seems like many widgets are missing from the widget list.

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 10
* **Custom ROM:** Stock Pixel
* **Install Source:** F-Droid

#### Description
When I try to add a widget to the home screen, many are missing. For example, the 'Direct dial' widget provided by the Google contacts app is missing, as is the 'Direct message' widget. 

Pixel launcher widget panel:
![Screenshot_20200901-223807](https://user-images.githubusercontent.com/463393/91925920-0de31900-eca4-11ea-8e4b-fd713500ba16.png)

OpemLauncher widget panel:
![Screenshot_20200901-223845](https://user-images.githubusercontent.com/463393/91925970-2f440500-eca4-11ea-8dc3-4e0841889d11.png)

Notice the missing widgets. In fact, no widgets from the Google contacts app show up at all. Neither the widget from the Docs app. I'm sure there are many more, and I'm happy to look through them more carefully if that will help with debugging.

I like the feel of this launcher, but I won't be using it until this bug is fixed since I rely on the direct dial/message widgets.

Let me know if you need any more info.

Cheers
Shane

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
