### ISSUE TITLE
"Recent Apps" not working on Android10

### ISSUE THREAD

**Issue by CorvusCorax** [OpenLauncherTeam/openlauncher#618]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 10
* **Custom ROM:** None (Stock ROM, Fairphone3)
* **Install Source:** F-Droid

#### Description

The list of "Recent apps" (more accurately the list of currently started apps still in background/cache) can be accessed on most Phones via the square button on the bottom.

This list has been an "optional launcher feature" up to and including Android 9 - On Fairphone 3 it was provided by the Stock Launcher Quickstep (com.android.launcher3) However up until Android9 the system itself also provides this functionality if the launcher does not implement it (with a slightly different UI)

I have been using OpenLauncher for many months and had com.android.launcher3 uninstalled, so the list of recent apps was coming from the core android system itself.

Now the phone updated to Android10 via OTA update, and the "recent apps" list does no longer work. Clicking on it does nothing.

Similar issues exist when googling for "recent apps" on Samsung 10 - unrelated to OpenLauncher, but the workaround is the same: reinstall the stock launcher.

This also worked for the Fairphone. Reinstalling the old com.android.launcher3:

If multiple launchers are installed, and the active "default" launcher app does not provide the functionality, it looks like android falls back to any other launcher or app that does provide it and starts it.

However under Android 10 if no other launcher is installed but Openlauncher, the system is not fully functional, missing the "recent apps" functionality. 

Up until Android 9, there was a fallback from one of the core android apps. This no longer exists. Now the launcher MUST provide this functionality.

#### Steps to reproduce

- Make OpenLauncher the default launcher
- Uninstall all other launchers but Openlauncher on Android 10 - including the system / stock launcher(s)
( for example using "pm uninstall --user 0" on adb shell)
- Reboot phone
- Start an app
- Go back to launcher/desktop
- Open recent apps list to switch back to first app

### Expected outcome:
- App list opens
### Actual outcome:
- Nothing happens

#### Log

No log provided, problem is systematic

**Comment by niektuytel** [comment]
so only the system apps are displaying on the screen ? (than i know the solution)

**Comment by gsantner** [comment]
"Recent Apps" is usually a feature by the OS, not the launcher. If still something open and you know the fix, please dev&test it and make pull request. thx.
