### ISSUE TITLE
[FR] Integrate app search in app drawer

### ISSUE THREAD

**Issue by keunes** [OpenLauncherTeam/openlauncher#619]
Hello,

Thanks so much for this launcher! Just started exploring, and (though there are a few glitches) I like it a lot.

One thing I would like improve is the option to search for apps. Currently it (the search button) is located on the home screen. What I like about the default launcher of my phone (Fairphone 3, I think they use more or less Google's stock launcher) is that there's an option to search for apps in the app drawer. I like it mainly for two reasons:
* My screen is rather big so the app drawer button is much more easily accessible
* It cleans up the desktop

While I don't see the need, I guess that some would like to see a setting for it to keep current behaviour.

**Comment by gsantner** [comment]
#599
