### ISSUE TITLE
Moving widgets assumes touch position is top left square but it is actually the centre

### ISSUE THREAD

**Issue by aabaker** [OpenLauncherTeam/openlauncher#62]
When moving a widget, if you pick up the widget by something other than the top left cell, it assumes that the touch position when you put it down should be the top left square but while you move it you are moving the centre position. As a result the widget does not drop where the preview showed it. 

This is best demonstrated using a widget that is either 3 cells tall or 3 cells wide on an empty page so other items aren't in the way of potential drop positions. Pick the widget up by the bottom right corner. Attempt to place in the top left corner of the page.  It will drop below or to the right of where you tried to drop it.

I suspect line 191 of Desktop.jave should subtract half of (widget width-cellwidth) from p2.x and half of widget height - cell heigtht from p2.y before calling addItemToPosition()

**Comment by BennyKok** [comment]
I will take a look,
