### ISSUE TITLE
Integrate minibar settings with main settings

### ISSUE THREAD

**Issue by keunes** [OpenLauncherTeam/openlauncher#620]
I see that the minibar has its own set of settings.

**Problem**: Currently it's possible to 'lock yourself out' of further changes to the minibar.

**Repeduce**: Open the minibar settings, deselect the minibar settings (to not display it in the minibar), close the settings.

**Proposed solution**: Add a new main entry in the settings screen (under 'interfaces') for the minibar. Tapping on it would open the minibar settings screen (as currently is).

**Comment by gsantner** [comment]
Long press some desktop screen, and you get the "Settings"  button on the bottom-right. So no, you can still access OL settings without minibar.
