### ISSUE TITLE
[Enhancement] Display widget resize buttons longer

### ISSUE THREAD

**Issue by keunes** [OpenLauncherTeam/openlauncher#622]
**Problem**: I'm trying to resize my calendar widget, but before I get how the increase/decrease buttons work (I'm used to dragging in my phone's default launcher), the resize buttons have disappeared again.

**Solution**: Display the buttons for a longer time period, and until the user taps elsewhere on the screen. Possibly even _only_ hide when tapping elsewhere on the screen.

The buttons are only visible after a very conscious user action (long press + select menu item), so displaying them longer isn't harmful.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
