### ISSUE TITLE
[FR] Unify colour choices (minibar, settings, app drawer)

### ISSUE THREAD

**Issue by keunes** [OpenLauncherTeam/openlauncher#623]
It's great that I can select the colour for the app (the settings) but, with all due respect to the creators of this great launcher, quite useless. Doesn't fit with the app's 'mission statement' to balance customisability and simplicity.

At the same time, it's not possible to set the colour of the minibar.

I think it would be nice to have a single colour selector for all three elements. Or, alternatively, introduce a colour setting for the minibar, and ditch the setting for the app itself.

**Comment by gsantner** [comment]
I think it's what users like at OpenLauncher, more options for these kind of things. So rather add more than remove/combine.

**Comment by keunes** [comment]
If the intention is not to consolidate settings, I think the following request is left:

> introduce a colour setting for the minibar

**Comment by gsantner** [comment]
If you are interested, yes please go ahead, make the changes and pull request. Thanks 😄

**Comment by keunes** [comment]
Unfortunately not everyone can code - I am one of those people that can't - please don't assume everyone can. I'm a mere translator. Hence the feature request (otherwise I would have sent a pull request).

**Comment by gsantner** [comment]
I'm aware of that, but somebody else who might read this, might be able to.

**Comment by gsantner** [comment]
I'm aware of that, but somebody else who might read this, might be able to.

See, there is literally NOBODY contributing code to the project and people just keep opening new feature requests and bug reports. Hence I close less important stuff because I anyway not have enough spare time to take care, and seemingly nobody else is interested to do either.
