### ISSUE TITLE
[Feature Request] App drawer only mode

### ISSUE THREAD

**Issue by geckolinux** [OpenLauncherTeam/openlauncher#626]
Hi there, I think this feature request might be fairly simple to implement:  I would like an option to use Open Launcher in a mode similar to iOS, where the home button takes me directly the open app drawer. All the rest of the functionality appears to be there to use it in this mode.
Thanks a lot for developing Open Launcher!

**Comment by gsantner** [comment]
we already had that and decided to remove it. though if you are interested and can provide a good working solution, do it and make a pull request.
