### ISSUE TITLE
Improve handling / calculation of available screen space

### ISSUE THREAD

**Issue by leo-graf** [OpenLauncherTeam/openlauncher#63]
### 1. Top (Desktop)
The space which is occupied by the notification bar should not be available for app icons if fullscreen mode is disabled.

### 2. Bottom (Dock & Drawer)
There is a lot of unused Space below the apps in the dock. This Space even grows if hardware keys are used as the software keys are hidden then. When using software keys it makes sense to have some kind of visual seperation but without them the Drawer should be fullscreen and the dock should only take the space where the icons are.

**Software keys**
![software_keys](https://cloud.githubusercontent.com/assets/7384959/25303698/ac837560-2758-11e7-8bf8-09179399f703.png)

**Hardware keys**
![hardware_keys](https://cloud.githubusercontent.com/assets/7384959/25303699/afc3980e-2758-11e7-85f4-48aabe7ea65c.png)

**Drawer Scroll with hardware keys**
![drawer_scroll](https://cloud.githubusercontent.com/assets/7384959/25303714/e9dfa294-2758-11e7-9dfc-9ef0cc50e6bf.png)

**Drawer Pages with hardware keys**
![drawer_pages](https://cloud.githubusercontent.com/assets/7384959/25303717/f4b40444-2758-11e7-91a7-0e679ea93987.png)

**Comment by BennyKok** [comment]
Oh, because my phone was using software key, so I never discover this problem.

**Comment by kosciak9** [comment]
![screenshot_20170428-000358](https://cloud.githubusercontent.com/assets/4347034/25506413/dc2a8090-2ba6-11e7-842f-5f6445254336.png)

I find it kind of funny - it's exactly opposite for me :)

**Comment by BennyKok** [comment]
OH no..

**Comment by BennyKok** [comment]
Yo guys check out the latest commit, I think this should be fixed as I am overriding the `onApplyWindowInsets` method in those custom views and they should be getting the correct nav bar height for padding.

**Comment by leo-graf** [comment]
Yes u are right, it displays correctly now. If I change to the App Drawers cards view there still seems to be a minor issue with this.

![issue](https://cloud.githubusercontent.com/assets/7384959/25541386/bafa7e72-2c4e-11e7-975d-0176f5c64c4b.png)

**Comment by kosciak9** [comment]
When will this update hit F-Droid?

**Comment by BennyKok** [comment]
You mean it too close to the bottom?
Right I will push it to GitHub later.

**Comment by leo-graf** [comment]
Yes, i was talking about the bottom padding. It just doesnt look right if the dots stick to the bottom..
