### ISSUE TITLE
Date bar : offer more sensitive date format presets

### ISSUE THREAD

**Issue by breversa** [OpenLauncherTeam/openlauncher#632]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 7.1.2
* **Custom ROM:** /e/ OS
* **Install Source:** F-Droid

#### Description
Hi there !
Currently, the offered format presets are several variations of the US date format (i.e. `month day year`) which, according to Wikipedia (https://en.wikipedia.org/wiki/Date_format_by_country), is only used in the USA, Kenya and Ghana.
The rest of the world uses mainly the `day month year` format, with `year month day` (https://en.wikipedia.org/wiki/ISO_8601) being second.

Hence, it would cater to more people worldwide to offer those formats (only) as presets :

1. `year month day` (I admit I'm partial to it as it make mathematically more sense :) )
2. `day month year`
3. `month day year`

And unless there's a huge demand for another date format, I'd leave the presets to that, as there's still the available option for a custom date format.

I haven't given to much thought regarding the time format. I guess that YMD and DMY users would prefer a 24h format, while MDY would prefer a 12h but I might be wrong.

**Comment by gsantner** [comment]
Hey it's fully configurable to user needs and don't see a need to make changes here.

**Comment by breversa** [comment]
Well… I for one spent much more time than I'm willing to admit to read the `strftime` documentation in order to reproduce the ISO 8601 format. I then gave up and came here to create this feature request, in the hope that it helps some other poor chaps like me.
