### ISSUE TITLE
Overlapping widgets / app-icons after uninstalled apps

### ISSUE THREAD

**Issue by har0ke** [OpenLauncherTeam/openlauncher#634]
#### General Information

* **OpenLauncher Version:** 0.7.3 and the current master: 8810069cea7ead90a42782532c8110c1de481c1d
* **Android Version:** 10
* **Custom ROM:** linage os 17.1 (RedmiNote 5 Pro)
* **Install Source:** f-droid / build from source

#### Description
When uninstalling apps, widgets and app-icons get moved around and may also overlap. I am only able to reproduce this issue one out of three times. Neither app-icon nor widget of the uninstalled app needs to be present on the home screen.

If someone gives me some pointers to a module that might reorganize the home-screen on specific events, I will try fixing the issue.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
