### ISSUE TITLE
Feature request or question: Can we add ability to create browser shortcuts to home screen?

### ISSUE THREAD

**Issue by viperperidot** [OpenLauncherTeam/openlauncher#643]
Hello,

I am not sure if this is an issue just for me or a feature that needs to be added. But when I try to add a web browser shortcut to my home screen it does not appear. I click on 'Add to Home' in my web browser (I have tried several browsers) and it does not add the icon to the home screen.

Please let me know if this functionality is already added and if this is a unique issue to myself.

Thanks!

**Comment by gsantner** [comment]
Use.search. #522 #637
