### ISSUE TITLE
Openlauncher doesn't see Google maps

### ISSUE THREAD

**Issue by alekksander** [OpenLauncherTeam/openlauncher#65]
launcher „does not see” google maps application, that other launchers show. not in the grid, not in the hide apps list.
google maps is not chose to be hidden anywhere.

**Comment by BennyKok** [comment]
have you tried cleaned up the launcher settings?

**Comment by BennyKok** [comment]
I have it... I can see Google Maps in my phone. Anyone else.

**Comment by alekksander** [comment]
please close, it seem not to be related to OpenLauncher after all. 
(maps are not listed anywhere in my phone now, but other launchers only… quite weird.)
