### ISSUE TITLE
hiding apps from grid, but not from dock

### ISSUE THREAD

**Issue by alekksander** [OpenLauncherTeam/openlauncher#66]
i don't know if it's a bug, or a feature, but now when we hide app it disappears from app grid **and** from bottom dock. 
the desired behavior in my understanding is to hide icon from grid only, because if it's in dock, it's intended to be there by user. perhaps there should be possibility to choose between „hide from grid” and „hide everywhere”.

**Comment by BennyKok** [comment]
so you mean when you hide an app, it did not auto remove from the dock?

**Comment by alekksander** [comment]
It did. I'd like it to hide it from grid, but remain in dock.

**Comment by dkanada** [comment]
Why do you want an app to show up in your dock but not your app drawer? Just trying to figure out a use case, that seems like it defeats the point of hiding the app.

**Comment by neolovich** [comment]
That would be a nice option. Hide the apps from the grid but leave it at the dock or Homescreen (like Nova Launcher for example).

**Comment by 12people** [comment]
Just filed a related task, except concerning search results: https://github.com/OpenLauncherTeam/openlauncher/issues/193 .
