### ISSUE TITLE
[Request] Could you please put a lock on hidden apps. With possibility to have different unlocking code or method as on the device itself. 

### ISSUE THREAD

**Issue by prkfsz** [OpenLauncherTeam/openlauncher#663]
#### General Information

* **OpenLauncher Version:** 1.0?
* **Android Version:** 1.0?
* **Custom ROM:** None?
* **Install Source:** F-Droid?

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by Dark1616** [comment]
#9999

**Comment by Dark1616** [comment]
#663
