### ISSUE TITLE
Can't hide page marker/indicator in the app drawer

### ISSUE THREAD

**Issue by joaocandre** [OpenLauncherTeam/openlauncher#666]
#### General Information

* **OpenLauncher Version:** 0.7.4 (42)
* **Android Version:** 11
* **Custom ROM:** LineageOS w/ microG 18.1
* **Install Source:** F-Droid

#### Description

With a paged app rawer, the page marker/indicator is always visible, even after disabling it in Settings > App Drawer > Position Indicator.

![Screenshot_20220104-120504_OpenLauncher](https://user-images.githubusercontent.com/1812344/148056922-00f78ace-790f-4185-b80d-9c5a6f1288ea.png)

**Comment by Ptitg** [comment]
Fixed by #641
