### ISSUE TITLE
Seek advice from you as an app developer

### ISSUE THREAD

**Issue by zyx666666** [OpenLauncherTeam/openlauncher#672]
Dear app developer:
Nowadays, our team has developed a tool that can detect and automatically repair accessibility problems in the app. We hope to receive your suggestions and opinions as an app developer.
Here, the accessibility problem I mentioned includes two types of problems: Text Contrast issue and Image Contrast issue. The former one corresponds to visible text, where there is a low contrast ratio between the text color and background color. The latter refers to images with a low contrast ratio between the foreground and background colors.
The following image shows the detection function and repair effect of our tool(this image is from your app):
![image](https://user-images.githubusercontent.com/48061456/157721476-d260a5cf-a773-4c1f-8cf1-0e0b641949fc.png)

(and this image is from the other app):
![image](https://user-images.githubusercontent.com/48061456/157721541-3c2fe3b4-ecab-42dc-b493-056f51ea8a06.png)

I want to know whether you think it is necessary to detect this problem and how effective you think our repair is. Sincerely hope to get your reply. Your reply is very important to me!

**Comment by gsantner** [comment]
The project is not actively developed. If you however take your time to improve the project - by whatever means (automated/manually), I review pull requests.
