### ISSUE TITLE
Suggestion: add more app on gesture

### ISSUE THREAD

**Issue by meradoou** [OpenLauncherTeam/openlauncher#69]
Hello,
Please add more applications choice on gesture?
Thank you

**Comment by BennyKok** [comment]
U mean open an app via gesture?

**Comment by meradoou** [comment]
Yes, please

**Comment by BennyKok** [comment]
OK, please give me some times. Thanks.

**Comment by BennyKok** [comment]
Mission accomplished :)

**Comment by meradoou** [comment]
Thank you. I'll wait the new version :)

**Comment by BennyKok** [comment]
But the F-droid update is so slow, if you are using F-Droid, maybe I will upload the apk to the repo later
