### ISSUE TITLE
Feature Request: Give folders a name.

### ISSUE THREAD

**Issue by hamishmb** [OpenLauncherTeam/openlauncher#690]
#### General Information

* **OpenLauncher Version:** 0.7.4 (42)
* **Android Version:** 11.
* **Custom ROM:** No.
* **Install Source:** F-Droid.

#### Description

Unable to name folders (as far as I can tell)

**Comment by mrpenner** [comment]
@hamishmb if you're talking about folders of icons on the homescreen, long-press then tap edit to name the folder.

**Comment by hamishmb** [comment]
Ah, my bad. I can't believe I never tried that. Is there a note about it somewhere?
