### ISSUE TITLE
Advertise and get one or more team members for help developing?

### ISSUE THREAD

**Issue by natrius** [OpenLauncherTeam/openlauncher#704]
Unfortunately this looks a bit like the app is dead and i think thats really unforutnate because i liked it a lot. 
Maybe you could advertise in reddit and somewhere to get a bit attention and a bit of development power to get this going again? Its a really good practical launcher and it would be a shame if it would be gone.

**Comment by gsantner** [comment]
I'm not the owner of the project, don't have control over the google play ID, and have too little of time free to put into here - not wanna fork and do everything on my own either.

**Comment by joe-average-user** [comment]
It would be nice if someone could write in big letters in some readme that the widget resize works with tap, and not drag. This has cost me several weeks trying to resize some widget and never succeeded. Until today where I found out that one has to double-tap one of the four possible directions to increase or decrease size accordingly.
Now I find it to be a great open source launcher.

**Comment by gsantner** [comment]
There is in big letters that the project is discontinued. :)

**Comment by joe-average-user** [comment]
You know the real difference between open and closed source software? open source software can be discontinued, but closed source will be buried.
Only that you declare it discontinued now does not mean it will be in the future. It is no closed source, it will not vanish.

**Comment by gsantner** [comment]
Of course, feel free to fork and improve!
