### ISSUE TITLE
[Feature Requst] Multiple app drawers

### ISSUE THREAD

**Issue by bsaunder2002** [OpenLauncherTeam/openlauncher#708]
#### General Information

* **OpenLauncher Version:** 0.7.4 via F-Droid
* **Android Version:** 12 or whatever crap is forced down my throat this week...
* **Custom ROM:** I wish...I have a T-Mo phone...even de-bloating risks a brick
* **Install Source:** F-Droid?  Hell yeah!

#### Description
So...people ask for folders...I've shunned them in the past.  That being said...my single app drawer is getting full.  Folders would be hard to stub into OpenLauncher (as other posts say and I believe)...yet I thought...what if we had 2 or 3 app drawers.  Say swipe up = main drawer, another action/any defined like swipe left = my work apps, swipe right = my fun apps, ...

Would multiple app drawers be easy to add?

**Comment by gsantner** [comment]
OpenLauncher is not in active development and I don't think having multiple app drawer lists is something that would be added
