### ISSUE TITLE
"This app isn't available for your device because it was made for an older version of Android"

### ISSUE THREAD

**Issue by nicolas-raoul** [OpenLauncherTeam/openlauncher#713]
#### General Information

* **OpenLauncher Version:** Google Play as of September 12, 2023
* **Android Version:** 14
* **Custom ROM:** No, out-of-the-box Pixel 7 Pro
* **Install Source:** Google Play

#### Description

You may just need to bump targetSdk in the manifest.

![Screenshot_20230912-223422](https://github.com/OpenLauncherTeam/openlauncher/assets/99590/ac45eb6e-dde1-4196-b25f-094099ae7231)

**Comment by gsantner** [comment]
The original author of the project is absent since many years and nobody else has access to that store entry.
