### ISSUE TITLE
Custom color for AppDrawer text when using Cards

### ISSUE THREAD

**Issue by gsantner** [OpenLauncherTeam/openlauncher#83]
Currently the text-color of the AppDrawer is not controllable, it is always gray. If a user changes the card color to a darker color the text becomes unreadable.

**Comment by dkanada** [comment]
I think we can keep this open, I would like to add the text color preference to the dock and app drawer as well.

**Comment by gsantner** [comment]
It is controllable now. but in combination with folder color (of desktop folders). We should seperate those
