### ISSUE TITLE
OpenLauncher doesn't utilize the screen space correctly on phones without virtual keys

### ISSUE THREAD

**Issue by sterbfly** [OpenLauncherTeam/openlauncher#88]
The distance between dock and the bottom should not be so huge
![OpenLauncher using space irrationally](https://cloud.githubusercontent.com/assets/15799238/25780634/c4a8fb30-333b-11e7-886a-8f6bca47021e.jpg)

Nova Launcher, for comparison
![Nova Launcher utilizing space correctly](https://cloud.githubusercontent.com/assets/15799238/25780641/f84b870a-333b-11e7-91f1-20b6342e420c.jpg)

Phone: Meizu m1 note
OS: Flyme 6 (Android 5.1.1)

**Comment by BennyKok** [comment]
Which version of OpebLauncher are u using?

**Comment by sterbfly** [comment]
Was using 0.3.1. Updating to 0.3.2.1 fixed the issue.
