### ISSUE TITLE
Taking an app out of the folder with two apps

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#97]
produces "empty" yet occupied place

**Comment by dkanada** [comment]
Are you using the latest version from F-Droid? I think 0.4.0 should have fixed this issue.

**Comment by ildar** [comment]
Indeed

**Comment by ildar** [comment]
Yes, the bug is fixed, but done it messy.
Putting apps into and outof folders frequently toasts "not enough space".
0.5.0
https://github.com/OpenLauncherTeam/openlauncher/issues/118
